/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define BONE_SPINE                 1
#define BONE_HEAD                  2
#define BONE_LEFTUPPERARM          3
#define BONE_RIGHTUPPERARM         4
#define BONE_LEFTHAND              5
#define BONE_RIGHTHAND             6
#define BONE_LEFTTHIGH             7
#define BONE_RIGHTTHIGH            8
#define BONE_LEFTFOOT              9
#define BONE_RIGHTFOOT             10
#define BONE_RIGHTCALF             11
#define BONE_LEFTCALF              12
#define BONE_LEFTFOREARM           13
#define BONE_RIGHTFOREARM          14
#define BONE_LEFTSHOULDER          15
#define BONE_RIGHTSHOULDER         16
#define BONE_NECK                  17
#define BONE_JAW                   18
