/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */

#define BODYPART_TORSO             3
#define BODYPART_GROIN             4
#define BODYPART_LEFTARM           5
#define BODYPART_RIGHTARM          6
#define BODYPART_LEFTLEG           7
#define BODYPART_RIGHTLEG          8
#define BODYPART_HEAD              9
