/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define CAMMODE_TRAIN              3
#define CAMMODE_FOLLOWPED          4
#define CAMMODE_SNIPER             7
#define CAMMODE_ROCKETAIM          8
#define CAMMODE_FIXED              15
#define CAMMODE_VEHICLEFRONT       16
#define CAMMODE_VEHICLEDEFAULT     18
#define CAMMODE_BOATDEFAULT        22
#define CAMMODE_WEAPONAIM          46
#define CAMMODE_ROCKETAIM2         51
#define CAMMODE_WEAPONAIM2         53
#define CAMMODE_VEHICLEPASSENGER   55
#define CAMMODE_HELICHASE          56
#define CAMMODE_GROUNDCHASE        57
#define CAMMODE_FLYBYCHASE         58
#define CAMMODE_GROUNDCHASE2       59
#define CAMMODE_FLYBYCHASE2        62
#define CAMMODE_FLYBYCHASE3        63
#define CAMMODE_PILOTCHASE         64
