/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define CARMOD_SPOILER_PRO                   1000   //Certain Transfender cars
#define CARMOD_SPOILER_WIN                   1001   //Certain Transfender cars
#define CARMOD_SPOILER_DRAG                  1002   //Certain Transfender cars
#define CARMOD_SPOILER_ALPHA                 1003   //Certain Transfender cars
#define CARMOD_HOOD_CHAMPSCOOP               1004   //Certain Transfender cars
#define CARMOD_HOOD_FURYSCOOP                1005   //Certain Transfender cars
#define CARMOD_ROOF_ROOFSCOOP                1006   //Certain Transfender cars
#define CARMOD_SIDESKIRT_RSKIRT              1007   //Certain Transfender cars

#define CARMOD_NITRO_5                       1008   //Most planes and Most Helicopters
#define CARMOD_NITRO_2                       1009   //Most planes and Most Helicopters
#define CARMOD_NITRO_10                      1010   //Most planes and Most Helicopters

#define CARMOD_HOOD_RACESCOOP                1011   //Certain Transfender cars
#define CARMOD_HOOD_WORXSCOOP                1012   //Certain Transfender cars
#define CARMOD_LAMPS_ROUNDFOG                1013   //Certain Transfender cars
#define CARMOD_SPOILER_CHAMP                 1014   //Certain Transfender cars
#define CARMOD_SPOILER_RACE                  1015   //Certain Transfender cars
#define CARMOD_SPOILER_WORX                  1016   //Certain Transfender cars
#define CARMOD_SIDESKIRT_LSKIRT              1017   //Certain Transfender cars

#define CARMOD_EXHAUST_UPSWEPT               1018   //Most cars
#define CARMOD_EXHAUST_TWIN                  1019   //Most cars
#define CARMOD_EXHAUST_LARGE                 1020   //Most cars
#define CARMOD_EXHAUST_MEDIUM                1021   //Most cars
#define CARMOD_EXHAUST_SMALL                 1022   //Most cars

#define CARMOD_SPOILER_FURY                  1023   //Certain Transfender cars
#define CARMOD_LAMPS_SQUAREFOG               1024   //Certain Transfender cars
#define CARMOD_WHEELS_OFFROAD                1025   //Certain Transfender cars

#define CARMOD_SULTAN_SIDESKIRT_RALIEN       1026   //Sultan
#define CARMOD_SULTAN_SIDESKIRT_LALIEN       1027   //Sultan
#define CARMOD_SULTAN_EXHAUST_ALIEN          1028   //Sultan
#define CARMOD_SULTAN_EXHAUST_XFLOW          1029   //Sultan
#define CARMOD_SULTAN_SIDESKIRT_LXFLOW       1030   //Sultan
#define CARMOD_SULTAN_SIDESKIRT_RXFLOW       1031   //Sultan
#define CARMOD_SULTAN_ROOF_ALIEN             1032   //Sultan
#define CARMOD_SULTAN_ROOF_XFLOW             1033   //Sultan

#define CARMOD_ELEGY_EXHAUST_ALIEN           1034   //Elegy
#define CARMOD_ELEGY_ROOF_XFLOW              1035   //Elegy
#define CARMOD_ELEGY_SIDESKIRT_RALIEN        1036   //Elegy
#define CARMOD_ELEGY_EXHAUST_XFLOW           1037   //Elegy
#define CARMOD_ELEGY_ROOF_ALIEN              1038   //Elegy
#define CARMOD_ELEGY_SIDESKIRT_LXFLOW        1039   //Elegy
#define CARMOD_ELEGY_SIDESKIRT_LALIEN        1040   //Elegy
#define CARMOD_ELEGY_SIDESKIRT_RXFLOW        1041   //Elegy

#define CARMOD_BROADWAY_SIDESKIRT_RCHROME    1042   //Broadway
#define CARMOD_BROADWAY_EXHAUST_SLAMIN       1043   //Broadway
#define CARMOD_BROADWAY_EXHAUST_CHROME       1044   //Broadway

#define CARMOD_FLASH_EXHAUST_XFLOW           1045   //Flash
#define CARMOD_FLASH_EXHAUST_ALIEN           1046   //Flash
#define CARMOD_FLASH_SIDESKIRT_RALIEN        1047   //Flash
#define CARMOD_FLASH_SIDESKIRT_RXFLOW        1048   //Flash
#define CARMOD_FLASH_SPOILER_ALIEN           1049   //Flash
#define CARMOD_FLASH_SPOILER_XFLOW           1050   //Flash
#define CARMOD_FLASH_SIDESKIRT_LALIEN        1051   //Flash
#define CARMOD_FLASH_SIDESKIRT_LXFLOW        1052   //Flash
#define CARMOD_FLASH_ROOF_XFLOW              1053   //Flash
#define CARMOD_FLASH_ROOF_ALIEN              1054   //Flash

#define CARMOD_STRATUM_ROOF_ALIEN            1055   //Stratum
#define CARMOD_STRATUM_SIDESKIRT_RALIEN      1056   //Stratum
#define CARMOD_STRATUM_SIDESKIRT_RXFLOW      1057   //Stratum
#define CARMOD_STRATUM_SPOILER_ALIEN         1058   //Stratum
#define CARMOD_STRATUM_EXHAUST_XFLOW         1059   //Stratum
#define CARMOD_STRATUM_SPOILER_XFLOW         1060   //Stratum
#define CARMOD_STRATUM_ROOF_XFLOW            1061   //Stratum
#define CARMOD_STRATUM_SIDESKIRT_LALIEN      1062   //Stratum
#define CARMOD_STRATUM_SIDESKIRT_LXFLOW      1063   //Stratum
#define CARMOD_STRATUM_EXHAUST_ALIEN         1064   //Stratum

#define CARMOD_JESTER_EXHAUST_ALIEN          1065   //Jester
#define CARMOD_JESTER_EXHAUST_XFLOW          1066   //Jester
#define CARMOD_JESTER_ROOF_ALIEN             1067   //Jester
#define CARMOD_JESTER_ROOF_XFLOW             1068   //Jester
#define CARMOD_JESTER_SIDESKIRT_RALIEN       1069   //Jester
#define CARMOD_JESTER_SIDESKIRT_RXFLOW       1070   //Jester
#define CARMOD_JESTER_SIDESKIRT_LALIEN       1071   //Jester
#define CARMOD_JESTER_SIDESKIRT_LXFLOW       1072   //Jester

#define CARMOD_WHEELS_SHADOW                 1073   //Most cars
#define CARMOD_WHEELS_MEGA                   1074   //Most cars
#define CARMOD_WHEELS_RIMSHINE               1075   //Most cars
#define CARMOD_WHEELS_WIRES                  1076   //Most cars
#define CARMOD_WHEELS_CLASSIC                1077   //Most cars
#define CARMOD_WHEELS_TWIST                  1078   //Most cars
#define CARMOD_WHEELS_CUTTER                 1079   //Most cars
#define CARMOD_WHEELS_SWITCH                 1080   //Most cars
#define CARMOD_WHEELS_GROVE                  1081   //Most cars
#define CARMOD_WHEELS_IMPORT                 1082   //Most cars
#define CARMOD_WHEELS_DOLLAR                 1083   //Most cars
#define CARMOD_WHEELS_TRANCE                 1084   //Most cars
#define CARMOD_WHEELS_ATOMIC                 1085   //Most cars
#define CARMOD_STEREO                        1086   //Most cars
#define CARMOD_HYDRAULICS                    1087   //Most cars

#define CARMOD_URANUS_ROOF_ALIEN             1088   //Uranus
#define CARMOD_URANUS_EXHAUST_XFLOW          1089   //Uranus
#define CARMOD_URANUS_SIDESKIRT_RALIEN       1090   //Uranus
#define CARMOD_URANUS_ROOF_XFLOW             1091   //Uranus
#define CARMOD_URANUS_EXHAUST_ALIEN          1092   //Uranus
#define CARMOD_URANUS_SIDESKIRT_LXFLOW       1093   //Uranus
#define CARMOD_URANUS_SIDESKIRT_LALIEN       1094   //Uranus
#define CARMOD_URANUS_SIDESKIRT_RXFLOW       1095   //Uranus

#define CARMOD_WHEELS_AHAB                   1096   //Most Cars
#define CARMOD_WHEELS_VIRTUAL                1097   //Most Cars
#define CARMOD_WHEELS_ACCESS                 1098   //Most Cars

#define CARMOD_BROADWAY_SIDESKIRT_LCHROME    1099   //Broadway

#define CARMOD_REMINGTON_BULLBAR_CHGRILL     1100   //Remington
#define CARMOD_REMINGTON_SIDESKIRT_LCHROMEF  1101   //Remington

#define CARMOD_SAVANNA_SIDESKIRT_LCHROME     1102   //Savanna

#define CARMOD_BLADE_ROOF_CONVERTIBLE        1103   //Blade
#define CARMOD_BLADE_EXHAUST_CHROME          1104   //Blade
#define CARMOD_BLADE_EXHAUST_SLAMIN          1105   //Blade

#define CARMOD_REMINGTON_SIDESKIRT_RCHROMEA  1106   //Remington

#define CARMOD_BLADE_SIDESKIRT_LCHROME       1107   //Blade
#define CARMOD_BLADE_SIDESKIRT_RCHROME       1108   //Blade

#define CARMOD_SLAMVAN_REARBULLBAR_CHROME    1109   //Slamvan
#define CARMOD_SLAMVAN_REARBULLBAR_SLAMIN    1110   //Slamvan
#define CARMOD_SLAMVAN_FRONT_SIGN1           1111   //Slamvan
#define CARMOD_SLAMVAN_FRONT_SIGN2           1112   //Slamvan
#define CARMOD_SLAMVAN_EXHAUST_CHROME        1113   //Slamvan
#define CARMOD_SLAMVAN_EXHAUST_SLAMIN        1114   //Slamvan
#define CARMOD_SLAMVAN_BULLBAR_CHROME        1115   //Slamvan
#define CARMOD_SLAMVAN_BULLBAR_SLAMIN        1116   //Slamvan
#define CARMOD_SLAMVAN_FBUMPER_CHROME        1117   //Slamvan
#define CARMOD_SLAMVAN_SIDESKIRT_RCHROME     1118   //Slamvan
#define CARMOD_SLAMVAN_SIDESKIRT_RWHEELCVR   1119   //Slamvan
#define CARMOD_SLAMVAN_SIDESKIRT_LCHROME     1120   //Slamvan
#define CARMOD_SLAMVAN_SIDESKIRT_LWHEELCVR   1121   //Slamvan

#define CARMOD_REMINGTON_SIDESKIRT_RCHROMEF  1122   //Remington
#define CARMOD_REMINGTON_BULLBAR_CHBARS      1123   //Remington
#define CARMOD_REMINGTON_SIDESKIRT_LCHROMEA  1124   //Remington
#define CARMOD_REMINGTON_BULLBAR_CHLIGHTS    1125   //Remington
#define CARMOD_REMINGTON_EXHAUST_CHROME      1126   //Remington
#define CARMOD_REMINGTON_EXHAUST_SLAMIN      1127   //Remington

#define CARMOD_BLADE_ROOF_VINYL              1128   //Blade

#define CARMOD_SAVANNA_EXHAUST_CHROME        1129   //Savanna
#define CARMOD_SAVANNA_ROOF_HARDTOP          1130   //Savanna
#define CARMOD_SAVANNA_ROOF_SOFTTOP          1131   //Savanna
#define CARMOD_SAVANNA_EXHAUST_SLAMIN        1132   //Savanna
#define CARMOD_SAVANNA_SIDESKIRT_RCHROME     1133   //Savanna

#define CARMOD_TORNADO_SIDESKIRT_RCHROME     1134   //Tornado
#define CARMOD_TORNADO_EXHAUST_SLAMIN        1135   //Tornado
#define CARMOD_TORNADO_EXHAUST_CHROME        1136   //Tornado
#define CARMOD_TORNADO_SIDESKIRT_LCHROME     1137   //Tornado

#define CARMOD_SULTAN_SPOILER_ALIEN          1138   //Sultan
#define CARMOD_SULTAN_SPOILER_XFLOW          1139   //Sultan
#define CARMOD_SULTAN_RBUMPER_XFLOW          1140   //Sultan
#define CARMOD_SULTAN_RBUMPER_ALIEN          1141   //Sultan

#define CARMOD_VENTS_LOVAL                   1142   //Certain Transfender Cars
#define CARMOD_VENTS_ROVAL                   1143   //Certain Transfender Cars
#define CARMOD_VENTS_LSQUARE                 1144   //Certain Transfender Cars
#define CARMOD_VENTS_RSQUARE                 1145   //Certain Transfender Cars

#define CARMOD_ELEGY_SPOILER_XFLOW           1146   //Elegy
#define CARMOD_ELEGY_SPOILER_ALIEN           1147   //Elegy
#define CARMOD_ELEGY_RBUMPER_XFLOW           1148   //Elegy
#define CARMOD_ELEGY_RBUMPER_ALIEN           1149   //Elegy

#define CARMOD_FLASH_RBUMPER_ALIEN           1150   //Flash
#define CARMOD_FLASH_RBUMPER_XFLOW           1151   //Flash
#define CARMOD_FLASH_FBUMPER_XFLOW           1152   //Flash
#define CARMOD_FLASH_FBUMPER_ALIEN           1153   //Flash

#define CARMOD_STRATUM_RBUMPER_ALIEN         1154   //Stratum
#define CARMOD_STRATUM_FBUMPER_ALIEN         1155   //Stratum
#define CARMOD_STRATUM_RBUMPER_XFLOW         1156   //Stratum
#define CARMOD_STRATUM_FBUMPER_XFLOW         1157   //Stratum

#define CARMOD_JESTER_SPOILER_XFLOW          1158   //Jester
#define CARMOD_JESTER_RBUMPER_ALIEN          1159   //Jester
#define CARMOD_JESTER_FBUMPER_ALIEN          1160   //Jester
#define CARMOD_JESTER_RBUMPER_XFLOW          1161   //Jester
#define CARMOD_JESTER_SPOILER_ALIEN          1162   //Jester

#define CARMOD_URANUS_SPOILER_XFLOW          1163   //Uranus
#define CARMOD_URANUS_SPOILER_ALIEN          1164   //Uranus
#define CARMOD_URANUS_FBUMPER_XFLOW          1165   //Uranus
#define CARMOD_URANUS_FBUMPER_ALIEN          1166   //Uranus
#define CARMOD_URANUS_RBUMPER_XFLOW          1167   //Uranus
#define CARMOD_URANUS_RBUMPER_ALIEN          1168   //Uranus

#define CARMOD_SULTAN_FBUMPER_ALIEN          1169   //Sultan
#define CARMOD_SULTAN_FBUMPER_XFLOW          1170   //Sultan

#define CARMOD_ELEGY_FBUMPER_ALIEN           1171   //Elegy
#define CARMOD_ELEGY_FBUMPER_XFLOW           1172   //Elegy

#define CARMOD_JESTER_FBUMPER_XFLOW          1173   //Jester

#define CARMOD_BROADWAY_FBUMPER_CHROME       1174   //Broadway
#define CARMOD_BROADWAY_FBUMPER_SLAMIN       1175   //Broadway
#define CARMOD_BROADWAY_RBUMPER_CHROME       1176   //Broadway
#define CARMOD_BROADWAY_RBUMPER_SLAMIN       1177   //Broadway

#define CARMOD_REMINGTON_RBUMPER_SLAMIN      1178   //Remington
#define CARMOD_REMINGTON_FBUMPER_CHROME      1179   //Remington
#define CARMOD_REMINGTON_RBUMPER_CHROME      1180   //Remington

#define CARMOD_BLADE_FBUMPER_SLAMIN          1181   //Blade
#define CARMOD_BLADE_FBUMPER_CHROME          1182   //Blade
#define CARMOD_BLADE_RBUMPER_SLAMIN          1183   //Blade
#define CARMOD_BLADE_RBUMPER_CHROME          1184   //Blade

#define CARMOD_REMINGTON_FBUMPER_SLAMIN      1185   //Remington

#define CARMOD_SAVANNA_RBUMPER_SLAMIN        1186   //Savanna
#define CARMOD_SAVANNA_RBUMPER_CHROME        1187   //Savanna
#define CARMOD_SAVANNA_FBUMPER_SLAMIN        1188   //Savanna
#define CARMOD_SAVANNA_FBUMPER_CHROME        1189   //Savanna

#define CARMOD_TORNADO_FBUMPER_SLAMIN        1190   //Tornado
#define CARMOD_TORNADO_FBUMPER_CHROME        1191   //Tornado
#define CARMOD_TORNADO_RBUMPER_CHROME        1192   //Tornado
#define CARMOD_TORNADO_RBUMPER_SLAMIN        1193   //Tornado
