/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define CRIME_10_71                3   //Advise nature of fire (size, type, contents of building)
#define CRIME_10_37_1              4   //Investigate suspicious vehicle
#define CRIME_10_81_1              5   //Breatherlizer Report
#define CRIME_10_24                6   //Assignment Completed
#define CRIME_10_21_1              7   //Call () by phone
#define CRIME_10_21_2              8   //Call () by phone
#define CRIME_10_21_3              9   //Call () by phone
#define CRIME_10_17                10  //Meet Complainant
#define CRIME_10_81_2              11  //Breatherlizer Report
#define CRIME_10_91_1              12  //Pick up prisoner/subject
#define CRIME_10_28_1              13  //Vehicle registration information
#define CRIME_10_81_3              14  //Breathalyzer
#define CRIME_10_28_2              15  //Vehicle registration information
#define CRIME_10_91_2              16  //Pick up prisoner/subject
#define CRIME_10_34                17  //Riot
#define CRIME_10_37_2              18  //Investigate suspicious vehicle
#define CRIME_10_81_4              19  //Breathalyzer
#define CRIME_10_7_1               21  //Out of service
#define CRIME_10_7_2               22  //Out of service
