/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define EXPLOSION_SMALL_1          0
#define EXPLOSION_MEDIUM           1
#define EXPLOSION_SMALL_2          2
#define EXPLOSION_SMALL_3          3
#define EXPLOSION_CHEMICAL_1       4
#define EXPLOSION_CHEMICAL_2       5
#define EXPLOSION_LARGE_1          6
#define EXPLOSION_LARGE_2          7
#define EXPLOSION_INVISIBLE_1      8
#define EXPLOSION_INVISIBLE_2      9
#define EXPLOSION_LARGE_3          10
#define EXPLOSION_SMALL_4          11
#define EXPLOSION_RCTIGER          12
#define EXPLOSION_INVISIBLE_3      13
