/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define EXPLOSION_SMALL_1          0    //Visible + Audible
#define EXPLOSION_MEDIUM           1    //Visible + Audible, No Physical Blast, Creates Fire
#define EXPLOSION_SMALL_2          2    //Visible + Audible, Creates Fire
#define EXPLOSION_SMALL_3          3    //Visible + Audible, Sometimes Creates Fire
#define EXPLOSION_CHEMICAL_1       4    //Visible, Silent
#define EXPLOSION_CHEMICAL_2       5    //Visible, Silent
#define EXPLOSION_LARGE_1          6    //Visible + Audible
#define EXPLOSION_LARGE_2          7    //Visible + Audible
#define EXPLOSION_INVISIBLE_1      8    //Audible
#define EXPLOSION_INVISIBLE_2      9    //Creates Fire + Audible
#define EXPLOSION_LARGE_3          10   //Visible + Audible
#define EXPLOSION_SMALL_4          11   //Visible + Audible
#define EXPLOSION_RCTIGER          12   //Visible + Audible
#define EXPLOSION_INVISIBLE_3      13   //No Physical Blast, Silent
