/*
 * SA-MP Includes Library+
 * 2018 - 2020, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define ICON_COLSQUARE             0
#define ICON_WHITESQUARE           1
#define ICON_PLAYERPOS             2
#define ICON_PLAYERMENUMAP         3
#define ICON_NORTH                 4
#define ICON_AIRYARD               5
#define ICON_AMMUNATION            6
#define ICON_BARBER                7
#define ICON_BIGSMOKE              8
#define ICON_BOATYARD              9
#define ICON_BURGERSHOT            10
#define ICON_QUARRY                11
#define ICON_CATALINA              12
#define ICON_CESAR                 13
#define ICON_CLUCKINBELL           14
#define ICON_CJ                    15
#define ICON_CRASH                 16
#define ICON_DINER                 17
#define ICON_EMMET                 18
#define ICON_ENEMYATTACK           19
#define ICON_FIRE                  20
#define ICON_GIRLFRIEND            21
#define ICON_HOSPITAL              22
#define ICON_LOCO                  23
#define ICON_MADDDOGG              24
#define ICON_CALIGULAS             25
#define ICON_OGLOC0                26
#define ICON_MODGARAGE             27
#define ICON_OGLOC                 28
#define ICON_PIZZA                 29
#define ICON_POLICE                30
#define ICON_PROPERTYGRN           31
#define ICON_PROPERTYRED           32
#define ICON_RACE                  33
#define ICON_RYDER                 34
#define ICON_SAVE                  35
#define ICON_SCHOOL                36
#define ICON_UNKNOWN               37
#define ICON_SWEET                 38
#define ICON_TATTOO                39
#define ICON_TRUTH                 40
#define ICON_WAYPOINT              41
#define ICON_TORENO                42
#define ICON_TRIADS                43
#define ICON_TRIADSCASINO          44
#define ICON_CLOTHES               45
#define ICON_WOOZIE                46
#define ICON_ZERO                  47
#define ICON_CLUB                  48
#define ICON_BAR                   49
#define ICON_RESTAURANT            50
#define ICON_TRUCK                 51
#define ICON_ROBBERY               52
#define ICON_RACEFLAG              53
#define ICON_GYM                   54
#define ICON_CAR                   55
#define ICON_LIGHT                 56
#define ICON_CLOSESTAIRPORT        57
#define ICON_AZTECAS               58
#define ICON_BALLAS                59
#define ICON_VAGOS                 60
#define ICON_SFRIFA                61
#define ICON_OGF                   62
#define ICON_PAYNSPRAY             63
