/*
 * SA-MP Includes Library+
 * Copyright (c) 2018 Ivan Kmeto
 *
 * Licensed under the MIT License.
 * http://opensource.org/licenses/mit-license
*/

#define LOC_WAREHOUSE2             0
#define LOC_TRANSFENDER            1
#define LOC_WORLDOFCOQ             2
#define LOC_AMMUNATION2            3
#define LOC_SUBURBAN               4
#define LOC_DENISEBEDROOM          5
#define LOC_SFGARAGE               6
#define LOC_OVALSTADIUM            7
#define LOC_LIBERTYCITY            8
#define LOC_SWEETSHOUSE            9
#define LOC_CALIGULAS              10
#define LOC_WUZIMU                 11
#define LOC_JET                    12

new Float:locCoords[13][4] = {
{1412.15,-2.28,1000.92,114.66},
{621.45,-23.73,1000.92,15.68},
{445.6,-6.98,1000.73,172.21},
{285.84,-39.02,1001.52,0.75},
{204.12,-46.8,1001.8,357.58},
{245.23,304.76,999.15,273.44},
{-2041.23,178.4,28.85,156.22},
{-1402.66,106.39,1032.27,105.14},
{-741.85,493.0,1371.98,71.78},
{2527.02,-1679.21,1015.5,260.97},
{2233.94,1711.8,1011.63,184.39},
{-2158.67,642.09,1052.38,86.54},
{1.55,23.32,1199.59,359.91}
};

new locID[13][1] = {
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1},
{1}
};

new locName[13][] = {
"Warehouse 2",
"TransFender",
"World of Coq",
"Ammunation (v2)",
"Suburban",
"Denise's Bedroom",
"San Fierro Garage",
"Oval Stadium",
"Liberty City",
"Sweet's House",
"Caligulas Casino",
"Wu Zi Mu's",
"Jet"
};
