/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define OBJECT_GUN_DILDO1             321    //gun_dildo1.dff
#define OBJECT_GUN_DILDO2             322    //gun_dildo2.dff
#define OBJECT_GUN_VIBE1              323    //gun_vibe1.dff
#define OBJECT_GUN_VIBE2              324    //gun_vibe2.dff
#define OBJECT_FLOWERA                325    //flowera.dff
#define OBJECT_GUN_CANE               326    //gun_cane.dff
#define OBJECT_GUN_BOXWEE             327    //gun_boxwee.dff
#define OBJECT_GUN_BOXBIX             328    //gun_boxbig.dff
#define OBJECT_CELLPHONE              330    //cellphone.dff
#define OBJECT_BRASSKNUCKLE           331    //brassknuckle.dff
#define OBJECT_GOLFCLUB               333    //golfclub.dff
#define OBJECT_NITESTICK              334    //nitestick.dff
#define OBJECT_KNIFECUR               335    //knifecur.dff
#define OBJECT_BAT                    336    //bat.dff
#define OBJECT_SHOVEL                 337    //shovel.dff
#define OBJECT_POOLCUE                338    //poolcue.dff
#define OBJECT_KATANA                 339    //katana.dff
#define OBJECT_CHNSAW                 341    //chnsaw.dff
#define OBJECT_GRENADE                342    //grenade.dff
#define OBJECT_TEARGAS                343    //teargas.dff
#define OBJECT_MOLOTOV                344    //molotov.dff
#define OBJECT_MISSILE                345    //missile.dff
#define OBJECT_COLT45                 346    //colt45.dff
#define OBJECT_SILENCED               347    //silenced.dff
#define OBJECT_DESERT_EAGLE           348    //desert_eagle.dff
#define OBJECT_CHROMEGUN              349    //chromegun.dff
#define OBJECT_SAWNOFF                350    //sawnoff.dff
#define OBJECT_SHOTGSPA               351    //shotgspa.dff
#define OBJECT_MICRO_UZI              352    //micro_uzi.dff
#define OBJECT_MP5LNG                 353    //mp5lng.dff
#define OBJECT_FLARE                  354    //flare.dff
#define OBJECT_AK47                   355    //ak47.dff
#define OBJECT_M4                     356    //m4.dff
#define OBJECT_CUNTGUN                357    //cuntgun.dff
#define OBJECT_SNIPER                 358    //sniper.dff
#define OBJECT_ROCKETLA               359    //rocketla.dff
#define OBJECT_HEATSEEK               360    //heatseek.dff
#define OBJECT_FLAME                  361    //flame.dff
#define OBJECT_MINIGUN                362    //minigun.dff
#define OBJECT_SATCHEL                363    //satchel.dff
#define OBJECT_BOMB                   364    //bomb.dff
#define OBJECT_SPRAYCAN               365    //spraycan.dff
#define OBJECT_FIRE_EX                366    //fire_ex.dff
#define OBJECT_CAMERA                 367    //camera.dff
#define OBJECT_NVGOGGLES              368    //nvgoggles.dff
#define OBJECT_IRGOGGLES              369    //irgoggles.dff
#define OBJECT_JETPACK                370    //jetpack.dff
#define OBJECT_GUN_PARA               371    //gun_para.dff
#define OBJECT_TEC9                   372    //tec9.dff
#define OBJECT_ARMOUR                 373    //armour.dff
#define OBJECT_VEG_TREE3              615    //veg_tree3.dff
#define OBJECT_VEG_TREEA1             616    //veg_treea1.dff
#define OBJECT_VEG_TREEB1             617    //veg_treeb1.dff
#define OBJECT_VEG_TREEA3             618    //veg_treea3.dff
#define OBJECT_VEG_PALWEE03           619    //veg_palwee03.dff
#define OBJECT_VEG_PALM04             620    //veg_palm04.dff
#define OBJECT_VEG_PALM02             621    //veg_palm02.dff
#define OBJECT_VEG_PALM03             622    //veg_palm03.dff
#define OBJECT_VEG_PALWEE01           623    //veg_palwee01.dff
#define OBJECT_VEG_PALWEE02           624    //veg_palwee02.dff
#define OBJECT_VEG_PALMKB1            625    //veg_palmkb1.dff
#define OBJECT_VEG_PALMKB2            626    //veg_palmkb2.dff
#define OBJECT_VEG_PALMKB3            627    //veg_palmkb3.dff
#define OBJECT_VEG_PALMKB4            628    //veg_palmkb4.dff
#define OBJECT_VEG_PALMKB5            629    //veg_palmkb5.dff
#define OBJECT_VEG_PALMKB8            630    //veg_palmkb8.dff
#define OBJECT_VEG_PALMKB9            631    //veg_palmkb9.dff
#define OBJECT_VEG_PALMKB7            632    //veg_palmkb7.dff
#define OBJECT_VEG_PALMKB10           633    //veg_palmkb10.dff
#define OBJECT_VEG_PALMKBB11          634    //veg_palmkbb11.dff
#define OBJECT_VEG_FERN_BALCNY_KB1    635    //veg_fern_balcny_kb1.dff
#define OBJECT_VEG_FERN_BALCNY_KB2    636    //veg_fern_balcny_kb2.dff
#define OBJECT_KB_PLANTERBOX          637    //kb_planterbox.dff
#define OBJECT_KB_PLANTERBUSH         638    //kb_planter+bush.dff
#define OBJECT_VEG_IVY_BALCNY_KB3     639    //veg_ivy_balcny_kb3.dff
#define OBJECT_KB_PLANTERBUSH2        640    //kb_planter+bush2.dff
#define OBJECT_VEG_PALMKB13           641    //veg_palmkb13.dff
#define OBJECT_KB_CANOPY_TEST         642    //kb_canopy_test.dff
#define OBJECT_KB_CHR_TBL_TEST        643    //kb_chr_tbl_test.dff
#define OBJECT_POT_02                 644    //pot_02.dff
#define OBJECT_VEG_PALMBIG14          645    //veg_palmbig14.dff
#define OBJECT_VEG_PALMKB14           646    //veg_palmkb14.dff
#define OBJECT_NEW_BUSHSM             647    //new_bushsm.dff
#define OBJECT_VEG_PALM01             648    //veg_palm01.dff
#define OBJECT_SJMPALM                649    //sjmpalm.dff
#define OBJECT_SJMCACTI2              650    //sjmcacti2.dff
#define OBJECT_SJMCACTI1              651    //sjmcacti1.dff
#define OBJECT_SJMPALMBIG             652    //sjmpalmbig.dff
