/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define OBJECT_GUN_DILDO1             321    //gun_dildo1.dff
#define OBJECT_GUN_DILDO2             322    //gun_dildo2.dff
#define OBJECT_GUN_VIBE1              323    //gun_vibe1.dff
#define OBJECT_GUN_VIBE2              324    //gun_vibe2.dff
#define OBJECT_FLOWERA                325    //flowera.dff
#define OBJECT_GUN_CANE               326    //gun_cane.dff
#define OBJECT_GUN_BOXWEE             327    //gun_boxwee.dff
#define OBJECT_GUN_BOXBIX             328    //gun_boxbig.dff
#define OBJECT_CELLPHONE              330    //cellphone.dff
#define OBJECT_BRASSKNUCKLE           331    //brassknuckle.dff
#define OBJECT_GOLFCLUB               333    //golfclub.dff
#define OBJECT_NITESTICK              334    //nitestick.dff
#define OBJECT_KNIFECUR               335    //knifecur.dff
#define OBJECT_BAT                    336    //bat.dff
#define OBJECT_SHOVEL                 337    //shovel.dff
#define OBJECT_POOLCUE                338    //poolcue.dff
#define OBJECT_KATANA                 339    //katana.dff
#define OBJECT_CHNSAW                 341    //chnsaw.dff
#define OBJECT_GRENADE                342    //grenade.dff
#define OBJECT_TEARGAS                343    //teargas.dff
#define OBJECT_MOLOTOV                344    //molotov.dff
#define OBJECT_MISSILE                345    //missile.dff
#define OBJECT_COLT45                 346    //colt45.dff
#define OBJECT_SILENCED               347    //silenced.dff
#define OBJECT_DESERT_EAGLE           348    //desert_eagle.dff
#define OBJECT_CHROMEGUN              349    //chromegun.dff
#define OBJECT_SAWNOFF                350    //sawnoff.dff
#define OBJECT_SHOTGSPA               351    //shotgspa.dff
#define OBJECT_MICRO_UZI              352    //micro_uzi.dff
#define OBJECT_MP5LNG                 353    //mp5lng.dff
#define OBJECT_FLARE                  354    //flare.dff
#define OBJECT_AK47                   355    //ak47.dff
#define OBJECT_M4                     356    //m4.dff
#define OBJECT_CUNTGUN                357    //cuntgun.dff
#define OBJECT_SNIPER                 358    //sniper.dff
#define OBJECT_ROCKETLA               359    //rocketla.dff
#define OBJECT_HEATSEEK               360    //heatseek.dff
#define OBJECT_FLAME                  361    //flame.dff
#define OBJECT_MINIGUN                362    //minigun.dff
#define OBJECT_SATCHEL                363    //satchel.dff
#define OBJECT_BOMB                   364    //bomb.dff
#define OBJECT_SPRAYCAN               365    //spraycan.dff
#define OBJECT_FIRE_EX                366    //fire_ex.dff
#define OBJECT_CAMERA                 367    //camera.dff
#define OBJECT_NVGOGGLES              368    //nvgoggles.dff
#define OBJECT_IRGOGGLES              369    //irgoggles.dff
#define OBJECT_JETPACK                370    //jetpack.dff
#define OBJECT_GUN_PARA               371    //gun_para.dff
#define OBJECT_TEC9                   372    //tec9.dff
#define OBJECT_ARMOUR                 373    //armour.dff
#define OBJECT_VEG_TREE3              615    //veg_tree3.dff
#define OBJECT_VEG_TREEA1             616    //veg_treea1.dff
#define OBJECT_VEG_TREEB1             617    //veg_treeb1.dff
#define OBJECT_VEG_TREEA3             618    //veg_treea3.dff
#define OBJECT_VEG_PALWEE03           619    //veg_palwee03.dff
#define OBJECT_VEG_PALM04             620    //veg_palm04.dff
#define OBJECT_VEG_PALM02             621    //veg_palm02.dff
#define OBJECT_VEG_PALM03             622    //veg_palm03.dff
#define OBJECT_VEG_PALWEE01           623    //veg_palwee01.dff
#define OBJECT_VEG_PALWEE02           624    //veg_palwee02.dff
#define OBJECT_VEG_PALMKB1            625    //veg_palmkb1.dff
#define OBJECT_VEG_PALMKB2            626    //veg_palmkb2.dff
#define OBJECT_VEG_PALMKB3            627    //veg_palmkb3.dff
#define OBJECT_VEG_PALMKB4            628    //veg_palmkb4.dff
#define OBJECT_VEG_PALMKB5            629    //veg_palmkb5.dff
#define OBJECT_VEG_PALMKB8            630    //veg_palmkb8.dff
#define OBJECT_VEG_PALMKB9            631    //veg_palmkb9.dff
#define OBJECT_VEG_PALMKB7            632    //veg_palmkb7.dff
#define OBJECT_VEG_PALMKB10           633    //veg_palmkb10.dff
#define OBJECT_VEG_PALMKBB11          634    //veg_palmkbb11.dff
#define OBJECT_VEG_FERN_BALCNY_KB1    635    //veg_fern_balcny_kb1.dff
#define OBJECT_VEG_FERN_BALCNY_KB2    636    //veg_fern_balcny_kb2.dff
#define OBJECT_KB_PLANTERBOX          637    //kb_planterbox.dff
#define OBJECT_KB_PLANTERBUSH         638    //kb_planter+bush.dff
#define OBJECT_VEG_IVY_BALCNY_KB3     639    //veg_ivy_balcny_kb3.dff
#define OBJECT_KB_PLANTERBUSH2        640    //kb_planter+bush2.dff
#define OBJECT_VEG_PALMKB13           641    //veg_palmkb13.dff
#define OBJECT_KB_CANOPY_TEST         642    //kb_canopy_test.dff
#define OBJECT_KB_CHR_TBL_TEST        643    //kb_chr_tbl_test.dff
#define OBJECT_POT_02                 644    //pot_02.dff
#define OBJECT_VEG_PALMBIG14          645    //veg_palmbig14.dff
#define OBJECT_VEG_PALMKB14           646    //veg_palmkb14.dff
#define OBJECT_NEW_BUSHSM             647    //new_bushsm.dff
#define OBJECT_VEG_PALM01             648    //veg_palm01.dff
#define OBJECT_SJMPALM                649    //sjmpalm.dff
#define OBJECT_SJMCACTI2              650    //sjmcacti2.dff
#define OBJECT_SJMCACTI1              651    //sjmcacti1.dff
#define OBJECT_SJMPALMBIG             652    //sjmpalmbig.dff
#define OBJECT_SJMCACTI03             653    //sjmcacti03.dff
#define OBJECT_PINETREE08             654    //pinetree08.dff
#define OBJECT_PINETREE06             655    //pinetree06.dff
#define OBJECT_PINETREE05             656    //pinetree05.dff
#define OBJECT_PINETREE02             657    //pinetree02.dff
#define OBJECT_PINETREE04             658    //pinetree04.dff
#define OBJECT_PINETREE01             659    //pinetree01.dff
#define OBJECT_PINETREE03             660    //pinetree03.dff
#define OBJECT_PINETREE07             661    //pinetree07.dff
#define OBJECT_FIRTREE2               664    //firtree2.dff
#define OBJECT_SM_VEG_TREE4           669    //sm_veg_tree4.dff
#define OBJECT_SM_FIRTALLDED          670    //sm_firtallded.dff
#define OBJECT_SM_BUSHYTREE           671    //sm_bushytree.dff
#define OBJECT_SM_VEG_TREE5           672    //sm_veg_tree5.dff
#define OBJECT_SM_BEVHILTREE          673    //sm_bevhiltree.dff
#define OBJECT_SM_DES_JOSH_LRG1       674    //sm_des_josh_lrg1.dff
#define OBJECT_JOSH_BALL              675    //josh_ball.dff
#define OBJECT_SM_DES_JOSH_SML1       676    //sm_des_josh_sml1.dff
#define OBJECT_SM_DES_AGAVE1          677    //sm_des_agave1.dff
#define OBJECT_SM_DES_AGAVE2          678    //sm_des_agave2.dff
#define OBJECT_SM_DES_CACT_BSH        679    //sm_des_cact_bsh.dff
#define OBJECT_SM_DES_JOSH_LRG2       680    //sm_des_josh_lrg2.dff
#define OBJECT_SM_DES_JOSH_SM2        681    //sm_des_josh_sm2.dff
#define OBJECT_SM_DES_CACTFLR         682    //sm_des_cactflr.dff
#define OBJECT_SM_FIR_GROUP           683    //sm_fir_group.dff
#define OBJECT_SM_FIR_LOG02           684    //sm_fir_log02.dff
#define OBJECT_SM_FIR_SCABBY          685    //sm_fir_scabby.dff
#define OBJECT_SM_FIR_DEAD            686    //sm_fir_dead.dff
#define OBJECT_SM_FIR                 687    //sm_fir_.dff
#define OBJECT_SM_FIR_SCABG           688    //sm_fir_scabg.dff
#define OBJECT_SM_FIR_COPSE1          689    //sm_fir_copse1.dff
#define OBJECT_SM_FIR_COPSE2          690    //sm_fir_copse2.dff
#define OBJECT_SM_VEG_TREE4_BIG       691    //sm_veg_tree4_big.dff
#define OBJECT_SM_DES_BUSH1           692    //sm_des_bush1.dff
#define OBJECT_SM_REDWOOD             693    //sm_redwood_.dff
#define OBJECT_SM_REDWOODGRP          694    //sm_redwoodgrp.dff
#define OBJECT_SM_FIR_SCABTG          695    //sm_fir_scabtg.dff
#define OBJECT_SM_FIR_SCABT           696    //sm_fir_scabt.dff
#define OBJECT_SM_FIR_TALL            697    //sm_fir_tall.dff
#define OBJECT_SM_FIRTBSHG            698    //sm_firtbshg.dff
#define OBJECT_SM_VEG_TREE6           700    //sm_veg_tree6.dff
#define OBJECT_SM_TUMBLEWD48P         701    //sm_tumblewd48p.dff
#define OBJECT_SM_TUMBLEWEED          702    //sm_tumbleweed.dff
#define OBJECT_SM_VEG_TREE7_BIG       703    //sm_veg_tree7_big.dff
#define OBJECT_BG_FIR_DEAD            704    //bg_fir_dead.dff
#define OBJECT_SM_VEG_TREE7VBIG       705    //sm_veg_tree7vbig.dff
#define OBJECT_SM_VEGVBBIG            706    //sm_vegvbbig.dff
#define OBJECT_SM_BUSHVBIG            707    //sm_bushvbig.dff
#define OBJECT_SM_VEG_TREE4_VBIG      708    //sm_veg_tree4_vbig.dff
#define OBJECT_SM_VEGVBBIGBRN         709    //sm_vegvbbigbrn.dff
#define OBJECT_VGS_PALM01             710    //vgs_palm01.dff
#define OBJECT_VGS_PALM02             711    //vgs_palm02.dff
#define OBJECT_VGS_PALM03             712    //vgs_palm03.dff
#define OBJECT_VEG_BEVTREE1           713    //veg_bevtree1.dff
#define OBJECT_VEG_BEVTREE2           714    //veg_bevtree2.dff
#define OBJECT_VEG_BEVTREE3           715    //veg_bevtree3.dff
#define OBJECT_SJMPALMBIGPV           716     //vegepart.ide, sjmpalmbigpv.dff
#define OBJECT_SM_BEVHILTREEPV        717     //vegepart.ide, sm_bevhiltreepv.dff
#define OBJECT_VGS_PALM04             718     //vegepart.ide, vgs_palm04.dff
#define OBJECT_VEG_LARGEFURS07        719     //vegepart.ide, veg_largefurs07.dff
#define OBJECT_VEG_LARGEFURS01        720     //vegepart.ide, veg_largefurs01.dff
#define OBJECT_VEG_LARGEFURS02        721     //vegepart.ide, veg_largefurs02.dff
#define OBJECT_VEG_LARGEFURS03        722     //vegepart.ide, veg_largefurs03.dff
#define OBJECT_VEG_LARGEFURS04        723     //vegepart.ide, veg_largefurs04.dff
#define OBJECT_VEG_LARGEFURS05        724     //vegepart.ide, veg_largefurs05.dff
#define OBJECT_VEG_LARGEFURS06        725     //vegepart.ide, veg_largefurs06.dff
#define OBJECT_TREE_HIPOLY19          726     //vegepart.ide, tree_hipoly19.dff
#define OBJECT_TREE_HIPOLY04          727     //vegepart.ide, tree_hipoly04.dff
#define OBJECT_TREE_HIPOLY06          728     //vegepart.ide, tree_hipoly06.dff
#define OBJECT_TREE_HIPOLY07          729     //vegepart.ide, tree_hipoly07.dff
#define OBJECT_TREE_HIPOLY08          730     //vegepart.ide, tree_hipoly08.dff
#define OBJECT_TREE_HIPOLY09          731     //vegepart.ide, tree_hipoly09.dff
#define OBJECT_TREE_HIPOLY10          732     //vegepart.ide, tree_hipoly10.dff
#define OBJECT_TREE_HIPOLY11          733     //vegepart.ide, tree_hipoly11.dff
#define OBJECT_TREE_HIPOLY14          734     //vegepart.ide, tree_hipoly14.dff
#define OBJECT_TREE_HIPOLY09B         735     //vegepart.ide, tree_hipoly09b.dff
#define OBJECT_CEASERTREE01_LVS       736     //vegepart.ide, ceasertree01_lvs.dff
#define OBJECT_AW_STREETTREE3         737     //vegepart.ide, aw_streettree3.dff
#define OBJECT_AW_STREETTREE2         738     //vegepart.ide, aw_streettree2.dff
#define OBJECT_SJMPALMTALL            739     //vegepart.ide, sjmpalmtall.dff
#define OBJECT_VGS_PALMVTALL          740     //vegepart.ide, vgs_palmvtall.dff
#define OBJECT_POT_01                 741     //vegepart.ide, pot_01.dff
#define OBJECT_POT_03                 742     //vegepart.ide, pot_03.dff
#define OBJECT_KB_POT_1               743     //vegepart.ide, kb_pot_1.dff
#define OBJECT_SM_SCRUB_ROCK4         744     //vegepart.ide, sm_scrub_rock4.dff
#define OBJECT_SM_SCRUB_ROCK5         745     //vegepart.ide, sm_scrub_rock5.dff
#define OBJECT_SM_SCRUB_ROCK2         746     //vegepart.ide, sm_scrub_rock2.dff
#define OBJECT_SM_SCRUB_ROCK3         747     //vegepart.ide, sm_scrub_rock3.dff
#define OBJECT_SM_SCRB_GRP1           748     //vegepart.ide, sm_scrb_grp1.dff
#define OBJECT_SM_SCRB_COLUMN3        749     //vegepart.ide, sm_scrb_column3.dff
#define OBJECT_SM_SCRB_COLUMN2        750     //vegepart.ide, sm_scrb_column2.dff
#define OBJECT_SM_SCRB_COLUMN1        751     //vegepart.ide, sm_scrb_column1.dff
#define OBJECT_SM_CUNT_ROCK1          752     //vegepart.ide, sm_cunt_rock1.dff
#define OBJECT_SM_DESCACTIIGRPB       753     //vegepart.ide, sm_descactiigrpb.dff
#define OBJECT_SM_DES_CACTIIGRP       754     //vegepart.ide, sm_des_cactiigrp.dff
#define OBJECT_SM_DES_PCKLYPR3        755     //vegepart.ide, sm_des_pcklypr3.dff
#define OBJECT_SM_DES_PCKLYPR2        756     //vegepart.ide, sm_des_pcklypr2.dff
#define OBJECT_SM_DES_PCKLYPR1        757     //vegepart.ide, sm_des_pcklypr1.dff
#define OBJECT_SM_SCRUB_ROCK6         758     //vegepart.ide, sm_scrub_rock6.dff
#define OBJECT_SM_BUSH_LARGE_1        759     //vegepart.ide, sm_bush_large_1.dff
#define OBJECT_SM_BUSH_SMALL_1        760     //vegepart.ide, sm_bush_small_1.dff
#define OBJECT_SM_DRYBRUSH_SM1        761     //vegepart.ide, sm_drybrush_sm1.dff
#define OBJECT_NEW_BUSHTEST           762     //vegepart.ide, new_bushtest.dff
#define OBJECT_ASH1_HI                763     //vegepart.ide, Ash1_hi.dff
#define OBJECT_CEDAR3_HI              764     //vegepart.ide, Cedar3_hi.dff
#define OBJECT_CEDAR2_HI              765     //vegepart.ide, Cedar2_hi.dff
#define OBJECT_CEDAR1_HI              766     //vegepart.ide, Cedar1_hi.dff
#define OBJECT_ELMTREEGRN_HI          767     //vegepart.ide, Elmtreegrn_hi.dff
#define OBJECT_ELMTREEGRN2_HI         768     //vegepart.ide, Elmtreegrn2_hi.dff
#define OBJECT_LOCUST_HI              769     //vegepart.ide, Locust_hi.dff
#define OBJECT_PINEBG_HI              770     //vegepart.ide, Pinebg_hi.dff
#define OBJECT_SPRUCETREE_HI          771     //vegepart.ide, sprucetree_hi.dff
#define OBJECT_ELMRED_HI              772     //vegepart.ide, Elmred_hi.dff
#define OBJECT_ELMDEAD_HI             773     //vegepart.ide, Elmdead_hi.dff
#define OBJECT_ELMPARSE_HI            774     //vegepart.ide, Elmsparse_hi.dff
#define OBJECT_ELMWEE_HI              775     //vegepart.ide, Elmwee_hi.dff
#define OBJECT_HAZELWEETREE_HI        776     //vegepart.ide, Hazelweetree_hi.dff
#define OBJECT_HAZELTALL_HI           777     //vegepart.ide, Hazeltall_hi.dff
#define OBJECT_ELMRED_HISM            778     //vegepart.ide, Elmred_hism.dff
#define OBJECT_PINEBG_HISM            779     //vegepart.ide, Pinebg_hism.dff
#define OBJECT_ELMSPARSE_HISM         780     //vegepart.ide, Elmsparse_hism.dff
#define OBJECT_ELMWEE_HISM            781     //vegepart.ide, Elmwee_hism.dff
#define OBJECT_ELMTREEGRN_HISM        782     //vegepart.ide, Elmtreegrn_hism.dff
#define OBJECT_HASHBURYTREE4SFS       789     //vegepart.ide, hashburytree4sfs.dff
#define OBJECT_SM_FIR_TALLGROUP       790     //vegepart.ide, sm_fir_tallgroup.dff
#define OBJECT_VBG_FIR_COPSE          791     //vegepart.ide, vbg_fir_copse.dff
#define OBJECT_AW_STREETTREE1         792     //vegepart.ide, aw_streettree1.dff
#define OBJECT_GENVEG_BUSH07          800     //procobj.ide, genVEG_bush07.dff
#define OBJECT_GENVEG_BUSH01          801     //procobj.ide, genVEG_bush01.dff
#define OBJECT_GENVEG_BUSH08          802     //procobj.ide, genVEG_bush08.dff
#define OBJECT_GENVEG_BUSH09          803     //procobj.ide, genVEG_bush09.dff
#define OBJECT_GENVEG_BUSH10          804     //procobj.ide, genVEG_bush10.dff
#define OBJECT_GENVEG_BUSH11          805     //procobj.ide, genVEG_bush11.dff
#define OBJECT_GENVEG_TALLGRASS       806     //procobj.ide, genVEG_tallgrass.dff
#define OBJECT_P_RUBBLE               807     //procobj.ide, p_rubble.dff
#define OBJECT_GENVEG_BUSH12          808     //procobj.ide, genVEG_bush12.dff
#define OBJECT_GENVEG_BUSH13          809     //procobj.ide, genVEG_bush13.dff
#define OBJECT_GENVEG_BUSH14          810     //procobj.ide, genVEG_bush14.dff
#define OBJECT_GENVEG_BUSH15          811     //procobj.ide, genVEG_bush15.dff
#define OBJECT_GENVEG_BUSH16          812     //procobj.ide, genVEG_bush16.dff
#define OBJECT_GENVEG_BUSH17          813     //procobj.ide, genVEG_bush17.dff
#define OBJECT_GENVEG_BUSH18          814     //procobj.ide, genVEG_bush18.dff
#define OBJECT_GENVEG_BUSH19          815     //procobj.ide, genVEG_bush19.dff
#define OBJECT_P_RUBBLE03             816     //procobj.ide, p_rubble03.dff
#define OBJECT_VEG_PFLOWERS01         817     //procobj.ide, veg_Pflowers01.dff
#define OBJECT_GENVEG_TALLGRASS02     818     //procobj.ide, genVEG_tallgrass02.dff
#define OBJECT_GENVEG_TALLGRASS03     819     //procobj.ide, genVEG_tallgrass03.dff
#define OBJECT_GENVEG_TALLGRASS04     820     //procobj.ide, genVEG_tallgrass04.dff
#define OBJECT_GENVEG_TALLGRASS05     821     //procobj.ide, genVEG_tallgrass05.dff
#define OBJECT_GENVEG_TALLGRASS06     822     //procobj.ide, genVEG_tallgrass06.dff
#define OBJECT_GENVEG_TALLGRASS07     823     //procobj.ide, genVEG_tallgrass07.dff
#define OBJECT_GENVEG_TALLGRASS08     824     //procobj.ide, genVEG_tallgrass08.dff
#define OBJECT_GENVEG_BUSHY           825     //procobj.ide, genVEG_bushy.dff
#define OBJECT_GENVEG_TALLGRASS10     826     //procobj.ide, genVEG_tallgrass10.dff
#define OBJECT_GENVEG_TALLGRASS11     827     //procobj.ide, genVEG_tallgrass11.dff
#define OBJECT_P_RUBBLE2              828     //procobj.ide, p_rubble2.dff
#define OBJECT_DEAD_TREE_3            829     //procobj.ide, DEAD_TREE_3.dff
#define OBJECT_DEAD_TREE_2            830     //procobj.ide, DEAD_TREE_2.dff
#define OBJECT_DEAD_TREE_5            831     //procobj.ide, DEAD_TREE_5.dff
#define OBJECT_DEAD_TREE_4            832     //procobj.ide, DEAD_TREE_4.dff
#define OBJECT_DEAD_TREE_6            833     //procobj.ide, DEAD_TREE_6.dff
#define OBJECT_DEAD_TREE_7            834     //procobj.ide, DEAD_TREE_7.dff
#define OBJECT_DEAD_TREE_8            835     //procobj.ide, DEAD_TREE_8.dff
#define OBJECT_DEAD_TREE_10           836     //procobj.ide, DEAD_TREE_10.dff
#define OBJECT_DEAD_TREE_1            837     //procobj.ide, DEAD_TREE_1.dff
#define OBJECT_DEAD_TREE_9            838     //procobj.ide, DEAD_TREE_9.dff
#define OBJECT_DEAD_TREE_11           839     //procobj.ide, DEAD_TREE_11.dff
#define OBJECT_DEAD_TREE_12           840     //procobj.ide, DEAD_TREE_12.dff
#define OBJECT_DEAD_TREE_13           841     //procobj.ide, DEAD_TREE_13.dff
#define OBJECT_DEAD_TREE_14           842     //procobj.ide, DEAD_TREE_14.dff
#define OBJECT_DEAD_TREE_15           843     //procobj.ide, DEAD_TREE_15.dff
#define OBJECT_DEAD_TREE_16           844     //procobj.ide, DEAD_TREE_16.dff
#define OBJECT_DEAD_TREE_17           845     //procobj.ide, DEAD_TREE_17.dff
#define OBJECT_DEAD_TREE_18           846     //procobj.ide, DEAD_TREE_18.dff
#define OBJECT_DEAD_TREE_19           847     //procobj.ide, DEAD_TREE_19.dff
#define OBJECT_DEAD_TREE_20           848     //procobj.ide, DEAD_TREE_20.dff
#define OBJECT_CJ_URB_RUB_3           849     //procobj.ide, CJ_urb_rub_3.dff
#define OBJECT_CJ_URB_RUB_1           850     //procobj.ide, CJ_urb_rub_1.dff
#define OBJECT_CJ_URB_RUB_2           851     //procobj.ide, CJ_urb_rub_2.dff
#define OBJECT_CJ_URB_RUB_4           852     //procobj.ide, CJ_urb_rub_4.dff
#define OBJECT_CJ_URB_RUB_5           853     //procobj.ide, CJ_urb_rub_5.dff
#define OBJECT_CJ_URB_RUB_3B          854     //procobj.ide, CJ_urb_rub_3b.dff
#define OBJECT_GENVEG_TALLGRASS01     855     //procobj.ide, genVEG_tallgrass01.dff
#define OBJECT_GENVEG_TALLGRASS12     856     //procobj.ide, genVEG_tallgrass12.dff
#define OBJECT_PROCWEEGRS             857     //procobj.ide, procweegrs.dff
#define OBJECT_SAND_JOSH2             858     //procobj.ide, sand_josh2.dff
#define OBJECT_SAND_PLANT04           859     //procobj.ide, sand_plant04.dff
#define OBJECT_SAND_PLANT01           860     //procobj.ide, sand_plant01.dff
#define OBJECT_SAND_PLANT02           861     //procobj.ide, sand_plant02.dff
#define OBJECT_SAND_PLANT05           862     //procobj.ide, sand_plant05.dff
#define OBJECT_SAND_PLANT03           863     //procobj.ide, sand_plant03.dff
#define OBJECT_SAND_COMBUSH1          864     //procobj.ide, sand_combush1.dff
#define OBJECT_SAND_COMBUSH02         865     //procobj.ide, sand_combush02.dff
#define OBJECT_SAND_COMBUSH03         866     //procobj.ide, sand_combush03.dff
#define OBJECT_P_RUBBLE04COL          867     //procobj.ide, p_rubble04col.dff
#define OBJECT_P_RUBBLE05COL          868     //procobj.ide, p_rubble05col.dff
#define OBJECT_VEG_PFLOWERSWEE        869     //procobj.ide, veg_Pflowerswee.dff
#define OBJECT_VEG_PFLOWERS2WEE       870     //procobj.ide, veg_Pflowers2wee.dff
#define OBJECT_VEG_PROCFPATCHWEE      871     //procobj.ide, veg_procfpatchwee.dff
#define OBJECT_GEN_TALLGRSNEW         872     //procobj.ide, gen_tallgrsnew.dff
#define OBJECT_VEG_PROCFPATCH         873     //procobj.ide, veg_procfpatch.dff
#define OBJECT_VEG_PROCGRASSPATCH     874     //procobj.ide, veg_procgrasspatch.dff
#define OBJECT_VEG_PROCFPATCH01       875     //procobj.ide, veg_procfpatch01.dff
#define OBJECT_VEG_PFLOWERS03         876     //procobj.ide, veg_Pflowers03.dff
#define OBJECT_VEG_PFLOWERS04         877     //procobj.ide, veg_Pflowers04.dff
#define OBJECT_VEG_PFLOWERS02         878     //procobj.ide, veg_Pflowers02.dff
#define OBJECT_P_RUBBLE04BCOL         879     //procobj.ide, p_rubble04bcol.dff
#define OBJECT_P_RUBBLE0BCOL          880     //procobj.ide, p_rubble0bcol.dff
#define OBJECT_SM_FIR_SCABG_PO        881     //procobj.ide, sm_fir_scabg_PO.dff
#define OBJECT_ASH_PO                 882     //procobj.ide, Ash_PO.dff
#define OBJECT_CEDAR3_PO              883     //procobj.ide, Cedar3_PO.dff
#define OBJECT_CEDAR2_PO              884     //procobj.ide, Cedar2_PO.dff
#define OBJECT_CEDAR1_PO              885     //procobj.ide, Cedar1_PO.dff
#define OBJECT_ELMTREEGRN_PO          886     //procobj.ide, Elmtreegrn_PO.dff
#define OBJECT_ELMTREEGRN2_PO         887     //procobj.ide, Elmtreegrn2_PO.dff
#define OBJECT_LOCUST_PO              888     //procobj.ide, Locust_PO.dff
#define OBJECT_PINEBG_PO              889     //procobj.ide, Pinebg_PO.dff
#define OBJECT_ELMRED_PO              890     //procobj.ide, Elmred_PO.dff
#define OBJECT_ELMDEAD_PO             891     //procobj.ide, Elmdead_PO.dff
#define OBJECT_HAZELWEETREE_PO        892     //procobj.ide, Hazelweetree_PO.dff
#define OBJECT_ELMREDSM_PO            893     //procobj.ide, Elmredsm_PO.dff
#define OBJECT_ELMSPARSESM_PO         894     //procobj.ide, Elmsparsesm_PO.dff
#define OBJECT_ELMWEESM_PO            895     //procobj.ide, Elmweesm_PO.dff
#define OBJECT_SEAROCK06              896     //procobj.ide, searock06.dff
#define OBJECT_SEAROCK01              897     //procobj.ide, searock01.dff
#define OBJECT_SEAROCK02              898     //procobj.ide, searock02.dff
#define OBJECT_SEAROCK03              899     //procobj.ide, searock03.dff
#define OBJECT_SEAROCK04              900     //procobj.ide, searock04.dff
#define OBJECT_SEAROCK05              901     //procobj.ide, searock05.dff
#define OBJECT_STARFISH               902     //procobj.ide, Starfish.dff
#define OBJECT_SEAWEED                903     //procobj.ide, seaweed.dff
#define OBJECT_SAND_JOSH1             904     //procobj.ide, sand_josh1.dff
#define OBJECT_ROCKBRKQ               905     //procobj.ide, rockbrkq.dff
#define OBJECT_P_RUBBLEBIG            906     //procobj.ide, p_rubblebig.dff
#define OBJECT_BUST_CABINET_4         910     //propext.ide, BUST_CABINET_4.dff
#define OBJECT_BUST_CABINET_1         911     //propext.ide, BUST_CABINET_1.dff
#define OBJECT_BUST_CABINET_2         912     //propext.ide, BUST_CABINET_2.dff
#define OBJECT_BUST_CABINET_3         913     //propext.ide, BUST_CABINET_3.dff
#define OBJECT_GRILL                  914     //propext.ide, GRILL.dff
#define OBJECT_AIRCON_FAN             915     //propext.ide, AIRCON_FAN.dff
#define OBJECT_FRUITCRATE2            916     //propext.ide, FRUITCRATE2.dff
#define OBJECT_FRUITCRATE1            917     //propext.ide, FRUITCRATE1.dff
#define OBJECT_CJ_FLAME_DRUM          918     //propext.ide, CJ_FLAME_Drum.dff
#define OBJECT_AIRCON                 919     //propext.ide, AIRCON.dff
#define OBJECT_Y_GENERATOR            920     //propext.ide, Y_GENERATOR.dff
#define OBJECT_CJ_IND_LIGHT           921     //propext.ide, CJ_IND_LIGHT.dff
#define OBJECT_PACKING_CARATES1       922     //propext.ide, Packing_carates1.dff
#define OBJECT_PACKING_CARATES2       923     //propext.ide, Packing_carates2.dff
#define OBJECT_FRUITCRATE3            924     //propext.ide, FRUITCRATE3.dff
#define OBJECT_RACK2                  925     //propext.ide, RACK2.dff
#define OBJECT_RUBBISH_BOX2           926     //propext.ide, RUBBISH_BOX2.dff
#define OBJECT_PIPING_DETAIL          927     //propext.ide, Piping_Detail.dff
#define OBJECT_RUBBISH_BOX1           928     //propext.ide, RUBBISH_BOX1.dff
#define OBJECT_GENERATOR              929     //propext.ide, GENERATOR.dff
#define OBJECT_O2_BOTTLES             930     //propext.ide, O2_Bottles.dff
#define OBJECT_RACK3                  931     //propext.ide, RACK3.dff
#define OBJECT_H_WHEELCHAIR           932     //propext.ide, H_WHEELCHAIR.dff
#define OBJECT_CJ_CABLEROLL           933     //propext.ide, CJ_CABLEROLL.dff
#define OBJECT_GENERATOR_BIG          934     //propext.ide, GENERATOR_BIG.dff
#define OBJECT_CJ_DRUM                935     //propext.ide, CJ_Drum.dff
#define OBJECT_CJ_DF_WORKTOP_2        936     //propext.ide, CJ_DF_WORKTOP_2.dff
#define OBJECT_CJ_DF_WORKTOP          937     //propext.ide, CJ_DF_WORKTOP.dff
#define OBJECT_CJ_DF_LIGHT            938     //propext.ide, CJ_DF_LIGHT.dff
#define OBJECT_CJ_DF_UNIT             939     //propext.ide, CJ_DF_UNIT.dff
#define OBJECT_CJ_DF_LIGHT_2          940     //propext.ide, CJ_DF_LIGHT_2.dff
#define OBJECT_CJ_DF_WORKTOP_3        941     //propext.ide, CJ_DF_WORKTOP_3.dff
#define OBJECT_CJ_DF_UNIT_2           942     //propext.ide, CJ_DF_UNIT_2.dff
#define OBJECT_GENERATOR_LOW          943     //propext.ide, GENERATOR_LOW.dff
#define OBJECT_PACKING_CARATES04      944     //propext.ide, Packing_carates04.dff
#define OBJECT_WS_CF_LAMPS            945     //propext.ide, WS_CF_LAMPS.dff
#define OBJECT_BSKBALL_LAX            946     //propext.ide, bskball_lax.dff
#define OBJECT_BSKBALLHUB_LAX01       947     //propext.ide, bskballhub_lax01.dff
#define OBJECT_PLANT_POT_10           948     //propext.ide, Plant_Pot_10.dff
#define OBJECT_PLANT_POT_4            949     //propext.ide, Plant_Pot_4.dff
#define OBJECT_PLANT_POT_12           950     //propext.ide, Plant_Pot_12.dff
#define OBJECT_CJ_VIEW_TELE2          951     //propext.ide, CJ_VIEW_TELE2.dff
#define OBJECT_GENERATOR_BIG_D        952     //propext.ide, GENERATOR_BIG_d.dff
#define OBJECT_CJ_OYSTER              953     //propext.ide, CJ_OYSTER.dff
#define OBJECT_CJ_HORSE_SHOE          954     //propext.ide, cj_horse_Shoe.dff
#define OBJECT_CJ_EXT_SPRUNK          955     //propext.ide, CJ_EXT_SPRUNK.dff
#define OBJECT_CJ_EXT_CANDY           956     //propext.ide, CJ_EXT_CANDY.dff
#define OBJECT_CJ_LIGHT_FIX_EXT       957     //propext.ide, CJ_LIGHT_FIT_EXT.dff
#define OBJECT_CJ_CHIP_MAKER          958     //propext.ide, CJ_CHIP_MAKER.dff
#define OBJECT_CJ_CHIP_MAKER_BITS     959     //propext.ide, CJ_CHIP_MAKER_BITS.dff
#define OBJECT_CJ_ARM_CRATE           960     //propext.ide, CJ_ARM_CRATE.dff
#define OBJECT_CJ_ARM_CRATE_TOP       961     //propext.ide, CJ_ARM_CRATE_top.dff
#define OBJECT_CJ_T_TICKET_PED        962     //propext.ide, CJ_T_TICKET_PED.dff
#define OBJECT_CJ_T_TICKET            963     //propext.ide, CJ_T_TICKET.dff
#define OBJECT_CJ_METAL_CRATE         964     //propext.ide, CJ_METAL_CRATE.dff
#define OBJECT_BAR_GATEBAR01          966     //barriers.ide, bar_gatebar01.dff
#define OBJECT_BAR_GATEBOX01          967     //barriers.ide, bar_gatebox01.dff
#define OBJECT_BARRIERTURN            968     //barriers.ide, barrierturn.dff
#define OBJECT_ELECTRICGATE           969     //barriers.ide, Electricgate.dff
#define OBJECT_FENCESMALLB            970     //barriers.ide, fencesmallb.dff
#define OBJECT_SUBWAYGATE             971     //barriers.ide, subwaygate.dff
#define OBJECT_TUNNELENTRANCE         972     //barriers.ide, tunnelentrance.dff
#define OBJECT_SUB_ROADBARRIER        973     //barriers.ide, sub_roadbarrier.dff
#define OBJECT_TALL_FENCE             974     //barriers.ide, tall_fence.dff
#define OBJECT_COLUMBIANGATE          975     //barriers.ide, Columbiangate.dff
#define OBJECT_PHILS_COMPND_GATE      976     //barriers.ide, phils_compnd_gate.dff
#define OBJECT_NEWTOWERDOOR1          977     //barriers.ide, newtowerdoor1.dff
#define OBJECT_SUB_ROADRIGHT          978     //barriers.ide, sub_roadright.dff
#define OBJECT_SUB_ROADLEFT           979     //barriers.ide, sub_roadleft.dff
#define OBJECT_AIRPORTGATE            980     //barriers.ide, airportgate.dff
#define OBJECT_HELIX_BARRIER          981     //barriers.ide, helix_barrier.dff
#define OBJECT_FENCESHIT              982     //barriers.ide, fenceshit.dff
#define OBJECT_FENCESHIT3             983     //barriers.ide, fenceshit3.dff
#define OBJECT_FENCESHIT2             984     //barriers.ide, fenceshit2.dff
#define OBJECT_GATE_AUTOR             985     //barriers.ide, gate_autoR.dff
#define OBJECT_GATE_AUTOL             986     //barriers.ide, gate_autoL.dff
#define OBJECT_ELECFENCE_BAR          987     //barriers.ide, elecfence_BAR.dff
#define OBJECT_WS_APGATE              988     //barriers.ide, ws_apgate.dff
#define OBJECT_AC_APGATE              989     //barriers.ide, ac_apgate.dff
#define OBJECT_BAR_BARRIER12          990     //barriers.ide, bar_barrier12.dff
#define OBJECT_BAR_BARRIERGATE1       991     //barriers.ide, bar_barriergate1.dff
#define OBJECT_BAR_BARRIER10B         992     //barriers.ide, bar_barrier10b.dff
#define OBJECT_BAR_BARRIER10          993     //barriers.ide, bar_barrier10.dff
#define OBJECT_LHOUSE_BARRIER2        994     //barriers.ide, lhouse_barrier2.dff
#define OBJECT_BAR_BARRIER16          995     //barriers.ide, bar_barrier16.dff
#define OBJECT_LHOUSE_BARRIER1        996     //barriers.ide, lhouse_barrier1.dff
#define OBJECT_LHOUSE_BARRIER3        997     //barriers.ide, lhouse_barrier3.dff
#define OBJECT_GDYN_BARRIER17         998     //barriers.ide, Gdyn_barrier17.dff
#define OBJECT_SPL_B_MAR_M            1000    //veh_mods.ide, spl_b_mar_m.dff
#define OBJECT_SPL_B_BAB_M            1001    //veh_mods.ide, spl_b_bab_m.dff
#define OBJECT_SPL_B_BAR_M            1002    //veh_mods.ide, spl_b_bar_m.dff
#define OBJECT_SPL_B_MAB_M            1003    //veh_mods.ide, spl_b_mab_m.dff
#define OBJECT_BNT_B_SC_M             1004    //veh_mods.ide, bnt_b_sc_m.dff
#define OBJECT_BNT_B_SC_L             1005    //veh_mods.ide, bnt_b_sc_l.dff
