/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#include <i_sampp/objects/ide_default>
#include <i_sampp/objects/ide_vegepart>
#include <i_sampp/objects/ide_procobj>
#include <i_sampp/objects/ide_propext>
#include <i_sampp/objects/ide_barriers>
#include <i_sampp/objects/ide_veh_mods>
#include <i_sampp/objects/ide_dynamic>
#include <i_sampp/objects/ide_dynamic2>
#include <i_sampp/objects/ide_multiobj>
#include <i_sampp/objects/ide_props>
#include <i_sampp/objects/ide_props2>
#include <i_sampp/objects/ide_levelxre>
#include <i_sampp/objects/ide_counxref>
#include <i_sampp/objects/ide_vegaxref>
#include <i_sampp/objects/ide_laxref>
#include <i_sampp/objects/ide_sfxref>
#include <i_sampp/objects/ide_levelmap>
#include <i_sampp/objects/ide_lan>
#include <i_sampp/objects/ide_seabed>
#include <i_sampp/objects/ide_lan2>
#include <i_sampp/objects/ide_las>
#include <i_sampp/objects/ide_las2>
#include <i_sampp/objects/ide_lae>
#include <i_sampp/objects/ide_lawn>
#include <i_sampp/objects/ide_law>
#include <i_sampp/objects/ide_law2>
#include <i_sampp/objects/ide_vegasn>
#include <i_sampp/objects/ide_vegasw>
#include <i_sampp/objects/ide_vegass>
#include <i_sampp/objects/ide_vegase>
#include <i_sampp/objects/ide_sfn>
