/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define PAINTJOB_CAMPER_TRUTH          0
#define PAINTJOB_REMINGTON_AZTEC       0
#define PAINTJOB_REMINGTON_FLAMES      1
#define PAINTJOB_REMINGTON_BLUEFLAMES  2
#define PAINTJOB_SLAMVAN_STRIPES       0
#define PAINTJOB_SLAMVAN_COLORFLAMES   1
#define PAINTJOB_SLAMVAN_FLAMES        2
#define PAINTJOB_BLADE_FLAMES          0
#define PAINTJOB_BLADE_AZTEC           1
#define PAINTJOB_BLADE_FLAMES2         2
#define PAINTJOB_URANUS_STRIPES        0
#define PAINTJOB_URANUS_SHARDS         1
#define PAINTJOB_URANUS_ELECTRIC       2
#define PAINTJOB_JESTER_WILD           0
#define PAINTJOB_JESTER_TRIBAL         1
#define PAINTJOB_JESTER_STRIPES        2
#define PAINTJOB_SULTAN_ALIEN          0
#define PAINTJOB_SULTAN_RALLY          1
#define PAINTJOB_SULTAN_XFLOW          2
#define PAINTJOB_STRATUM_STRIPES       0
#define PAINTJOB_STRATUM_ARROWS        1
#define PAINTJOB_STRATUM_SKILLS        2
#define PAINTJOB_ELEGY_FLAMES          0
#define PAINTJOB_ELEGY_ARROWS          1
#define PAINTJOB_ELEGY_SQUARES         2
#define PAINTJOB_FLASH_TRIBAL          0
#define PAINTJOB_FLASH_KNOTS           1
#define PAINTJOB_FLASH_TRIBAL2         2
#define PAINTJOB_SAVANNA_FLAMES        0
#define PAINTJOB_SAVANNA_AZTEC         1
#define PAINTJOB_SAVANNA_FLAMES2       2
#define PAINTJOB_BROADWAY_FLAMES       0
#define PAINTJOB_BROADWAY_FLAMES2      1
#define PAINTJOB_TORNADO_FLAMES        0
#define PAINTJOB_TORNADO_AZTEC         1
#define PAINTJOB_TORNADO_FLAMES2       2

#define PAINTJOB_REMOVE                3
