/*
 * SA-MP Includes Library+
 * Copyright (c) 2018 Ivan Kmeto
 *
 * Licensed under the MIT License.
 * http://opensource.org/licenses/mit-license
*/

#define PICKUP_BRIEFCASE           1210
#define PICKUP_MONEY               1212
#define PICKUP_INFO                1239
#define PICKUP_HEART               1240
#define PICKUP_PILL                1241
#define PICKUP_ARMOR               1242
#define PICKUP_BRIBE               1247
#define PICKUP_GTA3LOGO            1248
#define PICKUP_GREYBOMB            1252
#define PICKUP_PHOTOOP             1253
#define PICKUP_RAMPAGESSKULL       1254
#define PICKUP_RAMPAGEMSKULL       1313
#define PICKUP_PROPERTYBLUE        1272
#define PICKUP_PROPERTYGRN         1273
#define PICKUP_DOLLAR              1274
#define PICKUP_BLSHIRT             1275
#define PICKUP_TIKI                1276
#define PICKUP_SAVE                1277
#define PICKUP_DRUGS               1279
#define PICKUP_TWOPLAYER           1314
#define PICKUP_CORONA              1316
#define PICKUP_CHECKPOINT          1317
#define PICKUP_WHITEARROW          1318
#define PICKUP_YELLOWARROW         1559
#define PICKUP_PIZZABOX            1582
#define PICKUP_RHYMEBOOK           2894

#define PICKUP_WEAP_RDILDO         321
#define PICKUP_WEAP_WDILDO         322
#define PICKUP_WEAP_VIBRATOR       323
#define PICKUP_WEAP_VIBRATOR2      324
#define PICKUP_WEAP_FLOWERS        325
#define PICKUP_WEAP_CANE           326
#define PICKUP_WEAP_PHONE          330
#define PICKUP_WEAP_BRASSKNUCKLES  331
#define PICKUP_WEAP_GOLFCLUB       333
#define PICKUP_WEAP_NIGHTSTICK     334
#define PICKUP_WEAP_KNIFE          335
#define PICKUP_WEAP_BASEBALLBAT    336
#define PICKUP_WEAP_SHOVEL         337
#define PICKUP_WEAP_POOLCUE        338
#define PICKUP_WEAP_KATANA         339
#define PICKUP_WEAP_CHAINSAW       341
#define PICKUP_WEAP_GRENADE        342
#define PICKUP_WEAP_TEARGAS        343
#define PICKUP_WEAP_MOLOTOV        344
#define PICKUP_WEAP_PISTOL         346
#define PICKUP_WEAP_SILENCEDPISTOL 347
#define PICKUP_WEAP_DEAGLE         348
#define PICKUP_WEAP_SHOTGUN        349
#define PICKUP_WEAP_SAWNOFF        350
#define PICKUP_WEAP_AUTOSHOTGUN    351
#define PICKUP_WEAP_MICROUZI       352
#define PICKUP_WEAP_MP5            353
#define PICKUP_WEAP_HYDRAFLARE     354
#define PICKUP_WEAP_AK47           355
#define PICKUP_WEAP_M4             356
#define PICKUP_WEAP_RIFLE          357
#define PICKUP_WEAP_SNIPERRIFLE    358
#define PICKUP_WEAP_RPG            359
#define PICKUP_WEAP_HEATSEEKRPG    360
#define PICKUP_WEAP_FLAMETHROWER   361
#define PICKUP_WEAP_MINIGUN        362
#define PICKUP_WEAP_SATCHEL        363
#define PICKUP_WEAP_DETONATOR      364
#define PICKUP_WEAP_SPRAY          365
#define PICKUP_WEAP_EXTINGUISHER   366
#define PICKUP_WEAP_CAMERA         367
#define PICKUP_WEAP_NGOGGLES       368
#define PICKUP_WEAP_IGOGGLES       369
#define PICKUP_WEAP_JETPACK        370
#define PICKUP_WEAP_PARACHUTE      371
#define PICKUP_WEAP_TEC9           372
