/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2020, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define SKIN_CJ                    0    //Carl "CJ" Johnson (Main Character)
#define SKIN_TRUTH                 1    //The Truth
#define SKIN_MACCER                2    //Maccer
#define SKIN_ANDRE                 3    //Andre
#define SKIN_BBTHIN                4    //Barry "Big Bear" Thorne [Thin]
#define SKIN_BB                    5    //Barry "Big Bear" Thorne [Big]
#define SKIN_EMMET                 6    //Emmet
#define SKIN_MALE01                7    //Taxi Driver/Train Driver
#define SKIN_JANITOR               8    //Janitor
#define SKIN_BFORI                 9    //Normal Ped (F)
#define SKIN_BFOST                 10   //Old Woman
#define SKIN_VBFYCRP               11   //Casino croupier
#define SKIN_BFYRI                 12   //Rich Woman
#define SKIN_BFYST                 13   //Street Girl
#define SKIN_BMORI                 14   //Normal Ped (M)
#define SKIN_BMOST                 15   //Mr.Whittaker (RS Haul Owner)
#define SKIN_BMYAP                 16   //Airport Ground Worker
#define SKIN_BMYBU                 17   //Businessman
#define SKIN_BMYBE                 18   //Beach Visitor (M)
#define SKIN_BMYDJ                 19   //DJ
#define SKIN_BMYRI                 20   //Rich Guy (Madd Dogg's Manager)
#define SKIN_BMYCR                 21   //Normal Ped (M)
#define SKIN_BMYST                 22   //Normal Ped (M)
#define SKIN_WMYBMX                23   //BMXer
#define SKIN_WBDYG1                24   //Madd Dogg Bodyguard
#define SKIN_WBDYG2                25   //Madd Dogg Bodyguard
#define SKIN_WMYBP                 26   //Backpacker
#define SKIN_WMYCON                27   //Construction Worker
#define SKIN_BMYDRUG               28   //Drug Dealer
#define SKIN_WMYDRUG               29   //Drug Dealer
#define SKIN_HMYDRUG               30   //Drug Dealer
#define SKIN_DWFOLC                31   //Farm-Town Inhabitant (F)
#define SKIN_DWMOLC1               32   //Farm-Town Inhabitant (M)
#define SKIN_DWMOLC2               33   //Farm-Town Inhabitant (M)
#define SKIN_DWMYLC1               34   //Farm-Town Inhabitent (M)
#define SKIN_HMOGAR                35   //Gardener
#define SKIN_WMYGOL1               36   //Golfer
#define SKIN_WMYGOL2               37   //Golfer
#define SKIN_HFORI                 38   //Normal Ped (F)
#define SKIN_HFOST                 39   //Normal Ped (F)
#define SKIN_HFYRI                 40   //Normal Ped (F)
#define SKIN_HFYST                 41   //Normal Ped (F)
#define SKIN_JETHRO                42   //Jethro
#define SKIN_HMORI                 43   //Normal Ped (M)
#define SKIN_HMOST                 44   //Normal Ped (M)
#define SKIN_HMYBE                 45   //Beach Visitor
#define SKIN_HMYRI                 46   //Normal Ped (M)
#define SKIN_HMYCR                 47   //Normal Ped (M)
#define SKIN_HMYST                 48   //Normal Ped (M)
#define SKIN_OMOKUNG               49   //Snakehead (Da Nang)
#define SKIN_WMYMECH               50   //Mechanic
#define SKIN_BMYMOUN               51   //Mountain Biker
#define SKIN_WMYMOUN               52   //Mountain Biker
#define SKIN_OFORI                 53   //Unknown (F)
#define SKIN_OFOST                 54   //Normal Ped (F)
#define SKIN_OFYRI                 55   //Normal Ped (F)
#define SKIN_OFYST                 56   //Normal Ped (F)
#define SKIN_OMORI                 57   //Oriental Ped
#define SKIN_OMOST                 58   //Oriental Ped
#define SKIN_OMYRI                 59   //Normal Ped (M)
#define SKIN_OMYST                 60   //Normal Ped (M)
#define SKIN_WMYPLT                61   //Pilot
#define SKIN_WMOPJ                 62   //Colonel Fuhrberger
#define SKIN_BFYPRO                63   //Prostitute
#define SKIN_HFYPRO                64   //Prostitute
#define SKIN_KENDL                 65   //Kendl Johnson
#define SKIN_BMYPOL1               66   //Pool Player
#define SKIN_BMYPOL2               67   //Pool Player
#define SKIN_WMOPREA               68   //Priest/Preacher
#define SKIN_SBFYST                69   //Normal Ped (F)
#define SKIN_WMOSCI                70   //Scientist
#define SKIN_WMYSGRD               71   //Security Guard
#define SKIN_SWMYHP1               72   //Hippy
#define SKIN_SWMYHP2               73   //Hippy
#define SKIN_SWFOPRO               75   //Prostitute
#define SKIN_WFYSTEW               76   //Stewardess
#define SKIN_SWMOTR1               77   //Homeless
#define SKIN_WMOTR1                78   //Homeless
#define SKIN_BMOTR1                79   //Homeless
#define SKIN_VBMYBOX               80   //Boxer
#define SKIN_VWMYBOX               81   //Boxer
#define SKIN_VHMYELV               82   //Black Elvis
#define SKIN_VBMYELV               83   //White Elvis
#define SKIN_VIMYELV               84   //Blue Elvis
#define SKIN_VWFYPRO               85   //Prostitute
#define SKIN_RYDER3                86   //Ryder with robbery mask
#define SKIN_VWFYST1               87   //Stripper
#define SKIN_WFORI                 88   //Normal Ped (F)
#define SKIN_WFOST                 89   //Normal Ped (F)
#define SKIN_WFYJG                 90   //Jogger (F)
#define SKIN_WFYRI                 91   //Rich Woman
#define SKIN_WFYRO                 92   //Rollerskater (F)
#define SKIN_WFYST                 93   //Normal Ped (F)
#define SKIN_WMORI                 94   //Normal Ped (M)
#define SKIN_WMOST                 95   //Normal Ped (M)
#define SKIN_WMYJG                 96   //Jogger (M)
#define SKIN_WMYLG                 97   //Lifeguard (M)
#define SKIN_WMYRI                 98   //Normal Ped (M)
#define SKIN_WMYRO                 99   //Rollerskater (M)
#define SKIN_WMYCR                 100  //Biker
#define SKIN_WMYST                 101  //Normal Ped (M)
#define SKIN_BALLAS1               102  //Ballas Gang Member
#define SKIN_BALLAS2               103  //Ballas Gang Member
#define SKIN_BALLAS3               104  //Ballas Gang Member
#define SKIN_FAM1                  105  //GSF Gang Member
#define SKIN_FAM2                  106  //GSF Gang Member
#define SKIN_FAM3                  107  //GSF Gang Member
#define SKIN_LSV1                  108  //Vagos Gang Member
#define SKIN_LSV2                  109  //Vagos Gang Member
#define SKIN_LSV3                  110  //Vagos Gang Member
#define SKIN_MAFFA                 111  //Russian Mafia
#define SKIN_MAFFB                 112  //Russian Mafia
#define SKIN_MAFBOSS               113  //Russian Mafia
#define SKIN_VLA1                  114  //Aztecas Gang Member
#define SKIN_VLA2                  115  //Aztecas Gang Member
#define SKIN_VLA3                  116  //Aztecas Gang Member
#define SKIN_TRIADA                117  //Triad Member
#define SKIN_TRIADB                118  //Triad Member
#define SKIN_SINDACO               119  //Johnny Sindacco
#define SKIN_TRIBOSS               120  //Triad Member
#define SKIN_DNB1                  121  //Da Nang Gang Member
#define SKIN_DNB2                  122  //Da Nang Gang Member
#define SKIN_DNB3                  123  //Da Nang Gang Member
#define SKIN_VMAFF1                124  //Mafia Member
#define SKIN_VMAFF2                125  //Mafia Member
#define SKIN_VMAFF3                126  //Mafia Member
#define SKIN_VMAFF4                127  //Mafia Member
#define SKIN_DNMYLC                128  //Farm Inhabitant (M)
#define SKIN_DNFOLC1               129  //Farm Inhabitant (F)
#define SKIN_DNFOLC2               130  //Farm Inhabitant (F)
#define SKIN_DNFYLC                131  //Farm Inhabitant (F)
#define SKIN_DNMOLC1               132  //Farm Inhabitant (M)
#define SKIN_DNMOLC2               133  //Farm Inhabitant (M)
#define SKIN_SBMOTR2               134  //Homeless
#define SKIN_SWMOTR2               135  //Homeless
#define SKIN_SBMYTR3               136  //Normal Ped (M)
#define SKIN_SWMOTR3               137  //Homeless
#define SKIN_WFYBE                 138  //Beach Visitor (F)
#define SKIN_BFYBE                 139  //Beach Visitor (F)
#define SKIN_HFYBE                 140  //Beach Visitor (F)
#define SKIN_SOFYBU                141  //Businesswoman
#define SKIN_SBMYST                142  //Taxi Driver
#define SKIN_SBMYCR                143  //Crack Maker (M)
#define SKIN_BMYCG                 144  //Crack Maker (M)
#define SKIN_WFYCRK                145  //Crack Maker (F)
#define SKIN_HMYCM                 146  //Crack Maker (M)
#define SKIN_WMYBU                 147  //Businessman
#define SKIN_BFYBU                 148  //Businesswoman
#define SKIN_SMOKEV                149  //Big Smoke Armored
#define SKIN_WFYBU                 150  //Businesswoman
#define SKIN_DWFYLC1               151  //Normal Ped (F)
#define SKIN_WFYPRO                152  //Prostitute
#define SKIN_WMYCONB               153  //Construction Worker
#define SKIN_WMYBE                 154  //Beach Visitor (M)
#define SKIN_WMYPIZZ               155  //Well Stacked Pizza Worker
#define SKIN_BMOBAR                156  //Old Reece
#define SKIN_CWFYHB                157  //Hillbilly (F)
#define SKIN_CWMOFR                158  //Farmer (M)
#define SKIN_CWMOHB1               159  //Hillbilly (M)
#define SKIN_CWMOHB2               160  //Hillbilly (M)
#define SKIN_CWMYFR                161  //Farmer (M)
#define SKIN_CWMYHB1               162  //Hillbilly (M)
#define SKIN_BMYBOUN               163  //Black Bouncer
#define SKIN_WMYBOUN               164  //White Bouncer
#define SKIN_WMOMIB                165  //White MIB Agent
#define SKIN_BMYMIB                166  //Black MIB Agent
#define SKIN_WMYBELL               167  //Cluckin' Bell Worker
#define SKIN_BMOCHIL               168  //Hotdog/Chilli Dog Vendor
#define SKIN_SOFYRI                169  //Normal Ped (F)
#define SKIN_SOMYST                170  //Normal Ped (M)
#define SKIN_VWMYBJD               171  //Blackjack Dealer (M)
#define SKIN_VWFYCRP               172  //Casino Croupier (F)
#define SKIN_SFR1                  173  //San Fierro Rifa Gang Member
#define SKIN_SFR2                  174  //San Fierro Rifa Gang Member
#define SKIN_SFR3                  175  //San Fierro Rifa Gang Member
#define SKIN_BMYBAR                176  //Barber
#define SKIN_WMYBAR                177  //Barber
#define SKIN_WFYSEX                178  //Sex Shop Worker
#define SKIN_WMYAMMO               179  //Ammunation Salesman
#define SKIN_BMYTATT               180  //Tattoo Artist
#define SKIN_VWMYCR                181  //Punk
#define SKIN_VBMOCD                182  //Cab Driver
#define SKIN_VBMYCR                183  //Normal Ped (M)
#define SKIN_VHMYCR                184  //Normal Ped (M)
#define SKIN_SBMYRI                185  //Normal Ped (M)
#define SKIN_SOMYRI                186  //Normal Ped (M)
#define SKIN_SOMYBU                187  //Businessman
#define SKIN_SWMYST                188  //Normal Ped (M)
#define SKIN_WMYVA                 189  //Valet
#define SKIN_COPGRL3               190  //Girlfriend: Barbara Schternvart
#define SKIN_GUNGRL3               191  //Girlfriend: Helena Wankstein
#define SKIN_MECGRL3               192  //Girlfriend: Michelle Cannes
#define SKIN_NURGRL3               193  //Girlfriend: Katie Zhan
#define SKIN_CROGRL3               194  //Girlfriend: Millie Perkins
#define SKIN_GANGRL3               195  //Girlfriend: Denise Robinson
#define SKIN_CWFOFR                196  //Farm-Town Inhabitant (F)
#define SKIN_CWFOHB                197  //Hillbilly (F)
#define SKIN_CWFYFR1               198  //Farm-Town Inhabitant (F)
#define SKIN_CWFYFR2               199  //Farm-Town Inhabitant (F)
#define SKIN_CWMYHB2               200  //Hillbilly (M)
#define SKIN_DWFYLC2               201  //Farmer (F)
#define SKIN_DWMYLC2               202  //Farmer (M)
#define SKIN_OMYKARA               203  //Karate Teacher
#define SKIN_WMYKARA               204  //Karate Teacher
#define SKIN_WFYBURG               205  //Burger Shot Cashier
#define SKIN_VWMYCD                206  //Cab Driver
#define SKIN_VHFYPRO               207  //Prostitute
#define SKIN_SUZIE                 208  //Su Xi Mu
#define SKIN_OMONOOD               209  //Oriental Noodle Stand Vendor
#define SKIN_OMOBOAT               210  //Oriental Boating School Instructor
#define SKIN_WFYCLOT               211  //Clothes Shop Staff (F)
#define SKIN_VWMOTR1               212  //Homeless
#define SKIN_VWMOTR2               213  //Homeless
#define SKIN_VWFYWAI               214  //Casino Waitress (Maria Latore)
#define SKIN_SBFORI                215  //Normal Ped (F)
#define SKIN_SWFYRI                216  //Normal Ped (F)
#define SKIN_WMYCLOT               217  //Clothes Shop Staff (M)
#define SKIN_SBFOST                218  //Normal Ped (F)
#define SKIN_SBFYRI                219  //Rich Woman
#define SKIN_SBMOCD                220  //Cab Driver
#define SKIN_SBMORI                221  //Normal Ped (M)
#define SKIN_SBMOST                222  //Normal Ped (M)
#define SKIN_SHMYCR                223  //Normal Ped (M)
#define SKIN_SOFORI                224  //Normal Ped (F)
#define SKIN_SOFOST                225  //Normal Ped (F)
#define SKIN_SOFYST                226  //Normal Ped (F)
#define SKIN_SOMOBU                227  //Oriental Businessman
#define SKIN_SOMORI                228  //Oriental Ped (M)
#define SKIN_SOMOST                229  //Oriental Ped (M)
#define SKIN_SWMOTR5               230  //Homeless
#define SKIN_SWFORI                231  //Normal Ped (F)
#define SKIN_SWFOST                232  //Normal Ped (F)
#define SKIN_SWFYST                233  //Normal Ped (F)
#define SKIN_SWMOCD                234  //Cab Driver
#define SKIN_SWMORI                235  //Normal Ped (M)
#define SKIN_SWMOST                236  //Normal Ped (M)
#define SKIN_SHFYPRO               237  //Prostitute
#define SKIN_SBFYPRO               238  //Prostitute
#define SKIN_SWMOTR4               239  //Homeless
#define SKIN_SWMYRI                240  //The D.A.
#define SKIN_SMYST                 241  //Normal Ped with Afro (M)
#define SKIN_SMYST2                242  //Normal Ped Mexican (M)
#define SKIN_SFYPRO                243  //Prostitute
#define SKIN_VBFYST2               244  //Stripper
#define SKIN_VBFYPRO               245  //Prostitute
#define SKIN_VHFYST3               246  //Stripper
#define SKIN_BIKERA                247  //Biker
#define SKIN_BIKERB                248  //Biker
#define SKIN_BMYPIMP               249  //Pimp
#define SKIN_SWMYCR                250  //Normal Ped (M)
#define SKIN_WFYLG                 251  //Lifeguard (F)
#define SKIN_WMYVA2                252  //Naked Valet
#define SKIN_BMOSEC                253  //Bus Driver
#define SKIN_BIKDRUG               254  //Biker Drug Dealer
#define SKIN_WMYCH                 255  //Chaffeur (Limo Driver)
#define SKIN_SBFYSTR               256  //Stripper
#define SKIN_SWFYSTR               257  //Stripper
#define SKIN_HECK1                 258  //Heckler
#define SKIN_HECK2                 259  //Heckler
#define SKIN_BMYCON                260  //Construction Worker
#define SKIN_WMYCD1                261  //Cab Driver
#define SKIN_BMOCD                 262  //Cab Driver
#define SKIN_VWFYWA2               263  //Normal Ped (F)
#define SKIN_WMOICE                264  //Clown
#define SKIN_TENPEN                265  //Officer Frank Tenpenny
#define SKIN_PULASKI               266  //Officer Eddie Pulaski
#define SKIN_HERN                  267  //Officer Jimmy Hernandez
#define SKIN_DWAYNE                268  //Dwaine/Dwayne
#define SKIN_SMOKE                 269  //Big Smoke
#define SKIN_SWEET                 270  //Sweet
#define SKIN_RYDER                 271  //Ryder
#define SKIN_FORELLI               272  //Mafia Boss
#define SKIN_TBONE                 273  //T-Bone Mendez
#define SKIN_LAEMT1                274  //Paramedic LS
#define SKIN_LVEMT1                275  //Paramedic LV
#define SKIN_SFEMT1                276  //Paramedic SF
#define SKIN_LAFD1                 277  //Firefighter LS
#define SKIN_LVFD1                 278  //Firefighter LV
#define SKIN_SFFD1                 279  //Firefighter SF
#define SKIN_LAPD1                 280  //Policeman LS
#define SKIN_SFPD1                 281  //Policeman SF
#define SKIN_LVPD1                 282  //Policeman LV
#define SKIN_CSHER                 283  //Country Sheriff
#define SKIN_LAPDM1                284  //LSPD Motorbike Cop
#define SKIN_SWAT                  285  //S.W.A.T. Special Forces
#define SKIN_FBI                   286  //Federal Agent
#define SKIN_ARMY                  287  //San Andreas Army Soldier
#define SKIN_DSHER                 288  //Desert Sheriff
#define SKIN_ZERO                  289  //Zero
#define SKIN_ROSE                  290  //Ken Rosenberg
#define SKIN_PAUL                  291  //Kent Paul
#define SKIN_CESAR                 292  //Cesar Vialpando
#define SKIN_OGLOC                 293  //OG Loc
#define SKIN_WUZIMU                294  //Wu Zi Mu (Woozie)
#define SKIN_TORINO                295  //Michael Toreno
#define SKIN_JIZZY                 296  //Jizzy B.
#define SKIN_MADDOGG               297  //Madd Dogg
#define SKIN_CAT                   298  //Catalina
#define SKIN_CLAUDE                299  //Claude Speed

#define SKIN_UNASSIGNED            74   // -

//Skins available only for SA-MP version 0.3.7 RC3 and higher
#define SKIN_LAPDNA                300  //Policeman LS (Without gun holster)
#define SKIN_SFPDNA                301  //Policeman SF (Without gun holster)
#define SKIN_LVPDNA                302  //Policeman LV (Without gun holster)
#define SKIN_LAPDPC                303  //Policeman LS (Without uniform/unmarked)
#define SKIN_LAPDPD                304  //Policeman LS (Without uniform/unmarked)
#define SKIN_LVPDPC                305  //Policeman LV (Without uniform/unmarked)
#define SKIN_WFYCLPD               306  //Policewoman LS
#define SKIN_VBFYCPD               307  //Policewoman SF
#define SKIN_WFYCLEM               308  //Paramedic SF (F)
#define SKIN_WFYCLLV               309  //Policewoman LV
#define SKIN_CSHERNA               310  //Country Sheriff (Without hat)
#define SKIN_DSHERNA               311  //Desert Sheriff (Without hat)
