/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define SND_AMBIENCE_ENABLE           0       //Resume ambience sound
#define SND_AMBIENCE_DISABLE          1       //Stop ambience sound
#define SND_HELI_DISABLE              1000    //Disable helicopter sounds
#define SND_HELI_ENABLE               1001    //Enable helicopter sounds
#define SND_CASINO_WHEEL_START        4200    //Bandit wheel start
#define SND_CASINO_COINS              4201    //Casino slot machine falling coins
#define SND_CASINO_BLIP1              4202    //Casino slot machine blip
#define SND_CASINO_BLIP2              4203    //Casino slot machine blip

#define SND_PROPERTY_PURCHASED        182     //? CIV
#define SND_MISSION_PASSED            183     //? CIV
