/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define SND_AMBIENCE_ENABLE           0       //Resume ambience sound
#define SND_AMBIENCE_DISABLE          1       //Stop ambience sound

#define SND_HELI_DISABLE              1000    //Disable helicopter sounds
#define SND_HELI_ENABLE               1001    //Enable helicopter sounds

#define SND_POLICE_BLACK              2200    //Police Radio: "Black"
#define SND_POLICE_BLUE               2201    //Police Radio: "Blue"
#define SND_POLICE_BROWN              2202    //Police Radio: "Brown"
#define SND_POLICE_COPPER             2203    //Police Radio: "Copper"
#define SND_POLICE_CUSTOM             2204    //Police Radio: "Custom"
#define SND_POLICE_CUSTOMIZED         2205    //Police Radio: "Customized"
#define SND_POLICE_DARK               2206    //Police Radio: "Dark"
#define SND_POLICE_GOLD               2207    //Police Radio: "Gold"
#define SND_POLICE_GREEN              2208    //Police Radio: "Green"
#define SND_POLICE_GREY               2209    //Police Radio: "Grey"
#define SND_POLICE_LIGHT              2210    //Police Radio: "Light"
#define SND_POLICE_PINK               2211    //Police Radio: "Pink"
#define SND_POLICE_RED                2212    //Police Radio: "Red"
#define SND_POLICE_SILVER             2213    //Police Radio: "Silver"
#define SND_POLICE_WHITE              2214    //Police Radio: "White"

#define SND_POLICE_CENTRAL            2400    //Police Radio: "Central"
#define SND_POLICE_EAST               2401    //Police Radio: "East"
#define SND_POLICE_NORTH              2402    //Police Radio: "North"
#define SND_POLICE_SOUTH              2403    //Police Radio: "South"
#define SND_POLICE_WEST               2404    //Police Radio: "West"

#define SND_POLICE_HEADTOA10          2600    //Police Radio: "Head to a 10-"
#define SND_POLICE_INA                2601    //Police Radio: "In a"
#define SND_POLICE_INWATER            2602    //Police Radio: "In water"
#define SND_POLICE_ONA                2603    //Police Radio: "On a"
#define SND_POLICE_ONFOOT             2604    //Police Radio: "On foot"
#define SND_POLICE_RESPONDTOA10       2605    //Police Radio: "Respond to a 10-"
#define SND_POLICE_SUSPECTINWATER     2606    //Police Radio: "Suspect in water"
#define SND_POLICE_SUSPECTLASTSEEN    2607    //Police Radio: "Suspect last seen"
#define SND_POLICE_WEGOTA10           2608    //Police Radio: "We got a 10-"

#define SND_POLICE_17IN               2800    //Police Radio: "17 in"
#define SND_POLICE_21IN               2801    //Police Radio: "21 in"
#define SND_POLICE_24IN               2802    //Police Radio: "24 in"
#define SND_POLICE_28IN               2803    //Police Radio: "28 in"
#define SND_POLICE_34IN               2804    //Police Radio: "34 in"
#define SND_POLICE_37IN               2805    //Police Radio: "37 in"
#define SND_POLICE_7IN                2806    //Police Radio: "7 in"
#define SND_POLICE_71IN               2807    //Police Radio: "71 in"
#define SND_POLICE_81IN               2808    //Police Radio: "81 in"
#define SND_POLICE_90IN               2809    //Police Radio: "90 in"
#define SND_POLICE_91IN               2810    //Police Radio: "91 in"
#define SND_POLICE_A10_1              2811    //Police Radio: "a 10-"
#define SND_POLICE_A10_2              2812    //Police Radio: "a 10-"
#define SND_POLICE_A10_3              2813    //Police Radio: "a 10-"

#define SND_POLICE_2DOOR              3000    //Police Radio: "2 Door"
#define SND_POLICE_4DOOR              3001    //Police Radio: "4 Door"
#define SND_POLICE_AMBULANCE          3002    //Police Radio: "Ambulance"
#define SND_POLICE_ARTICCAB           3003    //Police Radio: "Artic Cab"
#define SND_POLICE_BEACHBUGGY         3004    //Police Radio: "Beach Buggy"
#define SND_POLICE_BIKE               3005    //Police Radio: "Bike"
#define SND_POLICE_BOAT               3006    //Police Radio: "Boat"
#define SND_POLICE_BUGGY              3007    //Police Radio: "Buggy"
#define SND_POLICE_BULLDOZER          3008    //Police Radio: "Bulldozer"
#define SND_POLICE_BUS                3009    //Police Radio: "Bus"
#define SND_POLICE_CAMPERVAN          3010    //Police Radio: "Camper Van"
#define SND_POLICE_COACH              3011    //Police Radio: "Coach"
#define SND_POLICE_COMBINEHARVESTER   3012    //Police Radio: "Combine Harvester"
#define SND_POLICE_COMPACT            3013    //Police Radio: "Compact"
#define SND_POLICE_CONVERTIBLE        3014    //Police Radio: "Convertible"
#define SND_POLICE_COUPE              3015    //Police Radio: "Coupe"
#define SND_POLICE_CRUISER            3016    //Police Radio: "Cruiser"
#define SND_POLICE_FIRETRUCK          3017    //Police Radio: "Firetruck"
#define SND_POLICE_FORKLIFT           3018    //Police Radio: "Forklift"
#define SND_POLICE_FREIGHTTRAIN       3019    //Police Radio: "Freight Train"
#define SND_POLICE_GARBAGETRUCK       3020    //Police Radio: "Garbage Truck"
#define SND_POLICE_GASTANKER          3021    //Police Radio: "Gas Tanker"
#define SND_POLICE_GOLFCART           3022    //Police Radio: "Golf Cart"
#define SND_POLICE_GOKART             3023    //Police Radio: "Go Kart"
#define SND_POLICE_HEARSE             3024    //Police Radio: "Hearse"
#define SND_POLICE_HELICOPTER         3025    //Police Radio: "Helicopter"
#define SND_POLICE_HOVERCRAFT         3026    //Police Radio: "Hovercraft"
#define SND_POLICE_ICECREAMVAN        3027    //Police Radio: "Icecream Van"
#define SND_POLICE_JEEP               3028    //Police Radio: "Jeep"
#define SND_POLICE_LAWNMOWER          3029    //Police Radio: "Lawn Mower"
#define SND_POLICE_LIMO               3030    //Police Radio: "Limo"
#define SND_POLICE_LOWRIDER           3031    //Police Radio: "Lowrider"
#define SND_POLICE_MOPED              3032    //Police Radio: "Moped"
#define SND_POLICE_MOTORBIKE          3033    //Police Radio: "Motorbike"
#define SND_POLICE_OFFROAD            3034    //Police Radio: "Offroad"
#define SND_POLICE_PEOPLECARRIER      3035    //Police Radio: "People Carrier"
#define SND_POLICE_PICKUP             3036    //Police Radio: "Pickup"
#define SND_POLICE_PLANE              3037    //Police Radio: "Plane"
#define SND_POLICE_POLICECAR          3038    //Police Radio: "Police Car"
#define SND_POLICE_POLICEVAN          3039    //Police Radio: "Police Van"
#define SND_POLICE_QUADBIKE           3040    //Police Radio: "Quad Bike"
#define SND_POLICE_RUBBERDINGHY       3041    //Police Radio: "Rubber Dinghy"
#define SND_POLICE_SANDBUGGY          3042    //Police Radio: "Sand Buggy"
#define SND_POLICE_SEAPLANE           3043    //Police Radio: "Sea Plane"
#define SND_POLICE_SNOWCAT            3044    //Police Radio: "Snowcat"
#define SND_POLICE_SPEEDBOAT          3045    //Police Radio: "Speedboat"
#define SND_POLICE_SPORT              3046    //Police Radio: "Sport"
#define SND_POLICE_SPORTSCAR          3047    //Police Radio: "Sports Car"
#define SND_POLICE_SPORTSBIKE         3048    //Police Radio: "Sports Bike"
#define SND_POLICE_STATIONVAGON       3049    //Police Radio: "Station Wagon"
#define SND_POLICE_SUV                3050    //Police Radio: "SUV"
#define SND_POLICE_TANK               3051    //Police Radio: "Tank"
#define SND_POLICE_TAXI               3052    //Police Radio: "Taxi"
#define SND_POLICE_TRACTOR            3053    //Police Radio: "Tractor"
#define SND_POLICE_TRAIN              3054    //Police Radio: "Train"
#define SND_POLICE_TRAM               3055    //Police Radio: "Tram"
#define SND_POLICE_TRUCK              3056    //Police Radio: "Truck"
#define SND_POLICE_VAN                3057    //Police Radio: "Van"

#define SND_CASINO_WHEEL_START        4200    //Bandit wheel start
#define SND_CASINO_COINS              4201    //Casino slot machine falling coins
#define SND_CASINO_BLIP1              4202    //Casino slot machine blip
#define SND_CASINO_BLIP2              4203    //Casino slot machine blip

#define SND_GYM_LINE_01               4800    //Gym Guy: "Yo' you wanna learn some new moves?"
#define SND_GYM_LINE_02               4801    //Gym Guy: "Suit youself homes, but the streets are mean dude."
#define SND_GYM_LINE_03               4802    //Gym Guy: "Man you're an embarrassment, get yourselves some muscles first."
#define SND_GYM_LINE_04               4803    //Gym Guy: "Hey you wanna go around with me?"
#define SND_GYM_LINE_05               4804    //Gym Guy: "Yo' pay attention and you might learn something."
#define SND_GYM_LINE_06               4805    //Gym Guy: "Yo' charge in and batter yo opponent!"
#define SND_GYM_LINE_07               4806    //Gym Guy: "Make sure yo' opponent is down and out!"
#define SND_GYM_LINE_08               4807    //Gym Guy: "Never give your opponent time to recover."

#define SND_GAME_BUZZLOOP             5200    //Continuous buzz
#define SND_GAME_BLING                5201    //Bling
#define SND_GAME_BBEE_DAMAGE          5202    //Bumblebee video game take damage
#define SND_GAME_BBEE_GAMEOVER        5203    //Bumblebee video game game over
#define SND_GAME_BBEE_FIRE            5204    //Bumblebee video game firing sound
#define SND_GAME_BBEE_BEEP            5205    //Bumblebee video game beep
#define SND_GAME_BBEE_DEATH           5206    //Bumblebee video game death
