/*
 * SA-MP Includes Library+
 * 2018 - 2020, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//GameText Styles
#define GMTEXT_STYLE_PRICEDOWN     0
#define GMTEXT_STYLE_RPRICEDOWN    1
#define GMTEXT_STYLE_SA            2 //Does not disappear until player respawns
#define GMTEXT_STYLE_SLIM          3
#define GMTEXT_STYLE_SLIM2         4
#define GMTEXT_STYLE_SLIMW         5
#define GMTEXT_STYLE_BPRICEDOWN    6
