/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2021, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//GameText Styles
#define GMTEXT_STYLE_PRICEDOWN     0
#define GMTEXT_STYLE_RPRICEDOWN    1
#define GMTEXT_STYLE_SA            2 //Does not disappear until player respawns
#define GMTEXT_STYLE_SLIM          3
#define GMTEXT_STYLE_SLIM2         4
#define GMTEXT_STYLE_SLIMW         5
#define GMTEXT_STYLE_BPRICEDOWN    6

//Might not work properly
#define GMTEXT_STYLE_VEHNAME       7
#define GMTEXT_STYLE_LOCATION      8
#define GMTEXT_STYLE_RADIO         9
#define GMTEXT_STYLE_RADIOW        10
#define GMTEXT_STYLE_PMONEY        11
#define GMTEXT_STYLE_NMONEY        12
#define GMTEXT_STYLE_STUNT         13
#define GMTEXT_STYLE_CLOCK         14
#define GMTEXT_STYLE_NOTIFICATION  15
