/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//Cars
#define VEH_LANDSTALKER            400
#define VEH_BRAVURA                401
#define VEH_BUFFALO                402
#define VEH_LINERUNNER             403
#define VEH_PERENNIAL              404
#define VEH_SENTINEL               405
#define VEH_DUMPER                 406
#define VEH_FIRETRUCK              407
#define VEH_TRASHMASTER            408
#define VEH_STRETCH                409
#define VEH_MANANA                 410
#define VEH_INFERNUS               411
#define VEH_VOODOO                 412
#define VEH_PONY                   413
#define VEH_MULE                   414
#define VEH_CHEETAH                415
#define VEH_AMBULANCE              416
#define VEH_MOONBEAM               418
#define VEH_ESPERANTO              419
#define VEH_TAXI                   420
#define VEH_WASHINGTON             421
#define VEH_BOBCAT                 422
#define VEH_MRWHOOPEE              423
#define VEH_BFINJECTION            424
#define VEH_PREMIER                426
#define VEH_ENFORCER               427
#define VEH_SECURICAR              428
#define VEH_BANSHEE                429
#define VEH_BUS                    431
#define VEH_RHINO                  432
#define VEH_BARRACKS               433
#define VEH_HOTKNIFE               434
#define VEH_PREVION                436
#define VEH_COACH                  437
#define VEH_CABBIE                 438
#define VEH_STALLION               439
#define VEH_RUMPO                  440
#define VEH_ROMERO                 442
#define VEH_PACKER                 443
#define VEH_MONSTER                444
#define VEH_ADMIRAL                445
#define VEH_TURISMO                451
#define VEH_FLATBED                455
#define VEH_YANKEE                 456
#define VEH_CADDY                  457
#define VEH_SOLAIR                 458
#define VEH_TOPFUN                 459
#define VEH_GLENDALE               466
#define VEH_OCEANIC                467
#define VEH_PATRIOT                470
#define VEH_HERMES                 474
#define VEH_SABRE                  475
#define VEH_ZR350                  477
#define VEH_WALTON                 478
#define VEH_REGINA                 479
#define VEH_COMET                  480
#define VEH_BURRITO                482
#define VEH_CAMPER                 483
#define VEH_BAGGAGE                485
#define VEH_DOZER                  486
#define VEH_RANCHER                489
#define VEH_FBIRANCHER             490
#define VEH_VIRGO                  491
#define VEH_GREENWOOD              492
#define VEH_HOTRING                494
#define VEH_SANDKING               495
#define VEH_BLISTA                 496
#define VEH_BOXVILLE               498
#define VEH_BENSON                 499
#define VEH_MESA                   500
#define VEH_HOTRINGA               502
#define VEH_HOTRINGB               503
#define VEH_BLOODRING              504
#define VEH_RANCHERLURE            505
#define VEH_SUPERGT                506
#define VEH_ELEGANT                507
#define VEH_JOURNEY                508
#define VEH_TANKER                 514
#define VEH_ROADTRAIN              515
#define VEH_NEBULA                 516
#define VEH_MAJESTIC               517
#define VEH_BUCCANEER              518
#define VEH_CEMENTTRUCK            524
#define VEH_TOWTRUCK               525
#define VEH_FORTUNE                526
#define VEH_CADRONA                527
#define VEH_FBITRUCK               528
#define VEH_WILLARD                529
#define VEH_FORKLIFT               530
#define VEH_TRACTOR                531
#define VEH_COMBINE                532
#define VEH_FELTZER                533
#define VEH_REMINGTON              534
#define VEH_SLAMVAN                535
#define VEH_BLADE                  536
#define VEH_VORTEX                 539
#define VEH_VINCENT                540
#define VEH_BULLET                 541
#define VEH_CLOVER                 542
#define VEH_SADLER                 543
#define VEH_FIRETRUCKLA            544
#define VEH_HUSTLER                545
#define VEH_INTRUDER               546
#define VEH_PRIMO                  547
#define VEH_TAMPA                  549
#define VEH_SUNRISE                550
#define VEH_MERIT                  551
#define VEH_UTILITY                552
#define VEH_YOSEMITE               554
#define VEH_WINDSOR                555
#define VEH_MONSTERA               556
#define VEH_MONSTERB               557
#define VEH_URANUS                 558
#define VEH_JESTER                 559
#define VEH_SULTAN                 560
#define VEH_STRATUM                561
#define VEH_ELEGY                  562
#define VEH_FLASH                  565
#define VEH_TAHOMA                 566
#define VEH_SAVANNA                567
#define VEH_BANDITO                568
#define VEH_KART                   571
#define VEH_MOWER                  572
#define VEH_DUNE                   573
#define VEH_SWEEPER                573
#define VEH_BROADWAY               575
#define VEH_TORNADO                576
#define VEH_DFT30                  578
#define VEH_HUNTLEY                579
#define VEH_STAFFORD               580
#define VEH_NEWSVAN                582
#define VEH_TUG                    583
#define VEH_EMPEROR                585
#define VEH_EUROS                  587
#define VEH_HOTDOG                 588
#define VEH_CLUB                   589
#define VEH_COPCARLA               596
#define VEH_COPCARSF               597
#define VEH_COPCARLV               598
#define VEH_RANGER                 599
#define VEH_PICADOR                600
#define VEH_SWATVAN                601
#define VEH_ALPHA                  602
#define VEH_PHOENIX                603
#define VEH_GLENSHIT               604
#define VEH_SADLERSHIT             605
#define VEH_BOXVILLEBURG           609

//Helicopters
#define VEH_LEVIATHAN              417
#define VEH_HUNTER                 425
#define VEH_SEASPARROW             447
#define VEH_SPARROW                469
#define VEH_MAVERICK               487
#define VEH_SANNMAVERICK           488
#define VEH_POLMAV                 497
#define VEH_CARGOBOB               548
#define VEH_RAINDANCE              563

//Boats
#define VEH_PREDATOR               430
#define VEH_SQUALO                 446
#define VEH_SPEEDER                452
#define VEH_REEFER                 453
#define VEH_TROPIC                 454
#define VEH_COASTGUARD             472
#define VEH_DINGHY                 473
#define VEH_MARQUIS                484
#define VEH_JETMAX                 493
#define VEH_LAUNCH                 595

//Truck Trailers
#define VEH_ARTICLETRAILER1        435
#define VEH_ARTICLETRAILER2        450
#define VEH_PETROLTRAILER          584
#define VEH_ARTICLETRAILER3        591

//RC Vehicles
#define VEH_RCBANDIT               441
#define VEH_RCBARON                464
#define VEH_RCRAIDER               465
#define VEH_RCGOBLIN               501
#define VEH_RCTIGER                564
#define VEH_RCCAM                  594

//Motorbikes
#define VEH_PIZZABOY               448
#define VEH_PCJ600                 461
#define VEH_FAGGIO                 462
#define VEH_FREEWAY                463
#define VEH_SANCHEZ                468
#define VEH_QUAD                   471
#define VEH_FCR900                 521
#define VEH_NRG500                 522
#define VEH_COPBIKE                523
#define VEH_BF400                  581
#define VEH_WAYFARER               586

//Unique Vehicles
#define VEH_TRAM                   449

//Airplanes
#define VEH_SKIMMER                460
#define VEH_RUSTLER                476
#define VEH_BEAGLE                 511
#define VEH_CROPDUSTER             512
#define VEH_STUNTPLANE             513
#define VEH_SHAMAL                 519
#define VEH_HYDRA                  520
#define VEH_NEVADA                 553
#define VEH_AT400                  577
#define VEH_ANDROMADA              592
#define VEH_DODO                   593

//Bicycles
#define VEH_BMX                    481
#define VEH_BIKE                   509
#define VEH_MTBIKE                 510

//Trains + Train Trailers
#define VEH_FREIGHTT               537
#define VEH_STREAKT                538
#define VEH_FREIGHTTRAILER         569
#define VEH_STREAKTRAILER          570
#define VEH_FREIGHTBOXT            590

//Misc Trailers
#define VEH_BAGBOXA                606
#define VEH_BAGBOXB                607
#define VEH_TUGSTAIRS              608
#define VEH_FARMTRAILER            610
#define VEH_UTILITYTRAILER         611


new vehicleName[213][] = {
"Unknown",
"Landstalker",
"Bravura",
"Buffalo",
"Linerunner",
"Perennial",
"Sentinel",
"Dumper",
"Firetruck",
"Trashmaster",
"Stretch",
"Manana",
"Infernus",
"Voodoo",
"Pony",
"Mule",
"Cheetah",
"Ambulance",
"Leviathan",
"Moonbeam",
"Esperanto",
"Taxi",
"Washington",
"Bobcat",
"Mr. Whoopee",
"BF Injection",
"Hunter",
"Premier",
"Enforcer",
"Securicar",
"Banshee",
"Predator",
"Bus",
"Rhino",
"Barracks",
"Hotknife",
"Article Trailer 1",
"Previon",
"Coach",
"Cabbie",
"Stallion",
"Rumpo",
"RC Bandit",
"Romero",
"Packer",
"Monster",
"Admiral",
"Squalo",
"Sea Sparrow",
"Pizzaboy",
"Tram",
"Article Trailer 2",
"Turismo",
"Speeder",
"Reefer",
"Tropic",
"Flatbed",
"Yankee",
"Caddy",
"Solair",
"Topfun Van",
"Skimmer",
"PCJ-600",
"Faggio",
"Freeway",
"RC Baron",
"RC Raider",
"Glendale",
"Oceanic",
"Sanchez",
"Sparrow",
"Patriot",
"Quad",
"Coastguard",
"Dinghy",
"Hermes",
"Sabre",
"Rustler",
"ZR-350",
"Walton",
"Regina",
"Comet",
"BMX",
"Burrito",
"Camper",
"Marquis",
"Baggage",
"Dozer",
"Maverick",
"News Chopper",
"Rancher",
"FBI Rancher",
"Virgo",
"Greenwood",
"Jetmax",
"Hotring Racer",
"Sandking",
"Blista Compact",
"Police Maverick",
"Boxville",
"Benson",
"Mesa",
"RC Goblin",
"Hotring Racer A",
"Hotring Racer B",
"Bloodring Banger",
"Rancher Lure",
"Super GT",
"Elegant",
"Journey",
"Bike",
"Mountain Bike",
"Beagle",
"Cropduster",
"Stuntplane",
"Tanker",
"Roadtrain",
"Nebula",
"Majestic",
"Buccaneer",
"Shamal",
"Hydra",
"FCR-900",
"NRG-500",
"HPV1000",
"Cement Truck",
"Towtruck",
"Fortune",
"Cadrona",
"FBI Truck",
"Willard",
"Forklift",
"Tractor",
"Combine Harvester",
"Feltzer",
"Remington",
"Slamvan",
"Blade",
"Freight Train",
"Brownstreak",
"Vortex",
"Vincent",
"Bullet",
"Clover",
"Sadler",
"Firetruck LA",
"Hustler",
"Intruder",
"Primo",
"Cargobob",
"Tampa",
"Sunrise",
"Merit",
"Utility Van",
"Nevada",
"Yosemite",
"Windsor",
"Monster A",
"Monster B",
"Uranus",
"Jester",
"Sultan",
"Stratum",
"Elegy",
"Raindance",
"RC Tiger",
"Flash",
"Tahoma",
"Savanna",
"Bandito",
"Freight Flat Trailer",
"Streak Trailer",
"Kart",
"Mower",
"Dune",
"Sweeper",
"Broadway",
"Tornado",
"AT400",
"DFT-30",
"Huntley",
"Stafford",
"BF-400",
"Newsvan",
"Tug",
"Petrol Trailer",
"Emperor",
"Wayfarer",
"Euros",
"Hotdog",
"Club",
"Freight Box Trailer",
"Article Trailer 3",
"Andromada",
"Dodo",
"RC Cam",
"Launch",
"Police Car (LSPD)",
"Police Car (SFPD)",
"Police Car (LVPD)",
"Ranger",
"Picador",
"S.W.A.T.",
"Alpha",
"Phoenix",
"Glendale Shit",
"Sadler Shit",
"Baggage Trailer A",
"Baggage Trailer B",
"Tug Stairs Trailer",
"Boxville",
"Farm Trailer",
"Utility Trailer"
};
