/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2020, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//Vehicle Health Conditions
#define VEH_HEALTH_FULL            1000
#define VEH_HEALTH_FULL_LOW        650
#define VEH_HEALTH_WHITESMOKE      649
#define VEH_HEALTH_WHITESMOKE_LOW  550
#define VEH_HEALTH_GREYSMOKE       549
#define VEH_HEALTH_GREYSMOKE_LOW   390
#define VEH_HEALTH_BLACKSMOKE      389
#define VEH_HEALTH_BLACKSMOKE_LOW  250
#define VEH_HEALTH_ONFIRE          249
