/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//Vehicle Health Conditions
#define VEH_HEALTH_FULL             1000   //Maximum vehicle health value
#define VEH_HEALTH_FULL_LOW         650    //Limit just before vehicle starts emitting white smoke
#define VEH_HEALTH_WHITESMOKE       649    //Overheating engine emitting white smoke
#define VEH_HEALTH_WHITESMOKE_LOW   550    //Limit before smoke turns grey
#define VEH_HEALTH_GREYSMOKE        549    //Overheating engine emitting grey smoke
#define VEH_HEALTH_GREYSMOKE_LOW    390    //Limit before smoke turns black
#define VEH_HEALTH_BLACKSMOKE       389    //Hot engine emitting black smoke
#define VEH_HEALTH_BLACKSMOKE_LOW   250    //Limit before engine catches fire
#define VEH_HEALTH_ONFIRE           249    //Damaged engine on fire
