/*
 * SA-MP Includes Library+
 * Copyright (c) 2020 Ivan Kmeťo
 *
 * Licensed under the MIT License.
 * http://opensource.org/licenses/mit-license
 */

//Vehicle Health Conditions
#define VEH_HEALTH_FULL            1000
#define VEH_HEALTH_FULL_LOW        650
#define VEH_HEALTH_WHITESMOKE      649
#define VEH_HEALTH_WHITESMOKE_LOW  550
#define VEH_HEALTH_GREYSMOKE       549
#define VEH_HEALTH_GREYSMOKE_LOW   390
#define VEH_HEALTH_BLACKSMOKE      389
#define VEH_HEALTH_BLACKSMOKE_LOW  250
#define VEH_HEALTH_ONFIRE          249
