/*
 * SA-MP Includes Library+
 * Copyright (c) 2018 Ivan Kmeto
 *
 * Licensed under the MIT License.
 * http://opensource.org/licenses/mit-license
*/

#define WEATHER_EXSUNNY_LA         0
#define WEATHER_SUNNY_LA           1
#define WEATHER_EXSUNNY_SMOG_LA    2
#define WEATHER_SUNNY_SMOG_LA      3
#define WEATHER_CLOUDY_LA          4
#define WEATHER_SUNNY_SF           5
#define WEATHER_EXSUNNY_SF         6
#define WEATHER_CLOUDY_SF          7
#define WEATHER_RAINY_SF           8
#define WEATHER_FOGGY_SF           9
#define WEATHER_SUNNY_VEGAS        10
#define WEATHER_EXSUNNY_VEGAS      11
#define WEATHER_CLOUDY_VEGAS       12
#define WEATHER_EXSUNNY_CTRYSIDE   13
#define WEATHER_SUNNY_CTRYSIDE     14
#define WEATHER_CLOUDY_CTRYSIDE    15
#define WEATHER_RAINY_CTRYSIDE     16
#define WEATHER_EXSUNNY_DESERT     17
#define WEATHER_SUNNY_DESERT       18
#define WEATHER_SANDSTORM_DESERT   19
#define WEATHER_UNDERWATER         20
