/*
 * SA-MP Includes Library+
 * Copyright (c) 2018 Ivan Kmeťo
 *
 * Licensed under the MIT License.
 * http://opensource.org/licenses/mit-license
 */

//Weapon Slot 0
#define WEAP_FIST                  0
#define WEAP_BRASSKNUCKLES         1

//Weapon Slot 1
#define WEAP_GOLFCLUB              2
#define WEAP_NIGHTSTICK            3
#define WEAP_KNIFE                 4
#define WEAP_BASEBALLBAT           5
#define WEAP_SHOVEL                6
#define WEAP_POOLCUE               7
#define WEAP_KATANA                8
#define WEAP_CHAINSAW              9

//Weapon Slot 10
#define WEAP_RDILDO                10
#define WEAP_WDILDO                11
#define WEAP_VIBRATOR              12
#define WEAP_VIBRATOR2             13
#define WEAP_FLOWERS               14
#define WEAP_CANE                  15

//Weapon Slot 8
#define WEAP_GRENADE               16
#define WEAP_TEARGAS               17
#define WEAP_MOLOTOV               18
#define WEAP_SATCHEL               39

//Weapon Slot 2
#define WEAP_PISTOL                22
#define WEAP_SILENCEDPISTOL        23
#define WEAP_DEAGLE                24

//Weapon Slot 3
#define WEAP_SHOTGUN               25
#define WEAP_SAWEDOFF              26
#define WEAP_AUTOSHOTGUN           27

//Weapon Slot 4
#define WEAP_MICROUZI              28
#define WEAP_MP5                   29
#define WEAP_TEC9                  32

//Weapon Slot 5
#define WEAP_AK47                  30
#define WEAP_M4                    31

//Weapon Slot 6
#define WEAP_RIFLE                 33
#define WEAP_SNIPERRIFLE           34

//Weapon Slot 7
#define WEAP_RPG                   35
#define WEAP_HEATRPG               36
#define WEAP_FLAMETHROWER          37
#define WEAP_MINIGUN               38

//Weapon Slot 12
#define WEAP_DETONATOR             40

//Weapon Slot 9
#define WEAP_SPRAY                 41
#define WEAP_EXTINGUISHER          42
#define WEAP_CAMERA                43

//Weapon Slot 11
#define WEAP_NGOGGLES              44
#define WEAP_TGOGGLES              45
#define WEAP_PARACHUTE             46
