/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


#define WEATHER_EXSUNNY_LA         0    //Los Santos specific weather
#define WEATHER_SUNNY_LA           1    //Los Santos specific weather
#define WEATHER_EXSUNNY_SMOG_LA    2    //Los Santos specific weather
#define WEATHER_SUNNY_SMOG_LA      3    //Los Santos specific weather
#define WEATHER_CLOUDY_LA          4    //Los Santos specific weather
#define WEATHER_SUNNY_SF           5    //San Fierro specific weather
#define WEATHER_EXSUNNY_SF         6    //San Fierro specific weather
#define WEATHER_CLOUDY_SF          7    //San Fierro specific weather
#define WEATHER_RAINY_SF           8    //San Fierro specific weather
#define WEATHER_FOGGY_SF           9    //San Fierro specific weather
#define WEATHER_SUNNY_VEGAS        10   //Las Venturas specific weather
#define WEATHER_EXSUNNY_VEGAS      11   //Las Venturas specific weather
#define WEATHER_CLOUDY_VEGAS       12   //Las Venturas specific weather
#define WEATHER_EXSUNNY_CTRYSIDE   13   //Countryside specific weather
#define WEATHER_SUNNY_CTRYSIDE     14   //Countryside specific weather
#define WEATHER_CLOUDY_CTRYSIDE    15   //Countryside specific weather
#define WEATHER_RAINY_CTRYSIDE     16   //Countryside specific weather
#define WEATHER_EXSUNNY_DESERT     17   //Bone County specific weather
#define WEATHER_SUNNY_DESERT       18   //Bone County specific weather
#define WEATHER_SANDSTORM_DESERT   19   //Bone County specific weather
#define WEATHER_UNDERWATER         20   //Used when camera is underwater
#define WEATHER_INTERIOR1          21   //Weather used in interiors
#define WEATHER_INTERIOR2          22   //Weather used in interiors
