/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//int_veg.ide
#define OBJ_TRIAD_BAR              14560   //triad_bar.dff
#define OBJ_TRIAD_NEON             14561   //triad_neon.dff
#define OBJ_TRIAD_LION             14562   //triad_lion.dff
#define OBJ_TRIAD_MAIN             14563   //triad_main.dff
#define OBJ_TRIAD_LIGHTS           14564   //triad_lights.dff
#define OBJ_TRIAD_BAR_STUFF        14565   //triad_bar_stuff.dff
#define OBJ_BUDHA_WHEL1B           14566   //budha_whel1b.dff
#define OBJ_BUDHA_WHEL02B          14567   //budha_whel02b.dff
#define OBJ_BUDHA_WHEL03B          14568   //budha_whel03b.dff
#define OBJ_TR_MAN_PILLAR          14569   //tr_man_pillar.dff
#define OBJ_TR_MAN_GLASS           14570   //tr_man_glass.dff
#define OBJ_CHINAFURN1             14571   //chinafurn1.dff
#define OBJ_MAINTENANCE16          14572   //maintenance16.dff
#define OBJ_MAINTENANCE03          14573   //maintenance03.dff
#define OBJ_MAINTENANCE20          14574   //maintenance20.dff
#define OBJ_MAINTENANCE31          14575   //maintenance31.dff
#define OBJ_VAULT_DOOR             14576   //vault_door.dff
#define OBJ_MAFCASLOADBAY01        14577   //mafCasLoadbay01.dff
#define OBJ_MAFCASPIPES01          14578   //mafCasPipes01.dff
#define OBJ_MAFCASLITES01          14579   //MafCasLites01.dff
#define OBJ_MAFCASGOLDBITS01       14580   //mafCasGoldBits01.dff
#define OBJ_AB_MAFIASUITE01ZZZ     14581   //ab_mafiaSuite01zzz.dff
#define OBJ_MAFIACASINOBAR1        14582   //mafiaCasinoBar1.dff
#define OBJ_AB_MAFCASLAUND         14583   //ab_mafCasLaund.dff
#define OBJ_AB_ABBATOIR05          14584   //ab_abbatoir05.dff
#define OBJ_AB_ABBATOIR04          14585   //ab_abbatoir04.dff
#define OBJ_AB_ABBATOIR03          14586   //ab_abbatoir03.dff
#define OBJ_AB_ABBATOIR02          14587   //ab_abbatoir02.dff
#define OBJ_AB_ABBATOIR01          14588   //ab_abbatoir01.dff
#define OBJ_AB_ABBATOIR06          14589   //ab_abbatoir06.dff
#define OBJ_MAFCASTOPFLOOR         14590   //mafCasTopfoor.dff
#define OBJ_MAFCASWALLLITE         14591   //mafcasWallLite.dff
#define OBJ_MAFCASLOADBAY02        14592   //mafCasLoadbay02.dff
#define OBJ_PAPERCHASE04           14593   //paperchase04.dff
#define OBJ_PAPERCHASE03           14594   //paperchase03.dff
#define OBJ_PAPERCHASE02           14595   //paperchase02.dff
#define OBJ_PAPERCHASE_STAIRS      14596   //paperchase_stairs.dff
#define OBJ_PAPERCHASE07           14597   //paperchase07.dff
#define OBJ_PAPERCHASE_GLASS       14598   //paperchase_glass.dff
#define OBJ_PAPERCHASE08           14599   //paperchase08.dff
#define OBJ_PAPERCHASE_BITS2       14600   //paperchase_bits2.dff
#define OBJ_MAFCASLITES02          14601   //MafCasLites02.dff
#define OBJ_PAPERCHASE01           14602   //paperchase01.dff
#define OBJ_BIKESCHL_MAIN          14603   //bikeschl_main.dff
#define OBJ_TV_STAND_BIKE          14604   //tv_stand_bike.dff
#define OBJ_TRIAD_LIGHTS2          14605   //triad_lights2.dff
#define OBJ_MAFCASMAIN4            14606   //MafCasMain4.dff
#define OBJ_TRIAD_MAIN2            14607   //triad_main2.dff
#define OBJ_TRIAD_BUDDHA01         14608   //triad_buddha01.dff
#define OBJ_MAFCASLITES04          14609   //MafCasLites04.dff
#define OBJ_MAFCASLITES05          14610   //MafCasLites05.dff
#define OBJ_MAFIACASINOBARLITE     14611   //mafiaCasinoBarLite.dff
#define OBJ_AB_ABATTOIR_BOX2       14612   //ab_abattoir_box2.dff
#define OBJ_AB_ABATTOIR_BOX1       14613   //ab_abattoir_box1.dff
#define OBJ_TRIAD_MAIN3            14614   //triad_main3.dff
#define OBJ_ABATOIR_DAYLITE        14615   //abatoir_daylite.dff
#define OBJ_AB_PILLARTEMP3         14616   //ab_pillarTemp3.dff
#define OBJ_AB_PILLARTEMP2         14617   //ab_pillarTemp2.dff
#define OBJ_AB_PILLARTEMP1         14618   //ab_pillarTemp1.dff
#define OBJ_TRICAS_SLOTTABLE2      14619   //tricas_slotTable2.dff
#define OBJ_TRICAS_SLOTTABLE1      14620   //tricas_slotTable1.dff
#define OBJ_MAFIACASINOGLASS       14621   //mafiaCasinoGlass.dff
#define OBJ_AB_PILLARTEMP4         14622   //ab_pillarTemp4.dff
#define OBJ_MAFCASMAIN1            14623   //MafCasMain1.dff
#define OBJ_MAFCASMAIN2            14624   //MafCasMain2.dff
#define OBJ_MAFCASMAIN3            14625   //MafCasMain3.dff
#define OBJ_MAFCASSIGNS1           14626   //mafcasSigns1.dff
#define OBJ_MAFCAS_OPTILITE1       14627   //mafcas_optilite1.dff
#define OBJ_AB_CALIGULASFRONT      14628   //ab_caligulasfront.dff
#define OBJ_MAFCAS_CHANDE          14629   //mafcas_chande.dff
#define OBJ_MAFCAS_XITBOX          14630   //mafcas_Xitbox.dff
#define OBJ_PAPERCHASE_DAYLITE     14631   //paperchase_daylite.dff
#define OBJ_PAPERCHASE_BITS2B      14632   //paperchase_bits2b.dff
#define OBJ_PAPERCHASE_BITS2C      14633   //paperchase_bits2c.dff
#define OBJ_BIKESCHL_DAYLITE       14634   //bikeschl_daylite.dff
#define OBJ_MAFCASGENSTUFF         14635   //mafcasGenStuff.dff
#define OBJ_MAFCAS_SIGNS           14636   //mafcas_signs.dff
#define OBJ_TRIAD_DRAGON           14637   //triad_dragon.dff
#define OBJ_AB_MAFSUITEDOOR        14638   //ab_mafsuiteDoor.dff
#define OBJ_TR_MAN_MAIN            14639   //tr_man_main.dff
#define OBJ_CHINAFURN2             14640   //chinafurn2.dff
#define OBJ_TRI_MAIN_HOLES         14641   //tri_main_holes.dff
#define OBJ_MAFCAS_SPIRAL_DAD      14642   //mafcas_spiral_dad.dff
#define OBJ_TR_MAN_MAIN_TR         14643   //tr_man_main_tr.dff
