/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFxref.ide
#define OBJ_BULKHEADLIGHT          3785    //bulkheadlight.dff
#define OBJ_MISSILE_05_SFXR        3786    //missile_05_SFXR.dff
#define OBJ_MISSILE_02_SFXR        3787    //missile_02_SFXR.dff
#define OBJ_MISSILE_03_SFXR        3788    //missile_03_SFXR.dff
#define OBJ_MISSILE_09_SFXR        3789    //missile_09_SFXR.dff
#define OBJ_MISSILE_01_SFXR        3790    //missile_01_SFXR.dff
#define OBJ_MISSILE_10_SFXR        3791    //missile_10_SFXR.dff
#define OBJ_MISSILE_08_SFXR        3792    //missile_08_SFXR.dff
#define OBJ_MISSILE_06_SFXR        3793    //missile_06_SFXR.dff
#define OBJ_MISSILE_07_SFXR        3794    //missile_07_SFXR.dff
#define OBJ_MISSILE_04_SFXR        3795    //missile_04_SFXR.dff
#define OBJ_ACBOX1_SFS             3796    //acbox1_SFS.dff
#define OBJ_MISSILE_11_SFXR        3797    //missile_11_SFXR.dff
#define OBJ_ACBOX3_SFS             3798    //acbox3_SFS.dff
#define OBJ_ACBOX2_SFS             3799    //acbox2_SFS.dff
#define OBJ_ACBOX4_SFS             3800    //acbox4_SFS.dff
#define OBJ_SFX_LITE04             3801    //sfx_lite04.dff
#define OBJ_SFX_PLANT03            3802    //sfx_plant03.dff
#define OBJ_SFX_ALARMS03           3803    //sfx_alarms03.dff
#define OBJ_SFXREF_AIRCON11        3804    //sfxref_aircon11.dff
#define OBJ_SFXREF_AIRCON12        3805    //sfxref_aircon12.dff
#define OBJ_SFX_WINPLANT07         3806    //sfx_winplant07.dff
#define OBJ_SFX_FLAG02             3807    //sfx_flag02.dff
#define OBJ_SFX_ALARMS04           3808    //sfx_alarms04.dff
#define OBJ_SFX_LITE05             3809    //sfx_lite05.dff
#define OBJ_SFX_PLANT04            3810    //sfx_plant04.dff
#define OBJ_SFX_WINPLANT08         3811    //sfx_winplant08.dff
#define OBJ_SFXREF_AIRCON13        3812    //sfxref_aircon13.dff
#define OBJ_SFXREF_AIRCON14        3813    //sfxref_aircon14.dff
#define OBJ_HANGAR1_SFXREF         3814    //hangar1_SFXREF.dff
#define OBJ_BIGHANGAR1_SFX         3816    //bighangar1_SFx.dff
#define OBJ_SF_FRWAYSIG            3818    //sf_frwaysig.dff
#define OBJ_BLEACHER_SFSX          3819    //bleacher_SFSx.dff
#define OBJ_BOX_HSE_09_SFXRF       3820    //box_hse_09_SFXRF.dff
#define OBJ_BOX_HSE_02_SFXRF       3821    //box_hse_02_SFXRF.dff
#define OBJ_BOX_HSE_03_SFXRF       3822    //box_hse_03_SFXRF.dff
#define OBJ_BOX_HSE_11_SFXRF       3823    //box_hse_11_SFXRF.dff
#define OBJ_BOX_HSE_10_SFXRF       3824    //box_hse_10_SFXRF.dff
#define OBJ_BOX_HSE_01_SFXRF       3825    //box_hse_01_SFXRF.dff
#define OBJ_BOX_HSE_06_SFXRF       3826    //box_hse_06_SFXRF.dff
#define OBJ_BOX_HSE_07_SFXRF       3827    //box_hse_07_SFXRF.dff
#define OBJ_BOX_HSE_05_SFXRF       3828    //box_hse_05_SFXRF.dff
#define OBJ_BOX_HSE_04_SFXRF       3829    //box_hse_04_SFXRF.dff
#define OBJ_BOX_HSE_08_SFXRF       3830    //box_hse_08_SFXRF.dff
#define OBJ_BOX_HSE_14_SFXRF       3842    //box_hse_14_SFXRF.dff
#define OBJ_BOX_HSE_12_SFXRF       3843    //box_hse_12_SFXRF.dff
#define OBJ_BOX_HSE_15_SFXRF       3844    //box_hse_15_SFXRF.dff
#define OBJ_BOX_HSE_13_SFXRF       3845    //box_hse_13_SFXRF.dff
#define OBJ_CARSHOWBANN_SFSX       3850    //carshowbann_SFSX.dff
#define OBJ_CARSHOWWIN_SFSX        3851    //carshowwin_SFSX.dff
#define OBJ_SF_JUMP                3852    //sf_jump.dff
#define OBJ_GAY_LAMPPOST           3853    //Gay_lamppost.dff
#define OBJ_GAY_TELGRPHPOLE        3854    //GAY_telgrphpole.dff
#define OBJ_GAY_TRAFFIC_LIGHT      3855    //GAY_TRAFFIC_LIGHT.dff
#define OBJ_SF_FRWAYSIG_HALF       3856    //sf_frwaysig_half.dff
#define OBJ_OTTOSMASH3             3857    //ottosmash3.dff
#define OBJ_OTTOSMASH1             3858    //ottosmash1.dff
#define OBJ_OTTOSMASH04            3859    //ottosmash04.dff
#define OBJ_MARKETSTALL04_SFXRF    3860    //marketstall04_SFXRF.dff
#define OBJ_MARKETSTALL01_SFXRF    3861    //marketstall01_SFXRF.dff
#define OBJ_MARKETSTALL02_SFXRF    3862    //marketstall02_SFXRF.dff
#define OBJ_MARKETSTALL03_SFXRF    3863    //marketstall03_SFXRF.dff
#define OBJ_WS_FLOODLIGHT          3864    //WS_floodlight.dff
#define OBJ_CONCPIPE_SFXRF         3865    //concpipe_SFXRF.dff
#define OBJ_DEMOLISH1_SFXRF        3866    //demolish1_SFXRF.dff
#define OBJ_WS_SCAFFOLDING_SFX     3867    //ws_scaffolding_SFX.dff
#define OBJ_WS_FLOODBEAMS          3872    //WS_floodbeams.dff
#define OBJ_SILICON04_SFS          3873    //Silicon04_SFS.dff
#define OBJ_SFTELEPOLE             3875    //SFtelepole.dff
#define OBJ_SF_ROOFMAST            3876    //sf_roofmast.dff
#define OBJ_SF_ROOFLITE            3877    //sf_rooflite.dff
#define OBJ_HEADSTONES_SFSX        3878    //headstones_SFSx.dff
#define OBJ_WS_JETTY_SFX           3879    //ws_jetty_SFX.dff
#define OBJ_AIRSECBOOTH_SFSE       3881    //airsecbooth_SFSe.dff
#define OBJ_AIRSECBOOTHINT_SFSE    3882    //airsecboothint_SFSe.dff
#define OBJ_SAMSITE_SFXRF          3884    //samsite_SFXRF.dff
#define OBJ_SAMBASE_SFXRF          3885    //sambase_SFXRF.dff
#define OBJ_WS_JETTYNOL_SFX        3886    //ws_jettynol_SFX.dff
#define OBJ_DEMOLISH4_SFXRF        3887    //demolish4_SFXRF.dff
