/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//countn2.ide
#define OBJ_DRVIN_SCREEN           16000   //drvin_screen.dff
#define OBJ_DRVIN_PROJHUT          16001   //drvin_projhut.dff
#define OBJ_DRVIN_SIGN             16002   //drvin_sign.dff
#define OBJ_DRVIN_TICKET           16003   //drvin_ticket.dff
#define OBJ_DES_TEPEOFF            16004   //des_tepeoff.dff
#define OBJ_DESN2_STWNBLOK2        16005   //desn2_stwnblok2.dff
#define OBJ_ROS_TOWNHALL           16006   //ros_townhall.dff
#define OBJ_DESN2_CN2BLOK1         16007   //desn2_cn2blok1.dff
#define OBJ_DES_NBRSTRUCT          16008   //des_nbrstruct.dff
#define OBJ_DES_NBRSTRUCT2         16009   //des_nbrstruct2.dff
#define OBJ_DES_RESLAB             16010   //des_reslab_.dff
#define OBJ_DES_WESTRN2            16011   //des_westrn2_.dff
#define OBJ_DES_NTCAFE             16012   //des_ntcafe.dff
#define OBJ_DES_NTWN_LINES1        16013   //des_ntwn_lines1_.dff
#define OBJ_DES_NTWN_LINES2        16014   //des_ntwn_lines2_.dff
#define OBJ_DES_NTWN_LINES6        16015   //des_ntwn_lines6_.dff
#define OBJ_DES_ROADBAR01          16016   //des_roadbar01.dff
#define OBJ_DES_ROADBAR02          16017   //des_roadbar02.dff
#define OBJ_DES_ROADBAR03          16018   //des_roadbar03.dff
#define OBJ_DES_ROADBAR04          16019   //des_roadbar04.dff
#define OBJ_DES_ROADBAR05          16020   //des_roadbar05.dff
#define OBJ_DES_GEYHOTBASE         16021   //des_geyhotbase_.dff
#define OBJ_DES_GEYWALL1           16022   //des_geywall1.dff
#define OBJ_DES_TRXINGSIGN02       16023   //des_trXingsign02.dff
#define OBJ_DES_LTRAINTUNNEL2      16024   //des_ltraintunnel2.dff
#define OBJ_DES_TRAINLINE06        16025   //des_trainline06.dff
#define OBJ_DES_TRAINLINE07        16026   //des_trainline07.dff
#define OBJ_DES_TRAINLINE08        16027   //des_trainline08.dff
#define OBJ_DES_TRAINLINE09        16028   //des_trainline09.dff
#define OBJ_DES_TRAINLINE11        16029   //des_trainline11.dff
#define OBJ_DES_TRAINLINE12        16030   //des_trainline12.dff
#define OBJ_DES_TRAINLINE13        16031   //des_trainline13.dff
#define OBJ_DES_TRAINLINE14        16032   //des_trainline14.dff
#define OBJ_DES_TRAINLINE15        16033   //des_trainline15.dff
#define OBJ_DES_TRAINLINE16        16034   //des_trainline16.dff
#define OBJ_DES_TRAINLINE10        16035   //des_trainline10.dff
#define OBJ_DES_TRAINLINE17        16036   //des_trainline17.dff
#define OBJ_DES_RAILBR_TWR10       16037   //des_railbr_twr10.dff
#define OBJ_DES_POWERCABLE_01      16038   //des_powercable_01.dff
#define OBJ_DES_POWERCABLE_03      16039   //des_powercable_03.dff
#define OBJ_DES_POWERCABLE_04      16040   //des_powercable_04.dff
#define OBJ_DES_POWERCABLE_07      16041   //des_powercable_07.dff
#define OBJ_DES_POWERCABLE_08      16042   //des_powercable_08.dff
#define OBJ_DES_POWERCABLE_09      16043   //des_powercable_09.dff
#define OBJ_DES_POWERCABLE_10      16044   //des_powercable_10.dff
#define OBJ_DES_POWERCABLE_11      16045   //des_powercable_11.dff
#define OBJ_DES_POWERCABLE_12      16046   //des_powercable_12.dff
#define OBJ_DES_POWERCABLE_19      16047   //des_powercable_19.dff
#define OBJ_DES_POWERCABLE_20      16048   //des_powercable_20.dff
#define OBJ_DES_POWERCABLE_21      16049   //des_powercable_21.dff
#define OBJ_DES_POWERCABLE_22      16050   //des_powercable_22.dff
#define OBJ_DES_WESTSALOON_01      16051   //des_westsaloon_01.dff
#define OBJ_DES_GHOTFENCE          16052   //des_ghotfence.dff
#define OBJ_DES_WESTRN7_01         16053   //des_westrn7_01.dff
#define OBJ_DES_WESTRN9_01         16054   //des_westrn9_01.dff
#define OBJ_QUARRY_BIT04           16055   //quarry_bit04.dff
#define OBJ_QUARRY_BIT02           16056   //quarry_bit02.dff
#define OBJ_QUARRY_BIT01           16057   //quarry_bit01.dff
#define OBJ_QUARRY_BIT05           16058   //quarry_bit05.dff
#define OBJ_QUARRY_BIT03           16059   //quarry_bit03.dff
#define OBJ_DES_TREELINE1          16060   //des_treeline1.dff
#define OBJ_DES_TREELINE2          16061   //des_treeline2.dff
#define OBJ_DES_NT_BUNTPOLES       16062   //des_nt_buntpoles.dff
#define OBJ_DES_COCKBUNTING        16063   //des_cockbunting.dff
#define OBJ_DES_CN2BLOK4           16064   //des_cn2blok4.dff
#define OBJ_DES_STWNSHOP01         16065   //des_stwnshop01.dff
#define OBJ_DES_BLUECAFE01         16066   //des_bluecafe01.dff
#define OBJ_DES_STWNMOTEL02        16067   //des_stwnmotel02.dff
#define OBJ_DES_STIPBLOCK1         16068   //des_stripblock1.dff
#define OBJ_DES_STWNYELMOT1        16069   //des_stwnyelmot1_.dff
#define OBJ_DES_STWNHOTEL1         16070   //des_stwnhotel1.dff
#define OBJ_DES_QUARRYBELT02       16071   //des_quarrybelt02.dff
#define OBJ_DES_QUARRYBELT01       16072   //des_quarrybelt01.dff
#define OBJ_DES_QUARRYBELT03       16073   //des_quarrybelt03.dff
#define OBJ_DES_QUARRYBELT04       16074   //des_quarrybelt04.dff
#define OBJ_DES_QUARRYBELT07       16075   //des_quarrybelt07.dff
#define OBJ_DES_SORTER01           16076   //des_sorter01.dff
#define OBJ_DES_GRAVELPILE01       16077   //des_gravelpile01.dff
#define OBJ_DES_QUARRYBELT08       16078   //des_quarrybelt08.dff
#define OBJ_DES_QUARRYBELT09       16079   //des_quarrybelt09.dff
#define OBJ_DES_BIGQUARYCONV01     16080   //des_bigquaryconv01.dff
#define OBJ_DES_BIGQUARYCONV02     16081   //des_bigquaryconv02.dff
#define OBJ_DES_QUARRYPLATFORM     16082   //des_quarryplatform.dff
#define OBJ_DES_QUARRY_HOPPER01    16083   //des_quarry_hopper01.dff
#define OBJ_DES_QUARRYRAMP         16084   //des_quarryramp.dff
#define OBJ_DES_QUARSTMOUND_02     16085   //des_quarstmound_02.dff
#define OBJ_DES_BIGOILPIPE01       16086   //des_bigoilpipe01.dff
#define OBJ_DES_OILFIELDPIPE01     16087   //des_oilfieldpipe01.dff
#define OBJ_DES_PIPESTRUT01        16088   //des_pipestrut01.dff
#define OBJ_DES_PIPESTRUT02        16089   //des_pipestrut02.dff
#define OBJ_DES_PIPESTRUT03        16090   //des_pipestrut03.dff
#define OBJ_DES_PIPESTRUT04        16091   //des_pipestrut04.dff
#define OBJ_DES_PIPESTRUT05        16092   //des_pipestrut05.dff
#define OBJ_A51_GATECONTROL        16093   //a51_gatecontrol.dff
#define OBJ_DES_A51INFENC          16094   //des_a51infenc.dff
#define OBJ_DES_A51GUARDBOX02      16095   //des_a51guardbox02.dff
#define OBJ_DES_A51GUARDBOX04      16096   //des_a51guardbox04.dff
