/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//barriers.ide
#define OBJ_BAR_GATEBAR01          966     //bar_gatebar01.dff
#define OBJ_BAR_GATEBOX01          967     //bar_gatebox01.dff
#define OBJ_BARRIERTURN            968     //barrierturn.dff
#define OBJ_ELECTRICGATE           969     //Electricgate.dff
#define OBJ_FENCESMALLB            970     //fencesmallb.dff
#define OBJ_SUBWAYGATE             971     //subwaygate.dff
#define OBJ_TUNNELENTRANCE         972     //tunnelentrance.dff
#define OBJ_SUB_ROADBARRIER        973     //sub_roadbarrier.dff
#define OBJ_TALL_FENCE             974     //tall_fence.dff
#define OBJ_COLUMBIANGATE          975     //Columbiangate.dff
#define OBJ_PHILS_COMPND_GATE      976     //phils_compnd_gate.dff
#define OBJ_NEWTOWERDOOR1          977     //newtowerdoor1.dff
#define OBJ_SUB_ROADRIGHT          978     //sub_roadright.dff
#define OBJ_SUB_ROADLEFT           979     //sub_roadleft.dff
#define OBJ_AIRPORTGATE            980     //airportgate.dff
#define OBJ_HELIX_BARRIER          981     //helix_barrier.dff
#define OBJ_FENCESHIT              982     //fenceshit.dff
#define OBJ_FENCESHIT3             983     //fenceshit3.dff
#define OBJ_FENCESHIT2             984     //fenceshit2.dff
#define OBJ_GATE_AUTOR             985     //gate_autoR.dff
#define OBJ_GATE_AUTOL             986     //gate_autoL.dff
#define OBJ_ELECFENCE_BAR          987     //elecfence_BAR.dff
#define OBJ_WS_APGATE              988     //ws_apgate.dff
#define OBJ_AC_APGATE              989     //ac_apgate.dff
#define OBJ_BAR_BARRIER12          990     //bar_barrier12.dff
#define OBJ_BAR_BARRIERGATE1       991     //bar_barriergate1.dff
#define OBJ_BAR_BARRIER10B         992     //bar_barrier10b.dff
#define OBJ_BAR_BARRIER10          993     //bar_barrier10.dff
#define OBJ_LHOUSE_BARRIER2        994     //lhouse_barrier2.dff
#define OBJ_BAR_BARRIER16          995     //bar_barrier16.dff
#define OBJ_LHOUSE_BARRIER1        996     //lhouse_barrier1.dff
#define OBJ_LHOUSE_BARRIER3        997     //lhouse_barrier3.dff
#define OBJ_GDYN_BARRIER17         998     //Gdyn_barrier17.dff