/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LaWn.ide
#define OBJ_ROAD_LAWN23            5703    //road_lawn23.dff
#define OBJ_ARCHWINDSHOP_LAW       5704    //archwindshop_laW.dff
#define OBJ_FILMSTUD1              5705    //filmstud1.dff
#define OBJ_STUDIOBLD03_LAW        5706    //studiobld03_laW.dff
#define OBJ_ROAD_LAWN03            5707    //road_lawn03.dff
#define OBJ_HOSPITAL_LAW           5708    //hospital_law.dff
#define OBJ_SHOP03_LAW01           5709    //shop03_laW01.dff
#define OBJ_CEM01_LAW              5710    //cem01_law.dff
#define OBJ_CEM02_LAW              5711    //cem02_law.dff
#define OBJ_CEMINT01_LAW           5712    //cemint01_law.dff
#define OBJ_GRAVE01_LAW            5713    //grave01_law.dff
#define OBJ_GRAVE03_LAW            5714    //grave03_law.dff
#define OBJ_GRAVE08_LAW            5715    //grave08_law.dff
