/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//gen_intb.ide
#define OBJ_CRACKHOOSE             14735   //crackhoose.dff
#define OBJ_AH_CHILLER2            14736   //AH_chiller2.dff
#define OBJ_WHOREPIX               14737   //whorepix.dff
#define OBJ_BROTHELBAR             14738   //brothelbar.dff
#define OBJ_WHOREFURN              14739   //whorefurn.dff
#define OBJ_RYBLINDS               14740   //ryblinds.dff
#define OBJ_RYKITUNIT              14741   //rykitunit.dff
#define OBJ_RYDERS_WALL_STUF       14742   //ryders_wall_stuf.dff
#define OBJ_RYDHALL                14743   //rydhall.dff
#define OBJ_RYBATHROOM             14744   //rybathroom.dff
#define OBJ_RYBATHARSE01           14745   //rybatharse01.dff
#define OBJ_RYLOUNGE               14746   //rylounge.dff
#define OBJ_CURSES04               14747   //curses04.dff
#define OBJ_SFHSM1                 14748   //sfhsm1.dff
#define OBJ_SFHSM1LIGHTS           14749   //sfhsm1lights.dff
#define OBJ_SFHSM2                 14750   //sfhsm2.dff
#define OBJ_SFHSM2BITS             14751   //sfhsm2bits.dff
#define OBJ_CURSES02               14752   //curses02.dff
#define OBJ_SFHSB2CURTS            14753   //sfhsb2curts.dff
#define OBJ_BIGSANFRANHOOSE        14754   //bigsanfranhoose.dff
#define OBJ_SHITE                  14755   //shite.dff
#define OBJ_SHITLOBBY              14756   //shitlobby.dff
#define OBJ_SFMANSIONBITS          14757   //sfmansionbits.dff
#define OBJ_SFMANSION1             14758   //sfmansion1.dff
#define OBJ_SFHSM03                14759   //sfhsm03.dff
#define OBJ_OBJECT03               14760   //Object03.dff
#define OBJ_RYSHADROOM             14761   //ryshadroom.dff
#define OBJ_ARSEWINOWS             14762   //arsewinows.dff
#define OBJ_SWEETSDAYLIGHT02       14763   //sweetsdaylight02.dff
#define OBJ_BALLUSTRADES           14764   //ballustrades.dff
