/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//countrye.ide
#define OBJ_CUNTE_ROADS01          12800   //cunte_roads01.dff
#define OBJ_CUNTE_ROADS03          12801   //cunte_roads03.dff
#define OBJ_CUNTE_ROADS04          12802   //cunte_roads04.dff
#define OBJ_CUNTE_ROADS06          12803   //cunte_roads06.dff
#define OBJ_CUNTEGROUND01          12804   //cuntEground01.dff
#define OBJ_CE_BIGSHED1            12805   //CE_bigshed1.dff
