/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//countrye.ide
#define OBJ_CUNTE_ROADS01          12800   //cunte_roads01.dff
#define OBJ_CUNTE_ROADS03          12801   //cunte_roads03.dff
#define OBJ_CUNTE_ROADS04          12802   //cunte_roads04.dff
#define OBJ_CUNTE_ROADS06          12803   //cunte_roads06.dff
#define OBJ_CUNTEGROUND01          12804   //cuntEground01.dff
#define OBJ_CE_BIGSHED1            12805   //CE_bigshed1.dff
#define OBJ_CUNTE_ROADS08          12806   //cunte_roads08.dff
#define OBJ_SW_LOGS4               12807   //sw_logs4.dff
#define OBJ_SW_LOGS3               12808   //sw_logs3.dff
#define OBJ_CUNTE_ROADS11          12809   //cunte_roads11.dff
#define OBJ_CUNTE_ROADS12          12810   //cunte_roads12.dff
#define OBJ_CUNTE_ROADS13          12811   //cunte_roads13.dff
#define OBJ_CUNTE_ROADS14          12812   //cunte_roads14.dff
#define OBJ_CUNTE_ROADS15          12813   //cunte_roads15.dff
#define OBJ_CUNTYELAND04           12814   //cuntyeland04.dff
#define OBJ_CUNTE_ROADS16          12815   //cunte_roads16.dff
#define OBJ_CUNTE_ROADS17          12816   //cunte_roads17.dff
#define OBJ_CUNTE_ROADS19          12817   //cunte_roads19.dff
#define OBJ_CUNTE_ROADS20          12818   //cunte_roads20.dff
#define OBJ_CUNTE_ROADS21          12819   //cunte_roads21.dff
#define OBJ_CUNTE_ROADS22          12820   //cunte_roads22.dff
#define OBJ_CRATESINALLEY          12821   //cratesinalley.dff
#define OBJ_SMALLTWNBLD05          12822   //smalltwnbld05.dff
#define OBJ_CUNTEGROUND02          12823   //cuntEground02.dff
#define OBJ_CEGROUNDTP104          12824   //CEgroundTP104.dff
#define OBJ_CUNTEGROUND08          12825   //cuntEground08.dff
#define OBJ_CUNTE_ROADS23          12826   //cunte_roads23.dff
#define OBJ_CUNTE_ROADS24          12827   //cunte_roads24.dff
#define OBJ_CUNTE_ROADS25          12828   //cunte_roads25.dff
#define OBJ_CUNTE_ROADS26          12829   //cunte_roads26.dff
#define OBJ_CUNTE_ROADS27          12830   //cunte_roads27.dff
#define OBJ_COE_TRAINTRAX_10       12831   //coe_traintrax_10.dff
#define OBJ_COE_TRAINTRAX_03       12832   //coe_traintrax_03.dff
#define OBJ_COE_TRAINTRAX_04       12833   //coe_traintrax_04.dff
#define OBJ_COE_TRAINTRAX_06       12835   //coe_traintrax_06.dff
#define OBJ_COE_TRAINTRAX_07       12836   //coe_traintrax_07.dff
#define OBJ_COE_TRAINTRAX_08       12837   //coe_traintrax_08.dff
#define OBJ_COE_TRAINTRAX_09       12838   //coe_traintrax_09.dff
#define OBJ_COS_SBANKSTEPS02       12839   //cos_sbanksteps02.dff
#define OBJ_COS_PIZSKYGLAS01       12840   //cos_pizskyglas01.dff
#define OBJ_COS_PIZINTERIOR        12841   //cos_pizinterior.dff
#define OBJ_COS_PIZSEATS           12842   //cos_pizseats.dff
#define OBJ_COS_LIQUORSHOP         12843   //cos_liquorshop.dff
#define OBJ_COS_LIQINSIDE          12844   //cos_liqinside.dff
#define OBJ_COS_LIQINSIDEBITS      12845   //cos_liqinsidebits.dff
#define OBJ_OTB_SIGN               12846   //otb_sign.dff
#define OBJ_SPRUNK_FACT            12847   //sprunk_fact.dff
#define OBJ_COE_SPRUNLKFENC        12848   //coe_sprunlkfenc.dff
#define OBJ_CORNERSTORE_01         12849   //CornerStore_01.dff
#define OBJ_SW_BLOCK01             12850   //sw_block01.dff
#define OBJ_CUNTE_ROADS29          12851   //cunte_roads29.dff
#define OBJ_CUNTE_ROADS30          12852   //cunte_roads30.dff
#define OBJ_SW_GAS01               12853   //sw_gas01.dff
#define OBJ_SW_GAS01INT            12854   //sw_gas01int.dff
#define OBJ_SW_COPSHOP             12855   //sw_copshop.dff
#define OBJ_SW_BRIDGE              12856   //sw_bridge.dff
#define OBJ_CE_BRIDGE02            12857   //CE_bridge02.dff
#define OBJ_SW_GATE1               12858   //sw_gate1.dff
#define OBJ_SW_CONT03              12859   //sw_cont03.dff
#define OBJ_SW_CONT04              12860   //sw_cont04.dff
#define OBJ_SW_CONT05              12861   //sw_cont05.dff
#define OBJ_SW_BLOCK03             12862   //sw_block03.dff
