/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAs.ide
#define OBJ_BTOLAND8_LAS           4806    //BTOLAND8_LAS.dff
#define OBJ_LAROADS_20GH_LAS       4807    //LAroads_20gh_LAs.dff
#define OBJ_LAROADSS_30_LAS        4808    //LAroadss_30_LAs.dff
#define OBJ_LAROADS_05_LAS         4809    //LAroads_05_LAs.dff
#define OBJ_HILLPALOS04_LAS        4810    //hillpalos04_LAs.dff
#define OBJ_CLIFFTEST02            4811    //clifftest02.dff
#define OBJ_CLIFFTEST05            4812    //clifftest05.dff
#define OBJ_CLIFFTEST07            4813    //clifftest07.dff
#define OBJ_CLIFFTEST09            4814    //clifftest09.dff
#define OBJ_CLIFFTESTGRND2         4815    //clifftestgrnd2.dff
#define OBJ_ROCKLIFF1_LAS          4816    //ROCKLIFF1_LAS.dff
#define OBJ_TRNTRK7_LAS            4817    //TRNTRK7_LAS.dff
#define OBJ_TRNTRK8_LAS            4818    //TRNTRK8_LAS.dff
#define OBJ_TRNTRK5_LAS            4819    //TRNTRK5_LAS.dff
#define OBJ_BTOLAND1_LAS           4820    //BTOLAND1_LAS.dff
#define OBJ_BTOLAND2_LAS           4821    //BTOLAND2_LAS.dff
#define OBJ_NWCSTRD1_LAS           4822    //NWCSTRD1_LAS.dff
#define OBJ_LASGRIFROAD            4823    //lasgrifroad.dff
#define OBJ_LASGRIFSTEPS2          4824    //lasgrifsteps2.dff
#define OBJ_GRIFFITHOBLAS          4825    //griffithoblas.dff
#define OBJ_GRIFFTOP2              4826    //grifftop2.dff
#define OBJ_LAROADS_20GHI_LAS      4827    //LAroads_20ghi_LAs.dff
#define OBJ_LSAIRPRT5              4828    //lasairprt5.dff
#define OBJ_LSAIRPRT4              4829    //lasairprt4.dff
#define OBJ_LSAIRPRT3              4830    //lasairprt3.dff
#define OBJ_AIRPURT2_LAS           4831    //airpurt2_las.dff
#define OBJ_AIRTWER_LAS            4832    //airtwer_Las.dff
#define OBJ_AIRPURTDER_LAS         4833    //airpurtder_las.dff
#define OBJ_AIRROAD1D_LAS          4834    //airoad1d_LAS.dff
#define OBJ_AIRROAD1B_LAS          4835    //airoad1b_LAS.dff
#define OBJ_LAROADSX_04_LAS        4836    //LAroadsx_04_LAs.dff
#define OBJ_LAPEDHUSREA_LAS        4837    //LApedhusrea_LAs.dff
#define OBJ_AIRPURTDERFR_LAS       4838    //airpurtderfr_las.dff
#define OBJ_BCHCOSTRD3_LAS         4839    //bchcostrd3_LAS.dff
#define OBJ_BCHCOSTRD4_LAS         4840    //bchcostrd4_LAS.dff
#define OBJ_BCHCOSTRD1_LAS         4841    //bchcostrd1_LAS.dff
#define OBJ_BEACH1_LAS0FG          4842    //Beach1_LAs0fg.dff
#define OBJ_BEACH1_LAS0FHY         4843    //Beach1_LAs0fhy.dff
#define OBJ_BEACH1_LAS04           4844    //Beach1_LAs04.dff
#define OBJ_HILLPALOS02_LAS        4845    //hillpalos02_LAs.dff
#define OBJ_LACITYPED1_LAS         4846    //LAcityped1_LAs.dff
#define OBJ_BEACH1_LAS0GJ          4847    //Beach1_LAs0gj.dff
#define OBJ_SANPEDBEAUT            4848    //sanpedbeaut.dff
#define OBJ_SNPDMSHFNC3_LAS        4849    //snpdmshfnc3_LAS.dff
#define OBJ_SNPEDSHPBLK07          4850    //snpedshpblk07.dff
#define OBJ_HILLPALOS01_LAS        4851    //hillpalos01_LAs.dff
#define OBJ_HILLPALOS03_LAS        4852    //hillpalos03_LAs.dff
#define OBJ_TRAINCANO_LAS          4853    //traincano_LAS.dff
#define OBJ_LASUNDRAIRPRT2         4854    //lasundrairprt2.dff
#define OBJ_LASUNDRAIRPRT1         4855    //lasundrairprt1.dff
#define OBJ_LASUNDRAIRPRT3         4856    //lasundrairprt3.dff
#define OBJ_SNPEDMTSP1_LAS         4857    //snpedmtsp1_LAS.dff
#define OBJ_SNPEDLAND1_LAS         4858    //snpedland1_LAS.dff
#define OBJ_SNPEDLAND2_LAS         4859    //snpedland2_LAS.dff
#define OBJ_UNIONSTWAR_LAS         4860    //unionstwar_LAS.dff
#define OBJ_SNPEDHUAIR2_LAS        4861    //snpedhuair2_LAS.dff
#define OBJ_AIRTUN2_LAS            4862    //airtun2_LAS.dff
#define OBJ_AIRTUN1_LAS            4863    //airtun1_LAS.dff
#define OBJ_AIRTUN3_LAS            4864    //airtun3_LAS.dff
#define OBJ_LASRNWAY2_LAS          4865    //lasrnway2_LAS.dff
#define OBJ_LASRNWAY1_LAS          4866    //lasrnway1_LAS.dff
#define OBJ_LASRNWAY3_LAS          4867    //lasrnway3_LAS.dff
#define OBJ_LAROADS_23_LAS         4868    //LAroads_23_LAs.dff
#define OBJ_LASRNWAY8_LAS          4869    //lasrnway8_LAS.dff
#define OBJ_AIRPURT2AX_LAS         4870    //airpurt2ax_las.dff
#define OBJ_AIRPURT2BX_LAS         4871    //airpurt2bx_las.dff
#define OBJ_LAROADS042E_LAS        4872    //LAroads_042e_LAs.dff
#define OBJ_UNIONSTWARC2_LAS       4873    //unionstwarc2_LAS.dff
#define OBJ_HELIPAD1_LAS           4874    //Helipad1_las.dff
