/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//gen_int2.ide
#define OBJ_INT2SMSF01_INT01       14700   //int2smSf01_int01.dff
#define OBJ_INT2HOOSE2             14701   //int2Hoose2.dff
#define OBJ_INT2LAMID01            14702   //int2lamid01.dff
#define OBJ_INT2HOOSE09            14703   //int2Hoose09.dff
#define OBJ_INT2HOOSE2_BITS        14704   //int2Hoose2_bits.dff
#define OBJ_INT2VASE               14705   //int2Vase.dff
#define OBJ_INT2LABIGTWO01         14706   //int2labigtwo01.dff
#define OBJ_INT2LABIG301           14707   //int2labig301.dff
#define OBJ_INT2LABIGONE01         14708   //int2labigone01.dff
#define OBJ_INT2LAMIDTWO01         14709   //int2lamidtwo01.dff
#define OBJ_INT2VGSHM3             14710   //int2vgshM3.dff
#define OBJ_INT2VGSHM2             14711   //int2vgshM2.dff
#define OBJ_INT2HOOSE11            14712   //int2Hoose11.dff
#define OBJ_INT2HOOSE16            14713   //int2Hoose16.dff
#define OBJ_INT2HOOSE08            14714   //int2Hoose08.dff
#define OBJ_INT2HOOSE09_BITS       14715   //int2Hoose09_Bits.dff
#define OBJ_INT2LAMID01_RAIL       14716   //int2lamid01_rail.dff
#define OBJ_INT2LASMTWO02          14717   //int2lasmtwo02.dff
#define OBJ_INT2LASMONE04          14718   //int2lasmone04.dff
#define OBJ_INT2LASMONE01          14719   //int2lasmone01.dff
#define OBJ_INT2LASMONE02          14720   //int2lasmone02.dff
#define OBJ_2LABIGONE_BITS         14721   //2labigone_bits.dff
#define OBJ_INT2HOOSE09_BITS2      14722   //int2Hoose09_Bits2.dff
#define OBJ_INT2HOOSE09_BITS3      14723   //int2Hoose09_Bits3.dff
#define OBJ_INT2HOOSE09_BITS4      14724   //int2Hoose09_Bits4.dff
#define OBJ_INT2LAMID01_RAIL2      14725   //int2lamid01_rail2.dff
#define OBJ_INT2LAMID01_RAIL3      14726   //int2lamid01_rail3.dff
#define OBJ_INT2LAMID01_RAIL4      14727   //int2lamid01_rail4.dff
#define OBJ_INT2LABIG302           14728   //int2labig302.dff
