/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFxref.ide
#define OBJ_BULKHEADLIGHT          3785    //bulkheadlight.dff
#define OBJ_MISSILE_05_SFXR        3786    //missile_05_SFXR.dff
#define OBJ_MISSILE_02_SFXR        3787    //missile_02_SFXR.dff
#define OBJ_MISSILE_03_SFXR        3788    //missile_03_SFXR.dff
#define OBJ_MISSILE_09_SFXR        3789    //missile_09_SFXR.dff
#define OBJ_MISSILE_01_SFXR        3790    //missile_01_SFXR.dff
#define OBJ_MISSILE_10_SFXR        3791    //missile_10_SFXR.dff
#define OBJ_MISSILE_08_SFXR        3792    //missile_08_SFXR.dff
#define OBJ_MISSILE_06_SFXR        3793    //missile_06_SFXR.dff
#define OBJ_MISSILE_07_SFXR        3794    //missile_07_SFXR.dff
#define OBJ_MISSILE_04_SFXR        3795    //missile_04_SFXR.dff
#define OBJ_ACBOX1_SFS             3796    //acbox1_SFS.dff
#define OBJ_MISSILE_11_SFXR        3797    //missile_11_SFXR.dff
#define OBJ_ACBOX3_SFS             3798    //acbox3_SFS.dff
#define OBJ_ACBOX2_SFS             3799    //acbox2_SFS.dff
#define OBJ_ACBOX4_SFS             3800    //acbox4_SFS.dff
#define OBJ_SFX_LITE04             3801    //sfx_lite04.dff
