/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAw.ide
#define OBJ_LAWROADS_LAW12         6035    //lawroads_law12.dff
#define OBJ_FILLER01_LAW           6036    //filler01_laW.dff
#define OBJ_FILLER02_LAW           6037    //filler02_laW.dff
#define OBJ_WILSHIRE2_LAW          6038    //wilshire2_law.dff
#define OBJ_WILSHIRE5_LAW          6039    //wilshire5_law.dff
#define OBJ_WILSHIRE7_LAW          6040    //wilshire7_law.dff
#define OBJ_WILSHIRE6_LAW          6041    //wilshire6_law.dff
#define OBJ_VENBLUE01_LAW          6042    //venblue01_law.dff
#define OBJ_WILSHIRE2W_LAW         6044    //wilshire2w_law.dff
#define OBJ_WILSHIRE5W_LAW         6045    //wilshire5w_law.dff
#define OBJ_HEDGE01_LAW            6046    //hedge01_law.dff
#define OBJ_WILSHIRE1_LAW          6047    //wilshire1_law.dff
