/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFe.ide
#define OBJ_LANDSHIT_09_SFE        9900    //landshit_09_sfe.dff
#define OBJ_FERYBUILD_1            9901    //ferybuild_1.dff
#define OBJ_FERRYLAND3             9902    //ferryland3.dff
#define OBJ_PIER69_MODELS07        9903    //pier69_models07.dff
#define OBJ_PIER69_MODELS04        9904    //pier69_models04.dff
#define OBJ_PIER69_MODELS06        9905    //pier69_models06.dff
#define OBJ_TEMPSF_2_SFE           9906    //tempsf_2_sfe.dff
#define OBJ_MONOLITH_SFE           9907    //monolith_sfe.dff
#define OBJ_ANOTHERBUILD091        9908    //anotherbuild091.dff
#define OBJ_VICSTUFF_SFE33         9909    //vicstuff_sfe33.dff
#define OBJ_FISHWARF01             9910    //fishwarf01.dff
#define OBJ_FISHWARF06             9911    //fishwarf06.dff
#define OBJ_FISHWARF03             9912    //fishwarf03.dff
#define OBJ_FISHWARF04             9913    //fishwarf04.dff
#define OBJ_FISHWARF05             9914    //fishwarf05.dff
#define OBJ_SFE_PARK               9915    //sfe_park.dff
#define OBJ_JUMPBUILD_SFE          9916    //jumpbuild_sfe.dff
#define OBJ_YET_ANOTHER_SFE        9917    //yet_another_sfe.dff
#define OBJ_POSH2_SFE              9918    //posh2_sfe.dff
#define OBJ_GRNWHITE_SFE           9919    //grnwhite_sfe.dff
#define OBJ_VICSTUFF_SFE6000       9920    //vicstuff_sfe6000.dff
#define OBJ_FERRYSHOPS1            9921    //ferryshops1.dff
#define OBJ_FERRYSHOPS2            9922    //ferryshops2.dff
#define OBJ_FERRYSHOPS3            9923    //ferryshops3.dff
#define OBJ_FERRYSHOPS4            9924    //ferryshops4.dff
#define OBJ_FERRYSHOPS5            9925    //ferryshops5.dff
#define OBJ_FERRYSHOPS07           9926    //ferryshops07.dff
#define OBJ_SFE_REDWHT2            9927    //sfe_redwht2.dff
#define OBJ_FERRYSHOPS08           9928    //ferryshops08.dff
#define OBJ_BORING_SFE             9929    //boring_sfe.dff
