/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//vegaxref.ide
#define OBJ_VEGASBOOTH01           3430    //vegasbooth01.dff
#define OBJ_VGSCLUBBOX01           3431    //vgsclubox01.dff
#define OBJ_HTLCNPY02_LVS          3432    //htlcnpy02_lvs.dff
#define OBJ_HTLCNPY01_LVS          3433    //htlcnpy01_lvs.dff
#define OBJ_SKLLSGN01_LVS          3434    //skllsgn01_lvs.dff
