/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//props2.ide
#define OBJ_CJ_ICE_FRIDGE_2        2360    //CJ_ICE_FRIDGE_2.dff
#define OBJ_CJ_ICE_FRIDGE_1        2361    //CJ_ICE_FRIDGE_1.dff
#define OBJ_SWEETIE_TRAY_1         2362    //CJ_SWEETIE_TRAY_1.dff
#define OBJ_CJ_SHOP_SIGN_1         2363    //CJ_SHOP_SIGN_1.dff
#define OBJ_CJ_SHOP_SIGN_2         2364    //CJ_SHOP_SIGN_2.dff
#define OBJ_SHOPPING_BASKET        2365    //SHOPPING_BASKET.dff
#define OBJ_CJ_DUDS_RAIL           2366    //CJ_DUDS_RAIL.dff
#define OBJ_SHOP_COUNTER_2         2367    //Shop_counter_2.dff
#define OBJ_SHOP_COUNTER_1         2368    //Shop_counter_1.dff
#define OBJ_CJ_TILL                2369    //CJ_Till.dff
#define OBJ_SHOP_SET_1_TABLE       2370    //Shop_set_1_Table.dff
#define OBJ_CLOTHES_RAIL           2371    //CLOTHES_RAIL.dff
#define OBJ_CLOTHES_RAIL2          2372    //CLOTHES_RAIL2.dff
#define OBJ_CLOTHES_RAIL3          2373    //CLOTHES_RAIL3.dff
#define OBJ_CJ_TSHIRT              2374    //CJ_Tshirt.dff
#define OBJ_SHOP_SET_2_UNIT1       2375    //Shop_set_2_Unit1.dff
#define OBJ_SHOP_SET_2_UNIT2       2376    //Shop_set_2_Unit2.dff
#define OBJ_CJ_JEAN_DARK           2377    //CJ_jean_dark.dff
#define OBJ_CJ_JEAN_LIGHT          2378    //CJ_jean_light.dff
#define OBJ_SHOP_SET_2_UNIT3       2379    //Shop_set_2_Unit3.dff
#define OBJ_CJ_SUITS               2380    //CJ_Suits.dff
#define OBJ_CJ_8_SWEATER           2381    //CJ_8_SWEATER.dff
#define OBJ_CJ_8_JEANS_LIGHT       2382    //CJ_8_JEANS_Light.dff
#define OBJ_CJ_6_SWEATER           2383    //CJ_6_SWEATER.dff
#define OBJ_CJ_8_JEANS_DARK        2384    //CJ_8_JEANS_DARK.dff
#define OBJ_SHOP_SET_2_UNIT4       2385    //Shop_set_2_Unit4.dff
#define OBJ_CJ_SWEATER_F_1         2386    //CJ_SWEATER_F_1.dff
#define OBJ_SHOP_SET_2_UNIT5       2387    //Shop_set_2_Unit5.dff
#define OBJ_CJ_DUDS_RAIL_2         2388    //CJ_DUDS_RAIL_2.dff
#define OBJ_CJ_4_SWEATERS          2389    //CJ_4_SWEATERS.dff
#define OBJ_CJ_4WAY_CLOTHES        2390    //CJ_4way_clothes.dff
#define OBJ_CJ_JEAN_CREAM          2391    //CJ_jean_CREAM.dff
#define OBJ_CJ_8_JEANS_MED         2392    //CJ_8_JEANS_MED.dff
#define OBJ_CJ_DUDS_RAIL_3         2393    //CJ_DUDS_RAIL_3.dff
#define OBJ_CJ_CLOTHES_STEP_1      2394    //CJ_CLOTHES_STEP_1.dff
#define OBJ_CJ_SPORTS_WALL         2395    //CJ_SPORTS_WALL.dff
#define OBJ_CJ_4_S_SWEATER         2396    //CJ_4_S_SWEATER.dff
#define OBJ_CJ_TRACKIES_DARK       2397    //CJ_TRACKIES_dark.dff
#define OBJ_CJ_TRACKIES_LIGHT      2398    //CJ_TRACKIES_LIGHT.dff
#define OBJ_CJ_4_S_SWEATER_2       2399    //CJ_4_S_SWEATER_2.dff
#define OBJ_CJ_SPORTS_WALL01       2400    //CJ_SPORTS_WALL01.dff
#define OBJ_CJ_TRACKIES_WHITE      2401    //CJ_TRACKIES_WHITE.dff
