/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//savehous.ide
#define OBJ_GENMOTELFURN_SV        15025   //genmotelfurn_sv.dff
#define OBJ_IMY_ROOMFURN12_SV      15026   //imy_roomfurn12_sv.dff
#define OBJ_IMMY_CLOTHES_SV        15027   //immy_clothes_sv.dff
#define OBJ_GENMOTEL2SH_SV         15028   //genmotel2sh_sv.dff
#define OBJ_GENMOTEL2_SV           15029   //genmotel2_sv.dff
#define OBJ_GENMOTEL_SV            15030   //genmotel_sv.dff
#define OBJ_LASMALL1_SV            15031   //lasmall1_sv.dff
#define OBJ_LASMALLFURN_SV         15032   //lasmallfurn_sv.dff
#define OBJ_VEGASHOTEL_SV          15033   //vegashotel_sv.dff
#define OBJ_HOTELGEN_SV            15034   //hotelgen_sv.dff
#define OBJ_KB_BED_TEST2_SV        15035   //kb_bed_test2_sv.dff
#define OBJ_KIT_CAB_WASHIN_SV      15036   //kit_cab_washin_sv.dff
#define OBJ_MED_DINNING_2_SV       15037   //MED_DINNING_2_sv.dff
#define OBJ_PLANT_POT_3_SV         15038   //Plant_Pot_3_sv.dff
#define OBJ_MRK_BED02_SV           15039   //mrk_bed02_sv.dff
#define OBJ_CUNTBITS               15040   //cuntbits.dff
#define OBJ_CUNTHOUSE              15041   //cunthouse.dff
#define OBJ_NEWHOUSE1              15042   //newhouse1.dff
#define OBJ_SVCUNTFLORDAY          15043   //svcuntflorday.dff
#define OBJ_LAMIDSHADFLOOR         15044   //lamidshadfloor.dff
#define OBJ_BIGLASHADOW            15045   //bigLAshadow.dff
#define OBJ_COUNTRYSAVEHOUSE       15046   //countrysavehouse.dff
#define OBJ_SVVGMDSHADFLOOR        15047   //svvgmdshadfloor.dff
#define OBJ_LABIGSAVEHOUSE         15048   //LABIGSAVEHOUse.dff
#define OBJ_SVLABIGKITCHSHAD       15049   //svlabigkitchshad.dff
#define OBJ_SVLABIGBITS            15050   //svlabigbits.dff
#define OBJ_SVLASMSHAD             15051   //svlasmshad.dff
#define OBJ_SVSFSMSHAD             15052   //svsfsmshad.dff
#define OBJ_BIGNICEVEGHOTEL        15053   //bigniceveghotel.dff
#define OBJ_SVVGMEDHOOSE           15054   //svvgmedhoose.dff
#define OBJ_SAVELAMID              15055   //savelamid.dff
#define OBJ_SVSFSMSHADFLOOR2       15056   //svsfsmshadfloor2.dff
#define OBJ_BIHOTELSHAD            15057   //bihotelshad.dff
#define OBJ_MIDVEGSAVEHOUSE        15058   //midvegsavehouse.dff
#define OBJ_LABIHALFHOUSE          15059   //labihalfhouse.dff
#define OBJ_SVSFMDSHADFLR1         15060   //svsfmdshadflr1.dff
#define OBJ_SVLAMIDSHAD            15061   //svlamidshad.dff
#define OBJ_LAMIDSHADFLR           15062   //lamidshadflr.dff
#define OBJ_SVMIDSAVEBITS          15063   //svmidsavebits.dff
#define OBJ_SVRAILS                15064   //svrails.dff
