/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//stadint.ide
#define OBJ_KICKBUS04              13590   //kickbus04.dff
#define OBJ_KICKCAR28              13591   //kickcar28.dff
#define OBJ_LOOPBIG                13592   //loopbig.dff
#define OBJ_KICKRAMP03             13593   //kickramp03.dff
#define OBJ_FIREYFIRE              13594   //fireyfire.dff
#define OBJ_STAND02                13595   //stand02.dff
#define OBJ_DESTRUCT04             13596   //destruct04.dff
#define OBJ_DESTRUCT05             13597   //destruct05.dff
#define OBJ_STAND03                13598   //stand03.dff
#define OBJ_STANDBLACK04           13599   //standblack04.dff
#define OBJ_DESTRUCT06             13600   //destruct06.dff
#define OBJ_DESTRUCT07             13601   //destruct07.dff
#define OBJ_THEBOLLA06             13602   //thebolla06.dff
#define OBJ_STAD_TAG               13603   //stad_tag.dff
#define OBJ_KICKRAMP05             13604   //kickramp05.dff
#define OBJ_DESTRUCT1              13605   //destruct1.dff
#define OBJ_STANDBLACK02           13606   //standblack02.dff
#define OBJ_RINGWALLS              13607   //ringwalls.dff
#define OBJ_SUMORING               13608   //sumoring.dff
#define OBJ_SUPPORTS               13609   //supports.dff
#define OBJ_STAND04                13610   //stand04.dff
#define OBJ_THEBOWL13              13611   //thebowl13.dff
#define OBJ_STUNTMAN03             13612   //stuntman03.dff
#define OBJ_THEBOWL11              13613   //thebowl11.dff
#define OBJ_THEBOWL12              13614   //thebowl12.dff
#define OBJ_THEBOWL10              13615   //thebowl10.dff
#define OBJ_THEBOLLA04             13616   //thebolla04.dff
#define OBJ_THEBOWL14              13617   //thebowl14.dff
#define OBJ_THEBOWL16              13618   //thebowl16.dff
#define OBJ_THEBOWL17              13619   //thebowl17.dff
#define OBJ_THEBOWL15              13620   //thebowl15.dff
#define OBJ_THEBOLLA03             13621   //thebolla03.dff
#define OBJ_SUMOFENCE              13622   //sumofence.dff
#define OBJ_MIDRINGFENCE           13623   //midringfence.dff
#define OBJ_INNER                  13624   //inner.dff
#define OBJ_STANDS                 13625   //stands.dff
#define OBJ_8ROAD2                 13626   //8road2.dff
#define OBJ_STADOVAL               13627   //stadoval.dff
#define OBJ_8STAD                  13628   //8stad.dff
#define OBJ_8SCREEN01              13629   //8screen01.dff
#define OBJ_8SCREEN                13630   //8screen.dff
#define OBJ_DIRTSTAD               13631   //dirtstad.dff
#define OBJ_DIRTCROWDS             13632   //dirtcrowds.dff
#define OBJ_DIRTOUTER01            13633   //dirtouter01.dff
#define OBJ_DIRTSTAD02             13634   //dirtstad02.dff
#define OBJ_THEROCKS10             13635   //therocks10.dff
#define OBJ_LOGRAMPS               13636   //logramps.dff
#define OBJ_TUBERAMP               13637   //tuberamp.dff
#define OBJ_STUNT1                 13638   //stunt1.dff
#define OBJ_RAMPARSE               13639   //ramparse.dff
#define OBJ_ARSE                   13640   //arse.dff
#define OBJ_KICKRAMP04             13641   //kickramp04.dff
#define OBJ_RINGS                  13642   //rings.dff
#define OBJ_LOGRAMPS02             13643   //logramps02.dff
#define OBJ_STEPS                  13644   //steps.dff
#define OBJ_KICKRAMP06             13645   //kickramp06.dff
#define OBJ_RAMPLANDPAD            13646   //ramplandpad.dff
#define OBJ_WALL1                  13647   //wall1.dff
#define OBJ_WALL2                  13648   //wall2.dff
#define OBJ_RAMPLANDPAD01          13649   //ramplandpad01.dff
#define OBJ_KICKCROWD01            13650   //kickcrowd01.dff
#define OBJ_OTUNNEL                13651   //otunnel.dff
#define OBJ_OROADBIT               13652   //oroadbit.dff
#define OBJ_INNERFENCE             13653   //innerfence.dff
#define OBJ_DARKPOLY               13654   //darkpoly.dff
#define OBJ_BRIDGE                 13655   //bridge.dff
#define OBJ_FUCKKNOWS              13656   //fuckknows.dff
#define OBJ_BIT                    13657   //bit.dff
#define OBJ_BIT01                  13658   //bit01.dff
#define OBJ_8BAR5                  13659   //8bar5.dff
#define OBJ_8TRACK1                13660   //8track1.dff
#define OBJ_COCKBARS               13661   //cockbars.dff
#define OBJ_DIRTCOCK               13662   //dirtcock.dff
#define OBJ_DIRTFENCES             13663   //dirtfences.dff
#define OBJ_DIRTROAD               13664   //dirtroad.dff
#define OBJ_DIRTFENCES2            13665   //dirtfences2.dff
#define OBJ_LOOPWEE                13666   //loopwee.dff
#define OBJ_MONKEYMAN              13667   //monkeyman.dff
