/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAhills.ide
#define OBJ_CUNTE_ROADS05          13672   //cunte_roads05.dff
#define OBJ_CEHOLLYHIL03           13673   //CEhollyhil03.dff
#define OBJ_CEMULLHOLDR05          13674   //CEmullholdr05.dff
#define OBJ_CUNTELUNGRDJ           13675   //cuntelungrdj.dff
#define OBJ_TCELAWCUNTUN1A_LAW2    13676   //TCElawcuntun1a_law2.dff
#define OBJ_TCELAWCUNTUNA_LAW2     13677   //TCElawcuntuna_law2.dff
#define OBJ_CENWHILTEST            13678   //CEnwhiltest.dff
#define OBJ_TCELANDBIVF4V_03       13679   //TCElandbivF4v_03.dff
#define OBJ_TCELAWCUNTUNB          13680   //TCElawcuntunb.dff
#define OBJ_TCEHILHOUSE03          13681   //TCEhilhouse03.dff
#define OBJ_TCECUNTUN              13682   //TCEcuntun.dff
#define OBJ_CENWHILTEST2           13683   //CEnwhiltest2.dff
#define OBJ_CENWHILTEST93          13684   //CEnwhiltest93.dff
#define OBJ_TCENWHILTEST92         13685   //TCEnwhiltest92.dff
#define OBJ_TCEHOMULHIL10          13686   //TCEhomulhil10.dff
#define OBJ_TCEHILLHSE02           13687   //TCEhillhse02.dff
#define OBJ_CENWHILTEST91          13688   //CEnwhiltest91.dff
#define OBJ_CENWHILTEST6           13689   //CEnwhiltest6.dff
#define OBJ_CE_ROADS38A            13690   //CE_Roads38a.dff
#define OBJ_TCELALANDBIV_03        13691   //TCELAlandbiv_03.dff
#define OBJ_CUNTE_LANDF4_03        13692   //cunte_landF4_03.dff
#define OBJ_TCENWHILTEST94         13693   //TCEnwhiltest94.dff
#define OBJ_CEHILLHSE13            13694   //CEhillhse13.dff
#define OBJ_CEHILLHSE05            13695   //CEhillhse05.dff
#define OBJ_CENEWHILLHUS           13696   //CEnewhillhus.dff
#define OBJ_TCELHOUSE06            13697   //TCElhouse06.dff
#define OBJ_CEHOLLYHIL10           13698   //CEhollyhil10.dff
#define OBJ_TCEMULHILHED1_LAW2     13699   //TCEmulhilhed1_law2.dff
#define OBJ_CEHOLLYHIL1            13700   //CEhollyhil1.dff
#define OBJ_TCEHILOUSE02           13701   //TCEhilouse02.dff
