/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFn.ide
#define OBJ_ROAD04SFN              9205    //road04sfn.dff
#define OBJ_LAND2_SFN10            9206    //land2_sfN10.dff
#define OBJ_LAND2_SFN01            9207    //land2_sfN01.dff
#define OBJ_LAND2_SFN19            9208    //land2_sfN19.dff
#define OBJ_LAND_SFN06             9209    //land_SFN06.dff
#define OBJ_LAND2_SFN11            9210    //land2_sfN11.dff
#define OBJ_LAND2_SFN09            9211    //land2_sfN09.dff
#define OBJ_LAND2_SFN13            9212    //land2_sfN13.dff
#define OBJ_LAND2_SFN15            9213    //land2_sfN15.dff
#define OBJ_LAND2_SFN12            9214    //land2_sfN12.dff
#define OBJ_LAND2_SFN17            9215    //land2_sfN17.dff
#define OBJ_LAND_SFN13             9216    //land_SFN13.dff
#define OBJ_LAND2_SFN16            9217    //land2_sfN16.dff
#define OBJ_LAND_SFN15             9218    //land_SFN15.dff
#define OBJ_LAND2_SFN14            9219    //land2_sfN14.dff
#define OBJ_VILLA_SFN_CHRIS_01     9220    //Villa_SFN_CHRIS_01.dff
#define OBJ_VILLA_SFN_CHRIS_02     9221    //Villa_SFN_CHRIS_02.dff
#define OBJ_ROAD08SFN              9222    //road08sfn.dff
