/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAn.ide
#define OBJ_POLICEST01_LAN         3975    //PoliceSt01_LAn.dff
#define OBJ_POLICEST02_LAN         3976    //PoliceSt02_LAn.dff
#define OBJ_LARIVERSEC1_LAN        3977    //LAriverSec1_LAn.dff
#define OBJ_LARIVERSEC3_LAN        3978    //LAriverSec3_LAn.dff
#define OBJ_BONAVENTURA_LAN        3979    //bonaventura_LAn.dff
