/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//seabed.ide
#define OBJ_SBSBEDLAW2             4240    //sbsbedlaw2.dff
#define OBJ_SBSBED4LAW2            4241    //sbsbed4law2.dff
#define OBJ_SBSBED5LAW2            4242    //sbsbed5law2.dff
#define OBJ_SBSBED8LAW2            4243    //sbsbed8law2.dff
#define OBJ_SBSBED9LAW2            4244    //sbsbed9law2.dff
#define OBJ_SBSBED1LAW2            4245    //sbsbed1law2.dff
#define OBJ_SBSBED3LAW2            4246    //sbsbed3law2.dff
#define OBJ_SBSBED6LAW2            4247    //sbsbed6law2.dff
#define OBJ_SBSBED7LAW2            4248    //sbsbed7law2.dff
#define OBJ_SBSBED91LAW2           4249    //sbsbed91law2.dff
#define OBJ_SBCNE_SEAFLOOR01       4250    //sbcne_seafloor01.dff
#define OBJ_SBCNE_SEAFLOOR02       4251    //sbcne_seafloor02.dff
#define OBJ_SBCNE_SEAFLOOR03       4252    //sbcne_seafloor03.dff
#define OBJ_SBCNE_SEAFLOOR05       4253    //sbcne_seafloor05.dff
#define OBJ_SBCE_GROUNDPALO09      4254    //sbCE_groundPALO09.dff
#define OBJ_SBCNE_SEAFLOOR04       4255    //sbcne_seafloor04.dff
#define OBJ_SBCNE_SEAFLOOR06       4256    //sbcne_seafloor06.dff
#define OBJ_SBSEABED_SFE03         4257    //sbseabed_sfe03.dff
#define OBJ_SBSEABED_SFE05         4258    //sbseabed_sfe05.dff
#define OBJ_SBSEABED_SFE01         4259    //sbseabed_sfe01.dff
#define OBJ_SBSEABED_SFE69         4260    //sbseabed_sfe69.dff
#define OBJ_SBSEABED_SFN02         4261    //sbseabed_SFN02.dff
#define OBJ_SBSEABED_SFN03         4262    //sbseabed_SFN03.dff
#define OBJ_SBSEABED_SFNCUNT       4263    //sbseabed_SFNcunt.dff
#define OBJ_SBSEABED1_SFW          4264    //sbseabed1_SFW.dff
#define OBJ_SBSEABED2SFW           4265    //sbseabed2_SFW.dff
#define OBJ_SBSEABED6SFW           4266    //sbseabed6_SFW.dff
#define OBJ_SBSEABED2_LAS2         4267    //sbseabed2_las2.dff
#define OBJ_SBSEABED3_LAS20        4268    //sbseabed3_las20.dff
#define OBJ_SBSEABED1_LAS2         4269    //sbseabed1_las2.dff
#define OBJ_SBSEABED5_LAS2         4270    //sbseabed5_las2.dff
#define OBJ_SBSEABED6LAS2          4271    //sbseabed6las2.dff
#define OBJ_SBSEABED8_LAS2         4272    //sbseabed8_las2.dff
#define OBJ_SBSEABED7_LAS2         4273    //sbseabed7_las2.dff
#define OBJ_SBSEABED86_LAS2        4274    //sbseabed86_las2.dff
#define OBJ_SBSEABED9_LAS20        4275    //sbseabed9_las20.dff
#define OBJ_SBSEABED91_LAS2        4276    //sbseabed91_las2.dff
#define OBJ_SBSEABED93_LAS         4277    //sbseabed93_LAS.dff
#define OBJ_SBSEABED92_LAS         4278    //sbseabed92_LAS.dff
#define OBJ_SBSEABED94_LAS         4279    //sbseabed94_LAS.dff
#define OBJ_SBSEABED95_LAS         4280    //sbseabed95_LAS.dff
#define OBJ_SBSEABED96_LAS         4281    //sbseabed96_LAS.dff
#define OBJ_SBSEABED97_LAS         4282    //sbseabed97_LAS.dff
#define OBJ_SBSEABED99_LAS         4283    //sbseabed99_LAS.dff
#define OBJ_SBSEABED98_LAS         4284    //sbseabed98_LAS.dff
#define OBJ_SBSEABED81_LAS         4285    //sbseabed81_LAS.dff
#define OBJ_SBSEABED85_LAS         4286    //sbseabed85_LAS.dff
#define OBJ_SBSEABED84_LAS         4287    //sbseabed84_LAS.dff
#define OBJ_SBSEABED83_LAS         4288    //sbseabed83_LAS.dff
#define OBJ_SBSEABED82_LAS         4289    //sbseabed82_LAS.dff
#define OBJ_SBCS_LANDBIT_46        4290    //sbcs_landbit_46.dff
#define OBJ_SBCS_LANDBIT_54        4291    //sbcs_landbit_54.dff
#define OBJ_SBCS_LANDBIT_63        4292    //sbcs_landbit_63.dff
#define OBJ_SBCS_LANDBIT_72        4293    //sbcs_landbit_72.dff
#define OBJ_SBCS_LANDBIT_77        4294    //sbcs_landbit_77.dff
#define OBJ_SBCS_LANDBIT_78        4295    //sbcs_landbit_78.dff
#define OBJ_SBCS_SEABIT_NEW        4296    //sbcs_seabit_new.dff
#define OBJ_SBCS_SEABIT1_NEW       4297    //sbcs_seabit1_new.dff
#define OBJ_SBCS_SEABIT2_NEW       4298    //sbcs_seabit2_new.dff
#define OBJ_SBCS_SEABIT3_NEW       4299    //sbcs_seabit3_new.dff
#define OBJ_SBCS_SEABIT4_NEW       4300    //sbcs_seabit4_new.dff
