/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFs.ide
#define OBJ_OC_FLATS_GND01_SFS     10350   //OC_FLATS_GND01_SFS.dff
#define OBJ_GROUNDBIT_10_SFS       10351   //groundbit_10_SFS.dff
#define OBJ_GROUNDBIT_11_SFS       10352   //groundbit_11_SFS.dff
#define OBJ_GROUNDBIT_12_SFS       10353   //groundbit_12_SFS.dff
#define OBJ_GROUNDBIT_13_SFS       10354   //groundbit_13_SFS.dff
#define OBJ_GROUNDBIT_48_SFS       10355   //groundbit_48_SFS.dff
#define OBJ_HASHBURY_01_SFS        10356   //hashbury_01_SFS.dff
#define OBJ_TRANSMITTER_SFS        10357   //transmitter_sfs.dff
#define OBJ_OC_FLATS_GND02_SFS     10358   //OC_FLATS_GND02_SFS.dff
#define OBJ_SFSHILL02              10359   //sfshill02.dff
#define OBJ_SFSHILL03              10360   //sfshill03.dff
#define OBJ_SFSHILL04              10361   //sfshill04.dff
#define OBJ_SFSHILL05              10362   //sfshill05.dff
#define OBJ_SFSHILL06              10363   //sfshill06.dff
#define OBJ_SFSHILL07              10364   //sfshill07.dff
#define OBJ_ROADBIT21_SFS          10365   //roadbit21_SFS.dff
#define OBJ_GOLFTUNNEL1_SFS        10366   //golftunnel1_SFS.dff
#define OBJ_ROADBIT38_SFS          10367   //roadbit38_SFS.dff
#define OBJ_CATHEDRAL_SFS          10368   //cathedral_SFS.dff
#define OBJ_SMALLSHOP_10_SFS08     10369   //smallshop_10_SFS08.dff
#define OBJ_ALLEY1_SFS             10370   //alley1_SFS.dff
#define OBJ_ALLEY1_SFS01           10371   //alley1_SFS01.dff
#define OBJ_ALLEY2_SFS01           10372   //alley2_SFS01.dff
#define OBJ_ALLEY2_SFS02           10373   //alley2_SFS02.dff
#define OBJ_ALLEY2_SFS04           10374   //alley2_SFS04.dff
#define OBJ_SUBSHOP_SFS            10375   //subshop_SFS.dff
