/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//levelxre.ide
#define OBJ_XREF_GARAGEDOOR        2885    //xref_garagedoor.dff
#define OBJ_SEC_KEYPAD             2886    //sec_keypad.dff
#define OBJ_A51_SPOTBULB           2887    //a51_spotbulb.dff
#define OBJ_A51_SPOTHOUSING        2888    //a51_spothousing.dff
#define OBJ_A51_SPOTBASE           2889    //a51_spotbase.dff
#define OBJ_KMB_SKIP               2890    //kmb_skip.dff
#define OBJ_KMB_PACKET             2891    //kmb_packet.dff
#define OBJ_TEMP_STINGER           2892    //temp_stinger.dff
#define OBJ_KMB_RAMP               2893    //kmb_ramp.dff
#define OBJ_KMB_RHYMESBOOK         2894    //kmb_rhymesbook.dff
#define OBJ_FUN_FLOWER_LAW         2895    //fun_flower_law.dff
#define OBJ_CASKET_LAW             2896    //casket_law.dff
#define OBJ_FUNTARP_LAW            2897    //funtarp_law.dff
#define OBJ_FUNTURF_LAW            2898    //funturf_law.dff
