/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//gen_int3.ide
#define OBJ_INT_BROTHELSEATS       14770   //int_brothelseats.dff
#define OBJ_INT3INT_BROTHEL        14771   //int3int_brothel.dff
#define OBJ_INT3INT_LOW_TV         14772   //int3int_LOW_TV.dff
#define OBJ_INT3INT_BROTHEL03      14773   //int3int_brothel03.dff
#define OBJ_INT_5KB_FLYKILLER      14774   //int_5kb_flykiller.dff
#define OBJ_INT3INT_BROTHEL04      14775   //int3int_brothel04.dff
#define OBJ_INT3INT_CARUPG_INT     14776   //int3int_carupg_int.dff
#define OBJ_INT_5WEECASINO         14777   //int_5weecasino.dff
#define OBJ_INT_BOXING02           14778   //int_boxing02.dff
#define OBJ_INT_BOXING03           14779   //int_boxing03.dff
#define OBJ_IN_BXING04             14780   //in_bxing04.dff
#define OBJ_IN_BXING05             14781   //in_bxing05.dff
#define OBJ_INT3INT_BOXING30       14782   //int3int_boxing30.dff
#define OBJ_INT3INT_KBSGARAGE      14783   //int3int_kbsgarage.dff
#define OBJ_GENINT_WAREHS          14784   //genint_warehs.dff
#define OBJ_GEN_OTB                14785   //gen_otb.dff
#define OBJ_AB_SFGYMBEAMS1         14786   //ab_sfGymBeams1.dff
#define OBJ_AB_SFGYMBITS02A        14787   //ab_sfGymBits02a.dff
#define OBJ_AB_SFGYMBITS01A        14788   //ab_sfGymBits01a.dff
#define OBJ_AB_SFGYMMAIN1          14789   //ab_sfGymMain1.dff
#define OBJ_AB_SFGYMBITS03A        14790   //ab_sfGymBits03a.dff
#define OBJ_A_VGSGYMBOXA           14791   //a_vgsGymBoxa.dff
#define OBJ_AB_VGSGYMBITS01A       14792   //ab_vgsGymBits01a.dff
#define OBJ_AB_VEGASGYMLITESA      14793   //ab_vegasGymLitesa.dff
#define OBJ_AB_VEGASGYMMAIN2       14794   //ab_vegasGymMain2.dff
#define OBJ_GENINT3_SMASHTV        14795   //genint3_smashtv.dff
#define OBJ_INT_KBSGARAGE05B       14796   //int_kbsgarage05b.dff
#define OBJ_INT_KBSGARAGE3B        14797   //int_kbsgarage3b.dff
#define OBJ_INT_KBSGARAGE3         14798   //int_kbsgarage3.dff
#define OBJ_GEN_OTB_BITS           14800   //gen_otb_bits.dff
#define OBJ_BDUPS_MAIN             14801   //Bdups_main.dff
#define OBJ_BDUPS_INTERIOR         14802   //BDups_interior.dff
#define OBJ_BDUPSNEW               14803   //BDupsNEW.dff
#define OBJ_BDUPS_PLANT            14804   //BDups_plant.dff
#define OBJ_BDUPSNEW_INT           14805   //BDupsNew_int.dff
#define OBJ_BDUPSHIFI              14806   //BDupshifi.dff
#define OBJ_BDUPSLIGHT01           14807   //BDupslight01.dff
#define OBJ_STRIP2_BUILDING        14808   //Strip2_Building.dff
#define OBJ_STRIP2_PLATFORMS       14809   //Strip2_Platforms.dff
#define OBJ_STRIP2_TABLES          14810   //Strip2_Tables.dff
#define OBJ_STRIP2_NEON            14811   //Strip2_neon.dff
#define OBJ_STUDIOHALL_FRAMES      14812   //StudioHall_frames.dff
#define OBJ_STUDIOHALL_FURN        14813   //StudioHall_Furn.dff
#define OBJ_STUDIOHALLBUILD        14814   //StudioHallBuild.dff
#define OBJ_WHHOUSE_MAIN           14815   //Whhouse_main.dff
#define OBJ_WHHOUSE_FURN           14816   //Whhouse_furn.dff
#define OBJ_WHHOUSE_RMS            14817   //Whhouse_Rms.dff
#define OBJ_OG_DOOR                14819   //OG_Door.dff
#define OBJ_DJ_STUFF               14820   //dj_stuff.dff
#define OBJ_MC_STRAPS_INT          14821   //mc_straps_int.dff
#define OBJ_GYM2_DOORWAY           14822   //Gym2_doorway.dff
#define OBJ_GYM3_DOORWAY           14823   //Gym3_doorway.dff
#define OBJ_GYM1_DOORWAY           14824   //Gym1_doorway.dff
#define OBJ_INT_BOXING07           14825   //int_boxing07.dff
#define OBJ_INT_KBSGARAGE2         14826   //int_kbsgarage2.dff
#define OBJ_AB_SFGYMBITS01A2       14827   //ab_sfGymBits01a2.dff
#define OBJ_LM_STRIP2PRIV          14828   //LM_strip2Priv.dff
#define OBJ_STRIP_SIGNS            14829   //strip_signs.dff
#define OBJ_STRIP_LIGHTS           14830   //strip_lights.dff
#define OBJ_LM_STRIPBAR            14831   //LM_stripbar.dff
#define OBJ_LM_STRIPCORNER         14832   //LM_stripCorner.dff
#define OBJ_LM_STRIPCHAIRS1        14833   //LM_stripchairs1.dff
#define OBJ_LM_STRIPPLANT          14834   //LM_stripplant.dff
#define OBJ_LM_STRIPCOLUMNS        14835   //LM_stripColumns.dff
#define OBJ_LM_STRIPPOLES          14836   //LM_strippoles.dff
#define OBJ_LM_STRIPCHAIRS         14837   //LM_stripchairs.dff
#define OBJ_INT_STRIP_CLUB         14838   //int_strip_club.dff
#define OBJ_LM_STRIPPRIV           14839   //LM_stripPriv.dff
#define OBJ_BDUPS_GRAF             14840   //Bdups_graf.dff
