/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//int_veg.ide
#define OBJ_TRIAD_BAR              14560   //triad_bar.dff
#define OBJ_TRIAD_NEON             14561   //triad_neon.dff
#define OBJ_TRIAD_LION             14562   //triad_lion.dff
#define OBJ_TRIAD_MAIN             14563   //triad_main.dff
#define OBJ_TRIAD_LIGHTS           14564   //triad_lights.dff
#define OBJ_TRIAD_BAR_STUFF        14565   //triad_bar_stuff.dff
#define OBJ_BUDHA_WHEL1B           14566   //budha_whel1b.dff
#define OBJ_BUDHA_WHEL02B          14567   //budha_whel02b.dff
#define OBJ_BUDHA_WHEL03B          14568   //budha_whel03b.dff
