/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//vegasE.ide
#define OBJ_MULTICARPARK01_LVS     8390    //multicarpark01_lvS.dff
#define OBJ_BALLYS03_LVS           8391    //ballys03_lvs.dff
#define OBJ_BALLYS02_LVS           8392    //ballys02_lvs.dff
#define OBJ_BALLYS01_LVS           8393    //ballys01_lvs.dff
#define OBJ_VGSBOX10SGN_LVS        8394    //vgsbox10sgn_lvS.dff
#define OBJ_VGEPYRMD_DY            8395    //vgEpyrmd_dy.dff
#define OBJ_SPHINX02_LVS           8396    //sphinx02_lvs.dff
#define OBJ_LUXORPILLAR01_LVS      8397    //luxorpillar01_lvs.dff
#define OBJ_LUXORLAND01_LVS        8398    //luxorland01_lvS.dff
#define OBJ_NIGHTCLUB01_LVS        8399    //nightclub01_lvs.dff
#define OBJ_NIGHTCLUB02_LVS        8400    //nightclub02_lvs.dff
#define OBJ_SHOP05_LVS             8401    //shop05_lvs.dff
#define OBJ_VGSHPGRND01_LVS        8402    //vgshpgrnd01_lvS.dff
#define OBJ_SHOP03_LVS             8403    //shop03_lvs.dff
#define OBJ_VGSHPGRND03_LVS        8404    //vgshpgrnd03_lvS.dff
#define OBJ_VGSHPGRND02_LVS        8405    //vgshpgrnd02_lvS.dff
#define OBJ_CARPARKSIGN01_LVS      8406    //carparksign01_lvs.dff
#define OBJ_CARPARKHUT01_LVS       8407    //carparkhut01_lvs.dff
#define OBJ_CARPARKSIGN02_LVS      8408    //carparksign02_lvs.dff
#define OBJ_GNHOTEL01_LVS          8409    //gnhotel01_lvs.dff
#define OBJ_CARPARKHUT02_LVS       8410    //carparkhut02_lvs.dff
#define OBJ_GNHOTEL02_LVS          8411    //gnhotel02_lvs.dff
#define OBJ_WDDNGCHPLSIGN_LVS      8412    //wddngchplsign_lvs.dff
#define OBJ_BBALLCOURT02_LVS       8416    //bballcourt02_lvs.dff
#define OBJ_BBALLCOURT01_LVS       8417    //bballcourt01_lvs.dff
#define OBJ_VGSHPGRND04_LVS        8418    //vgshpgrnd04_lvS.dff
#define OBJ_VGSBLDNG01_LVS         8419    //vgsbldng01_lvs.dff
#define OBJ_ARPRTCRPRK04_LVS       8420    //arprtcrprk04_lvS.dff
#define OBJ_PIRTEHTL02_LVS         8421    //pirtehtl02_lvS.dff
