/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAs2.ide
#define OBJ_STORDRALAS2            5105    //Stordralas2.dff
#define OBJ_ROADSBX_LAS2           5106    //Roadsbx_las2.dff
#define OBJ_CHEMPLANT2_LAS2        5107    //chemplant2_las2.dff
#define OBJ_LADOCKS2_LAS2          5108    //LADocks2_las2.dff
#define OBJ_SANPDMDOCK3_LAS2       5109    //sanpdmdock3_las2.dff
#define OBJ_MEXCRNERSHP2_LAS2      5110    //mexcrnershp2_las2.dff
#define OBJ_INDUSLAND2_LAS2        5111    //IndusLand2_las2.dff
#define OBJ_LAROADS_26_LAS2        5112    //LAroads_26_las2.dff
#define OBJ_BLOCKAA_LAS2           5113    //BlockAA_las2.dff
#define OBJ_BEACH1_LAS2            5114    //Beach1_las2.dff
#define OBJ_LAS2CHEMDOCK1          5115    //las2chemdock1.dff
#define OBJ_LAS2STRIPBAR1          5116    //las2stripbar1.dff
#define OBJ_TRNTRK4_LAS2           5117    //TRNTRK4_las2.dff
#define OBJ_TRNTRK3_LAS2           5118    //TRNTRK3_las2.dff
#define OBJ_TRNTRK4A_LAS2          5119    //TRNTRK4A_las2.dff
#define OBJ_BTOROAD3_LAS2          5120    //BTOROAD3_las2.dff
#define OBJ_BTOLAND6_LAS2          5121    //BTOLAND6_las2.dff
#define OBJ_BTOLAND5_LAS2          5122    //BTOLAND5_las2.dff
#define OBJ_NEWCOMP2_LAS2          5123    //NEWCOMP2_las2.dff
#define OBJ_NWCSTRD2_LAS2          5124    //NWCSTRD2_las2.dff
#define OBJ_NWCSTRD3_LAS2          5125    //NWCSTRD3_las2.dff
#define OBJ_DOCKCRANESCALE0        5126    //dockcranescale0.dff
#define OBJ_IMCOMP1TRK             5127    //imcomp1trk.dff
#define OBJ_BTOROAD1MNK_LAS2       5128    //BTOROAD1mnk_las2.dff
#define OBJ_IMRACOMPINT_LAS2       5129    //imracompint_las2.dff
#define OBJ_IMCOMPSTRS02           5130    //imcompstrs02.dff
#define OBJ_IMRANCOMP1_LAS2        5131    //imrancomp1_las2.dff
#define OBJ_LAS2DKWAR107           5132    //las2dkwar107.dff
#define OBJ_BCHCOSTRD6_LAS2        5133    //bchcostrd6_las2.dff
#define OBJ_SNPEDSHPRK_LAS2        5134    //snpedshprk_las2.dff
#define OBJ_BRKWRHUS02             5135    //brkwrhus02.dff
#define OBJ_SNPEDSHPRK1_LAS2       5136    //snpedshprk1_las2.dff
#define OBJ_BRKWRHUS3_LAS2         5137    //brkwrhus3_las2.dff
#define OBJ_SNPDOLDWRHS2_LAS2      5138    //snpdoldwrhs2_las2.dff
#define OBJ_SANPEDRO4_LAS2         5139    //sanpedro4_las2.dff
#define OBJ_SNPEDTATSHP            5140    //snpedtatshp.dff
#define OBJ_BTOROADXTRA_LAS2       5141    //BTOROADxtra_las2.dff
#define OBJ_LAS2PLAZA1BIT          5142    //las2plaza1bit.dff
#define OBJ_LAS2CHENDOCK04         5143    //las2chendock04.dff
#define OBJ_LAS2JMSCUM11           5144    //las2jmscum11.dff
#define OBJ_SANPDMDOCK2_LAS2       5145    //sanpdmdock2_las2.dff
#define OBJ_SANPDMDOCK1_LAS2       5146    //sanpdmdock1_las2.dff
#define OBJ_SANPEDBIGBRID_LAS2     5147    //sanpedbigbrid_las2.dff
#define OBJ_BIGSTORMBRID_LAS2      5148    //bigstormbrid_las2.dff
#define OBJ_SCUMEST1_LAS2          5149    //scumest1_las2.dff
#define OBJ_SCUMWIRES1_LAS2        5150    //SCUMWIRES1_las2.dff
#define OBJ_CARGANGHUD_LAS2        5151    //carganghud_las2.dff
#define OBJ_STUNTRAMP1_LAS2        5152    //stuntramp1_las2.dff
#define OBJ_STUNTRAMP7_LAS2        5153    //stuntramp7_las2.dff
#define OBJ_DK_CARGOSHP03D         5154    //dk_cargoshp03d.dff
#define OBJ_DK_CARGOSHP05D         5155    //dk_cargoshp05d.dff
#define OBJ_DK_CARGOSHP24D         5156    //dk_cargoshp24d.dff
#define OBJ_DK_CARGOSHP25D         5157    //dk_cargoshpd25d.dff
#define OBJ_DK_CARGOSHP76D         5158    //dk_cargoshp76d.dff
#define OBJ_DKCARGOHULL2D          5160    //dkcargohull2d.dff
#define OBJ_DKCARGOHULL2BD         5166    //dkcargohull2bd.dff
#define OBJ_DKCARGOHULL2CD         5167    //dkcargohull2cd.dff
#define OBJ_CLUCKINBELL1_LAS2      5168    //cluckinbell1_las2.dff
#define OBJ_IMNRMPY1_LAS2          5169    //imnrmpy1_las2.dff
#define OBJ_IMNRMPY2_LAS2          5170    //imnrmpy2_las2.dff
#define OBJ_DOCKOFF01_LAS2         5171    //dockoff01_LAs2.dff
#define OBJ_BEACH1SPT_LAS2         5172    //Beach1spt_las2.dff
#define OBJ_LAS2JMSCUM12           5173    //las2jmscum12.dff
#define OBJ_SANPEDMEXQ4_LAS2       5174    //sanpedmexq4_las2.dff
#define OBJ_SANPEDMEXQ3_LAS2       5175    //sanpedmexq3_las2.dff
#define OBJ_SANPDMDOCKA_LAS2       5176    //sanpdmdocka_las2.dff
#define OBJ_LAS2STRIPSSHP1         5177    //las2stripsshp1.dff
#define OBJ_CUTRDN1_LAS2           5178    //cutrdn1_las2.dff
#define OBJ_MEXCRNERSHP_LAS2       5179    //mexcrnershp_las2.dff
#define OBJ_NWSPLTBILD2_LAS2       5180    //nwspltbild2_las2.dff
#define OBJ_NWSPLTBILD3_LAS2       5181    //nwspltbild3_las2.dff
#define OBJ_NWSPLTBILD4_LAS2       5182    //nwspltbild4_las2.dff
#define OBJ_NWSPLTBILD1_LAS2       5183    //nwspltbild1_las2.dff
#define OBJ_MDOCK1A_LAS2           5184    //mdock1a_las2.dff
#define OBJ_BRKWRHUSFUK_LAS2       5185    //brkwrhusfuk_las2.dff
#define OBJ_NWSNPDNW_LAS2          5186    //nwsnpdnw_las2.dff
#define OBJ_MEXCRNRXC_LAS2         5187    //mexcrnrxc_las2.dff
#define OBJ_NWRRDSSPLT_LAS2        5188    //nwrrdssplt_las2.dff
#define OBJ_CTDDWWNBLK_LAS2        5189    //ctddwwnblk_las2.dff
#define OBJ_SCRAPFNCE_LAS2         5190    //scrapfnce_las2.dff
#define OBJ_NWDKBRIDD_LAS2         5191    //nwdkbridd_las2.dff
#define OBJ_CHEMGRND_LAS2          5192    //chemgrnd_las2.dff
#define OBJ_SNPEDTEEW2_LAS2        5231    //snpedteew2_las2.dff
#define OBJ_SNPEDTEEW9_LAS2        5232    //snpedteew9_las2.dff
#define OBJ_SNPEDTEEW8_LAS2        5233    //snpedteew8_las2.dff
#define OBJ_SCUMWFIRES1_LAS20      5234    //SCUMWFIRES1_las20.dff
#define OBJ_RIVERBRIDLS_LAS2       5243    //RiverBridls_las2.dff
#define OBJ_LASNTRK1IM03           5244    //lasntrk1im03.dff
#define OBJ_BCHCOSTRD6V_LAS2       5250    //bchcostrd6v_las2.dff
#define OBJ_LAS2DKWAR01            5259    //las2dkwar01.dff
#define OBJ_LAS2DKWAR02            5260    //las2dkwar02.dff
#define OBJ_LAS2DKWAR03            5261    //las2dkwar03.dff
#define OBJ_LAS2DKWAR04            5262    //las2dkwar04.dff
