/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//VegasS.ide
#define OBJ_AIRPORT01_LVS          7978    //airport01_lvS.dff
#define OBJ_BLASTDEF01_LVS         7979    //blastdef01_lvS.dff
#define OBJ_AIRPRTBITS12_LVS       7980    //airprtbits12_lvS.dff
#define OBJ_SMALLRADAR02_LVS       7981    //smallradar02_lvS.dff
