/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAxref.ide
#define OBJ_COMPMEDHOS2_LAE        3555    //compmedhos2_LAe.dff
#define OBJ_COMPMEDHOS3_LAE        3556    //compmedhos3_LAe.dff
#define OBJ_COMPMEDHOS4_LAE        3557    //compmedhos4_LAe.dff
#define OBJ_COMPMEDHOS5_LAE        3558    //compmedhos5_LAe.dff
#define OBJ_LASTRAN1_LA01          3564    //lastran1_LA01.dff
#define OBJ_LASDKRT1_LA01          3565    //lasdkrt1_LA01.dff
#define OBJ_LASNTRK1               3566    //lasntrk1.dff
#define OBJ_LASNFLTRAIL            3567    //lasnfltrail.dff
#define OBJ_LASNTRK2               3568    //lasntrk2.dff
#define OBJ_LASNTRK3               3569    //lasntrk3.dff
#define OBJ_LASDKRT2               3570    //lasdkrt2.dff
#define OBJ_LASDKRT3               3571    //lasdkrt3.dff
#define OBJ_LASDKRT4               3572    //lasdkrt4.dff
#define OBJ_LASDKRTGRP1            3573    //lasdkrtgrp1.dff
#define OBJ_LASDKRTGRP2            3574    //lasdkrtgrp2.dff
#define OBJ_LASDKRT05              3575    //lasdkrt05.dff
#define OBJ_DOCKCRATES2_LA         3576    //DockCrates2_LA.dff
#define OBJ_DOCKCRATES1_LA         3577    //DockCrates1_LA.dff
#define OBJ_DOCKBARR1_LA           3578    //DockBarr1_LA.dff
#define OBJ_COMPBIGHO2_LAE         3580    //compbigho2_LAe.dff
#define OBJ_COMPMEDHOS1_LAE        3582    //compmedhos1_LAe.dff
#define OBJ_COMPBIGHO3_LAE         3583    //compbigho3_LAe.dff
#define OBJ_COMPPROJ01_LA          3584    //compproj01_LA.dff
#define OBJ_LASTRAN1_LA02          3585    //lastran1_LA02.dff
#define OBJ_ESCL_LA                3586    //escl_LA.dff
#define OBJ_NWSNPEDHUS1_LAS        3587    //nwsnpedhus1_LAS.dff
#define OBJ_SANPED_HSE1_LAS        3588    //sanped_hse1_LAs.dff
#define OBJ_COMPFUKHOUSE3          3589    //compfukhouse3.dff
#define OBJ_COMPFUKHOUSE2          3590    //compfukhouse2.dff
#define OBJ_LA_FUCKCAR2            3593    //la_fuckcar2.dff
#define OBJ_LA_FUCKCAR1            3594    //la_fuckcar1.dff
#define OBJ_DINGBAT01AEX_LA        3595    //Dingbat01Aex_LA.dff
#define OBJ_DINGBAT02AEX_LA        3596    //Dingbat02Aex_LA.dff
#define OBJ_DINGBAT01BEX_LA        3597    //Dingbat01Bex_LA.dff
#define OBJ_HILLHOUSE01_LA         3598    //hillhouse01_LA.dff
#define OBJ_HILLHOUSE02_LA         3599    //hillhouse02_LA.dff
#define OBJ_HILLHOUSE06_LA         3600    //hillhouse06_LA.dff
#define OBJ_HILLHOUSE04_LA         3601    //hillhouse04_LA.dff
#define OBJ_HILLHOUSE05_LA         3602    //hillhouse05_LA.dff
#define OBJ_BEVMAN_LAW2            3603    //bevman_LAW2.dff
#define OBJ_BEVMANGAR_LAW2         3604    //bevmangar_LAW2.dff
#define OBJ_BEVMAN3_LAW2           3605    //bevman3_LAW2.dff
#define OBJ_BEVBRKHUS1             3606    //bevbrkhus1.dff
#define OBJ_BEVMAN2_LAW2           3607    //bevman2_LAW2.dff
#define OBJ_HILLHOUSE08_LA         3608    //hillhouse08_LA.dff
#define OBJ_HILLHOUSE13_LA         3609    //hillhouse13_LA.dff
#define OBJ_HILLHOUSE12_LA         3612    //hillhouse12_LA.dff
#define OBJ_HILLHOUSE10_LA         3613    //hillhouse10_LA.dff
#define OBJ_HILLHOUSE09_LA         3614    //hillhouse09_LA.dff
#define OBJ_SANMONBHUT1_LAW2       3615    //sanmonbhut1_LAW2.dff
#define OBJ_MIDRANHUS2_LAS         3616    //midranhus2_LAS.dff
#define OBJ_MIDRANHUS_LAS          3617    //midranhus_LAS.dff
#define OBJ_NWLAW2HUSJM3_LAW2      3618    //nwlaw2husjm3_Law2.dff
#define OBJ_NWLAW2HUSJM4_LAW2      3619    //nwlaw2husjm4_Law2.dff
#define OBJ_REDOCKRANE_LAS         3620    //redockrane_LAS.dff
#define OBJ_RBIGCRATE_LAS          3621    //rbigcrate_LAS.dff
#define OBJ_RDWARHUS               3622    //rdwarhus.dff
#define OBJ_RDWARHUS2              3623    //rdwarhus2.dff
#define OBJ_NWWARHUS               3624    //nwwarhus.dff
#define OBJ_CRGOSTNTRMP            3625    //crgostntrmp.dff
#define OBJ_DCKWRKHUT              3626    //dckwrkhut.dff
#define OBJ_DCKCANPY               3627    //dckcanpy.dff
#define OBJ_SMALLPROSJMT_LAS       3628    //smallprosjmt_LAS.dff
#define OBJ_ARHANG_LAS             3629    //arhang_LAS.dff
#define OBJ_CRDBOXES2_LAS          3630    //crdboxes2_LAs.dff
#define OBJ_OILCRAT_LAS            3631    //oilcrat_LAS.dff
#define OBJ_IMOILDRUM_LAS          3632    //imoildrum_LAS.dff
