/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFw.ide
#define OBJ_CHINAGATE              9482    //chinagate.dff
#define OBJ_LAND_16_SFW            9483    //land_16_sfw.dff
#define OBJ_LAND_46_SFW            9484    //land_46_sfw.dff
#define OBJ_ROAD_SFW02             9485    //road_SFW02.dff
