/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//int_cont.ide
#define OBJ_TRUKSTP04              14650   //trukstp04.dff
#define OBJ_TRUKSTP05              14651   //trukstp05.dff
#define OBJ_TRUKSTP02              14652   //trukstp02.dff
#define OBJ_TRUKSTP03              14653   //trukstp03.dff
#define OBJ_TRUKSTP06              14654   //trukstp06.dff
#define OBJ_TRUKSTP01              14655   //trukstp01.dff
#define OBJ_TSDINERXITBOX          14656   //tsdinerXitbox.dff
#define OBJ_CUNTCHAIRS             14657   //cuntchairs.dff
