/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//gen_int4.ide
#define OBJ_INT_POLICEA07          14842   //int_policeA07.dff
#define OBJ_INT_POLICEA01          14843   //int_policeA01.dff
#define OBJ_INT_POLICEA02          14844   //int_policeA02.dff
#define OBJ_INT_POLICEA03          14845   //int_policeA03.dff
#define OBJ_INT_PPOL               14846   //int_ppol.dff
#define OBJ_MP_SFPD_BIG            14847   //mp_sfpd_big.dff
#define OBJ_MP_SFPD_STAIRS1        14848   //mp_sfpd_stairs1.dff
#define OBJ_MP_SFPD_LIGHTS1        14849   //mp_sfpd_lights1.dff
#define OBJ_MP_SFPD_OBJ1           14850   //mp_sfpd_obj1.dff
#define OBJ_MP_SFPD_SIGNA          14851   //mp_sfpd_signa.dff
#define OBJ_MP_SFPD_WIN1           14852   //mp_sfpd_win1.dff
#define OBJ_VEG_POL_MAIN2          14853   //veg_pol_main2.dff
#define OBJ_COUNTERA               14854   //countera.dff
#define OBJ_COUNTERB               14855   //counterb.dff
#define OBJ_CELLSA                 14856   //cellsa.dff
#define OBJ_VEG_POL_MAIN1          14858   //veg_pol_main1.dff
#define OBJ_COOCHIE_ROOM           14859   //coochie-room.dff
#define OBJ_COOCHIE_POSTERS        14860   //coochie-posters.dff
#define OBJ_CHOOCHIE_BED           14861   //choochie-bed.dff
#define OBJ_HEADBOARD              14862   //headboard.dff
#define OBJ_CLOTHES                14863   //clothes.dff
#define OBJ_SHOES                  14864   //shoes.dff
#define OBJ_BOBBI_ROOM01           14865   //bobbi-room01.dff
#define OBJ_BOBBIE_BED01           14866   //bobbie-bed01.dff
#define OBJ_BOBBIE_CUPBOARDS       14867   //bobbie-cupboards.dff
#define OBJ_PENNANTS01             14868   //pennants01.dff
#define OBJ_BOBBIE_TABLE           14869   //bobbie-table.dff
#define OBJ_POMPOM01               14870   //pompom01.dff
#define OBJ_KYLIE_BARN             14871   //Kylie_barn.dff
#define OBJ_KYLIE_LOGS             14872   //Kylie_logs.dff
#define OBJ_KYLIE_HAY              14873   //Kylie_hay.dff
#define OBJ_KYLIE_STAIRS           14874   //Kylie_stairs.dff
#define OBJ_KYLIE_HAY1             14875   //Kylie_hay1.dff
#define OBJ_MICHELLE_GARAGE        14876   //michelle-garage.dff
#define OBJ_MICHELLE_STAIRS        14877   //michelle-stairs.dff
#define OBJ_MICHELLE_BARRELS       14878   //michelle-barrels.dff
#define OBJ_MICHELLE_BITS          14879   //michelle-bits.dff
#define OBJ_MICHELLE_BED01         14880   //michelle-bed01.dff
#define OBJ_BARBARA_COP            14881   //barbara-cop.dff
#define OBJ_BARB_PIPES             14882   //barb-pipes.dff
#define OBJ_PRISON_GATES           14883   //prison-gates.dff
#define OBJ_VEGAS_SIGNS1           14885   //Vegas-signs1.dff
#define OBJ_POLVEGSIGNS1           14886   //polvegsigns1.dff
#define OBJ_POLVEGSIGNS3           14887   //polvegsigns3.dff
#define OBJ_MILLIE_HEADBOARD       14888   //Millie-headboard.dff
#define OBJ_MILLIE_ROOM            14889   //Millie-room.dff
#define OBJ_MILLIE_VIBRATORS       14890   //millie-vibrators.dff
#define OBJ_MILLIE_SWING           14891   //millie-swing.dff
#define OBJ_MP_SFPD_WIN2           14892   //mp_sfpd_win2.dff
#define OBJ_POLICE1_EXIT           14893   //police1-exit.dff
#define OBJ_POLICE2_EXIT01         14894   //police2-exit01.dff
#define OBJ_MP_SFPD_OBJ2           14895   //mp_sfpd_obj2.dff
#define OBJ_MP_SFPD_LIGHTS2A       14896   //mp_sfpd_lights2a.dff
#define OBJ_MP_SFPD_LIGHTS1A       14897   //mp_sfpd_lights1a.dff
#define OBJ_INT_POLICEA03A         14898   //int_policeA03a.dff
#define OBJ_POLICE3_EXIT01         14900   //police3-exit01.dff
#define OBJ_POLICE3_EXIT02         14901   //police3-exit02.dff
#define OBJ_VEG_POL_WINDOW         14902   //veg_pol_window.dff
#define OBJ_MP_SFPD_LIGHTS2        14903   //mp_sfpd_lights2.dff
