/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//gen_int1.ide
#define OBJ_INT_TATOOA05           14660   //int_tatooA05.dff
#define OBJ_INT_TATOOA01           14661   //int_tatooA01.dff
#define OBJ_INT_TATOOA02           14662   //int_tatooA02.dff
#define OBJ_INT_TATOOA03           14663   //int_tatooA03.dff
#define OBJ_INT_TATOOA04           14664   //int_tatooA04.dff
#define OBJ_INT_7_11A40            14665   //int_7_11A40.dff
#define OBJ_CJ_SEX_COUNTER03       14666   //CJ_SEX_COUNTER03.dff
#define OBJ_INT_7_11A41            14667   //int_7_11A41.dff
#define OBJ_711_C                  14668   //711_c.dff
#define OBJ_711_D                  14669   //711_d.dff
#define OBJ_INT_7_11A42            14670   //int_7_11A42.dff
#define OBJ_INT_7_11A5             14671   //int_7_11A5.dff
#define OBJ_INT_SEX01              14672   //int_sex01.dff
#define OBJ_CHNSAW1                14673   //chnsaw1.dff
#define OBJ_HOTELFERNS1_LAN        14674   //hotelferns1_LAn.dff
#define OBJ_HOTELATRIUM_LAN        14675   //Hotelatrium_LAn.dff
#define OBJ_INT_TATOOA06           14676   //int_tatooA06.dff
#define OBJ_INT_TATOOA07           14677   //int_tatooA07.dff
#define OBJ_INT_TATOOA08           14678   //int_tatooA08.dff
#define OBJ_INT_TAT_TOOLS01        14679   //Int_tat_tools01.dff
#define OBJ_INT_TAT_LIGHTS01       14680   //Int_tat_lights01.dff
#define OBJ_INT_TATOOA09           14681   //int_tatooA09.dff
#define OBJ_INT_TATOOA10           14682   //int_tatooA10.dff
#define OBJ_INT_TATOOA11           14683   //int_tatooA11.dff
#define OBJ_INT_TATOOA12           14684   //int_tatooA12.dff
#define OBJ_INT_TATOOA13           14685   //int_tatooA13.dff
#define OBJ_INT_TAT_TOOLS02        14686   //Int_tat_tools02.dff
#define OBJ_INT_TAT_LIGHTS02       14687   //Int_tat_lights02.dff
#define OBJ_INT_TATOOA14           14688   //int_tatooA14.dff
#define OBJ_INT_TATOOA15           14689   //int_tatooA15.dff
#define OBJ_INT_7_11A40_BITS       14690   //int_7_11A40_bits.dff
#define OBJ_INT_7_11A41_BITS       14691   //int_7_11A41_bits.dff
#define OBJ_INT_7_11A41_BITS01     14692   //int_7_11A41_bits01.dff
#define OBJ_INT_TAT_TOOLS          14693   //Int_tat_tools.dff
#define OBJ_SEX_SHOP_DET           14694   //SEX_SHOP_DET.dff
#define OBJ_INT_7_11A41_BITS02     14695   //int_7_11A41_bits02.dff
#define OBJ_INT_TAT_LIGHTS         14699   //Int_tat_lights.dff
