/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAn2.ide
#define OBJ_LIBRTOW1_LAN           4550    //LibrTow1_LAn.dff
#define OBJ_LARIVERSEC2_LAN        4551    //LAriverSec2_LAn.dff
#define OBJ_AMUBLOKSUN1_LAN        4552    //amubloksun1_LAn.dff
#define OBJ_ROAD12_LAN2            4553    //road12_LAn2.dff
#define OBJ_LIBBASE1_LAN           4554    //LibBase1_LAn.dff
#define OBJ_FIGFREE4_LAN           4555    //figfree4_LAn.dff
#define OBJ_SKY4PLAZ1_LAN          4556    //sky4plaz1_LAn.dff
#define OBJ_ROAD10_LAN2            4557    //road10_LAn2.dff
#define OBJ_LACMENTR1_LAN          4558    //LacmEntr1_LAn.dff
#define OBJ_LACMABASE1_LAN         4559    //LacmaBase1_LAn.dff
#define OBJ_LACMCANOP1_LAN         4560    //LacmCanop1_LAn.dff
#define OBJ_LAPLAZA2_LAN           4562    //LAplaza2_LAn.dff
#define OBJ_LASKYSCRAP1_LAN        4563    //LAskyscrap1_LAn.dff
#define OBJ_LASKYSCRAP2_LAN        4564    //LAskyscrap2_LAn.dff
#define OBJ_BUNKSTEPS1_LAN         4565    //bunksteps1_LAn.dff
#define OBJ_ROAD07_LAN2            4567    //road07_LAn2.dff
#define OBJ_GROUND01_LAN2          4568    //ground01_LAn2.dff
#define OBJ_STOLENBUILDS05         4569    //stolenbuilds05.dff
#define OBJ_STOLENBUILDS08         4570    //stolenbuilds08.dff
#define OBJ_STOLENBUILDS09         4571    //stolenbuilds09.dff
#define OBJ_STOLENBUILDS11         4572    //stolenbuilds11.dff
#define OBJ_STOLENBUILDS12         4573    //stolenbuilds12.dff
#define OBJ_STOLENBUILDS13         4574    //stolenbuilds13.dff
#define OBJ_FIREESCAPES1_LAN2      4575    //fireescapes1_lan2.dff
#define OBJ_LAN2NEWBUILD1          4576    //lan2newbuild1.dff
#define OBJ_HALGROUNDLAN2          4584    //halgroundlan2.dff
#define OBJ_TOWERLAN2              4585    //towerlan2.dff
#define OBJ_SKYSCRAPN201           4586    //skyscrapn201.dff
#define OBJ_SKYSCRAPN203           4587    //skyscrapn203.dff
#define OBJ_ROOFSHITLAN2           4588    //roofshitlan2.dff
#define OBJ_ROAD15_LAN2            4589    //road15_LAn2.dff
#define OBJ_GRASSPATCHLAN2         4590    //grasspatchlan2.dff
#define OBJ_LAN2SHIT03             4591    //lan2shit03.dff
#define OBJ_LAN2SHIT04             4592    //lan2shit04.dff
#define OBJ_LAN2BUILDBLK01         4593    //lan2buildblk01.dff
#define OBJ_LAN2BUILDBLK02         4594    //lan2buildblk02.dff
#define OBJ_CPARK05_LAN2           4595    //cpark05_LAN2.dff
#define OBJ_CSPGM_LAN2             4596    //cspGM_LAN2.dff
#define OBJ_CRPRKBLOK4_LAN2        4597    //crprkblok4_LAN2.dff
#define OBJ_CRPRKBLOK2_LAN2        4598    //crprkblok2_LAN2.dff
#define OBJ_CSP2GM_LAN2            4599    //csp2GM_LAN2.dff
#define OBJ_LADTBUILD10_LAN        4600    //LAdtbuild10_LAn.dff
#define OBJ_LAN2_GM1               4601    //LAn2_gm1.dff
#define OBJ_LASKYSCRAP4_LAN        4602    //LAskyscrap4_LAn.dff
#define OBJ_SKY4PLAZ2_LAN          4603    //sky4plaz2_LAn.dff
#define OBJ_BUILD4PLAZ_LAN2        4604    //build4plaz_LAn2.dff
#define OBJ_SKYSCRAPN203_GLS       4605    //skyscrapn203_gls.dff
#define OBJ_CPARKGMAUMK_LAN        4636    //cparkgmaumk_LAN.dff
#define OBJ_CPARK_MUCK_LAN2        4637    //cpark_muck_lan2.dff
#define OBJ_PAYPARK_LAN01          4638    //paypark_lan01.dff
#define OBJ_PAYPARK_LAN02          4639    //paypark_lan02.dff
#define OBJ_PAYPARK_LAN03          4640    //paypark_lan03.dff
#define OBJ_PAYPARK_LAN04          4641    //paypark_lan04.dff
#define OBJ_PAYPARK_LAN            4642    //paypark_lan.dff
