/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//stadint.ide
#define OBJ_KICKBUS04              13590   //kickbus04.dff
#define OBJ_KICKCAR28              13591   //kickcar28.dff
#define OBJ_LOOPBIG                13592   //loopbig.dff
#define OBJ_KICKRAMP03             13593   //kickramp03.dff
