/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//int_SF.ide
#define OBJ_DRIVESCHL_MAIN         14530   //driveschl_main.dff
#define OBJ_INT_ZEROSRC01          14531   //int_zerosrc01.dff
#define OBJ_TV_STAND_DRIV          14532   //tv_stand_driv.dff
#define OBJ_PLEASURE_TOP           14533   //pleasure-TOP.dff
#define OBJ_AB_WOOZIES01           14534   //ab_woozies01.dff
#define OBJ_AB_WOOZIES03           14535   //ab_woozies03.dff
#define OBJ_PLEASURE_BOT           14536   //pleasure-BOT.dff
#define OBJ_PDOMESBAR              14537   //pdomesBar.dff
#define OBJ_PDOMES_XITBOX          14538   //Pdomes_Xitbox.dff
#define OBJ_PDOMES_LOGO            14539   //pdomes_logo.dff
#define OBJ_PDOMES_EXTRAS          14540   //pdomes_extras.dff
#define OBJ_DRIVESCHL_DAYLITE      14541   //driveschl_daylite.dff
#define OBJ_WOOZIES_XITBOX         14542   //woozies_Xitbox.dff
#define OBJ_AB_WOOZIES04           14543   //ab_woozies04.dff
#define OBJ_AB_WOOZIES02           14544   //ab_woozies02.dff
#define OBJ_AB_WOOZIESGLASS        14545   //ab_wooziesGlass.dff
#define OBJ_PLEASURE_MID           14546   //pleasure-MID.dff
#define OBJ_PLEASURE_DL            14547   //pleasure-DL.dff
#define OBJ_CARGO_TEST             14548   //cargo_test.dff
#define OBJ_CARGE_BARRELS          14549   //carge_barrels.dff
#define OBJ_CARGO_NETTING          14550   //cargo_netting.dff
#define OBJ_CARGO_STORE            14551   //cargo_store.dff
#define OBJ_CARGO_STUFF            14552   //cargo_stuff.dff
#define OBJ_ANDROM_DES_OBJ         14553   //androm_des_obj.dff
#define OBJ_AB_WOOZIESSHAD         14554   //ab_wooziesSHAD.dff
#define OBJ_ZEROWARDROBE           14556   //ZEROWARDROBE.dff
#define OBJ_MODEL_BOX15            14558   //MODEL_BOX15.dff
#define OBJ_PDOMECONES             14559   //PDomeCones.dff
