/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAe.ide
#define OBJ_LAESKATEPARKLA         5390    //laeskateparkLA.dff
#define OBJ_LAEROAD01              5391    //laeroad01.dff
#define OBJ_LAESTRIPMALL1          5392    //laestripmall1.dff
#define OBJ_LAESHOP1               5393    //laeshop1.dff
#define OBJ_XSTPDNAM_LAE           5394    //xstpdnam_LAE.dff
#define OBJ_LAECOMPTONBRIJ3        5395    //laecomptonbrij3.dff
#define OBJ_LAERAILBRIJBLOK        5396    //laeRailBrijBlok.dff
#define OBJ_LAECLUBBLOCK1          5397    //laeclubBlock1.dff
#define OBJ_LAETRAINTUNN02         5398    //laetraintunn02.dff
#define OBJ_LAETRAINTUNN01         5399    //laetraintunn01.dff
#define OBJ_LAESKATETUBE1          5400    //laeskatetube1.dff
#define OBJ_LAEGARAGES1NW          5401    //laegarages1nw.dff
#define OBJ_LAEHOSPGROUND1         5402    //laehospground1.dff
#define OBJ_LAEHOSPITAL1           5403    //laehospital1.dff
#define OBJ_LAESTORMDRAIN01        5404    //laestormdrain01.dff
#define OBJ_LAEBLAKWESTRAN2        5405    //laeBlakWesTran2.dff
#define OBJ_LAECRACKMOTEL4         5406    //laecrackmotel4.dff
#define OBJ_LAELASRUFF201          5407    //laelasruff201.dff
#define OBJ_LAEEXAMINERBUILD1      5408    //laeexaminerbuild1.dff
#define OBJ_LAEPETROL1A            5409    //laepetrol1a.dff
#define OBJ_LAECUMPSTREET          5410    //laecumpstreet.dff
#define OBJ_LAEROADSBLK            5411    //laeroadsblk.dff
#define OBJ_LAELASJMSCUBIT         5412    //laelasjmscubit.dff
#define OBJ_LAECRACKMOTEL1         5413    //laecrackmotel1.dff
#define OBJ_LAEJEFFERS02           5414    //laeJeffers02.dff
#define OBJ_LAESKATEPARKTRANS      5415    //laeskateparkTrans.dff
#define OBJ_LAEGANGHOUS205         5416    //laeganghous205.dff
#define OBJ_LAENWBLK2              5417    //laenwblk2.dff
#define OBJ_LAE711BLOCK01          5418    //lae711block01.dff
#define OBJ_LAESTORMDRAIN02        5419    //laestormdrain02.dff
#define OBJ_LAESTORMDRAIN03        5420    //laestormdrain03.dff
#define OBJ_LAESMOKESHSE           5421    //laesmokeshse.dff
#define OBJ_LAESPRAYDOOR1          5422    //laespraydoor1.dff
#define OBJ_LAEJEFFERS03           5423    //laeJeffers03.dff
#define OBJ_LAEJEFFERS04           5424    //laeJeffers04.dff
#define OBJ_LAEJEFFERS05           5425    //laeJeffers05.dff
#define OBJ_LAEJEFFERS06           5426    //laeJeffers06.dff
#define OBJ_LAEJEFFERS09           5427    //laeJeffers09.dff
#define OBJ_LAEJEFFERS10           5428    //laeJeffers10.dff
#define OBJ_XWHATTFK_LAE           5429    //xwhattfk_LAE.dff
#define OBJ_LAEIDLEWOOD11          5430    //laeIdlewood11.dff
#define OBJ_LAEROAD02              5431    //laeroad02.dff
#define OBJ_LAEROAD03              5432    //laeroad03.dff
#define OBJ_LAEROAD04              5433    //laeroad04.dff
#define OBJ_LAEROAD05              5434    //laeroad05.dff
#define OBJ_LAEROAD06              5435    //laeroad06.dff
#define OBJ_FUKXROAD07             5436    //fukxroad07.dff
#define OBJ_LAEROAD08              5437    //laeroad08.dff
#define OBJ_LAEROAD09              5438    //laeroad09.dff
#define OBJ_LAEROAD10              5439    //laeroad10.dff
#define OBJ_LAEROAD11              5440    //laeroad11.dff
#define OBJ_LAEROAD12              5441    //laeroad12.dff
#define OBJ_LAEROAD13              5442    //laeroad13.dff
#define OBJ_LAEGLENPARK02          5443    //laeGlenPark02.dff
#define OBJ_LAECHICANO02           5444    //laeChicano02.dff
#define OBJ_LAECHICANO01           5445    //laeChicano01.dff
#define OBJ_LAECHICANO03           5446    //laeChicano03.dff
#define OBJ_LAECHICANO04           5447    //laeChicano04.dff
#define OBJ_LAECHICANO05           5448    //laeChicano05.dff
#define OBJ_LAECHICANOTR1          5449    //laeChicanoTr1.dff
#define OBJ_LAECHICANO06           5450    //laeChicano06.dff
#define OBJ_LAECHICANO07           5451    //laeChicano07.dff
#define OBJ_LAECHICANO09           5452    //laeChicano09.dff
#define OBJ_LAECHICANO10           5453    //laeChicano10.dff
#define OBJ_LAEROAD14              5456    //laeroad14.dff
#define OBJ_LAEGLENPARK01          5457    //laeGlenPark01.dff
#define OBJ_LAEMACPARK01           5458    //laeMacPark01.dff
#define OBJ_LAEJEFFERS01           5459    //laeJeffers01.dff
#define OBJ_LAEGLENPARK05          5461    //laeGlenPark05.dff
#define OBJ_LAEGLENPARK04          5462    //laeGlenPark04.dff
