/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SAMP.ide
#define OBJ_CUTSCENECOUCH1         11682   //CutsceneCouch1.dff
#define OBJ_CUTSCENECOUCH2         11683   //CutsceneCouch2.dff
#define OBJ_CUTSCENECOUCH3         11684   //CutsceneCouch3.dff
#define OBJ_CUTSCENECOUCH4         11685   //CutsceneCouch4.dff
#define OBJ_CBARSECTION1           11686   //CBarSection1.dff
#define OBJ_CBARSTOOL1             11687   //CBarStool1.dff
#define OBJ_CWORKTOP1              11688   //CWorkTop1.dff
#define OBJ_CBOOTHSEAT1            11689   //CBoothSeat1.dff
#define OBJ_CTABLE1                11690   //CTable1.dff
#define OBJ_CTABLE2                11691   //CTable2.dff
#define OBJ_A51LANDBIT1            11692   //A51LandBit1.dff
#define OBJ_HILLS250X250GRASS1     11693   //Hills250x250Grass1.dff
#define OBJ_HILL250X250ROCKY1      11694   //Hill250x250Rocky1.dff
#define OBJ_HILL250X250ROCKY2      11695   //Hill250x250Rocky2.dff
#define OBJ_HILL250X250ROCKY3      11696   //Hill250x250Rocky3.dff
#define OBJ_ROPEBRIDGEPART1        11697   //RopeBridgePart1.dff
#define OBJ_ROPEBRIDGEPART2        11698   //RopeBridgePart2.dff
#define OBJ_SAMPROADSIGN46         11699   //SAMPRoadSign46.dff
#define OBJ_SAMPROADSIGN47         11700   //SAMPRoadSign47.dff
#define OBJ_AMBULANCELIGHTS1       11701   //AmbulanceLights1.dff
#define OBJ_AMBULANCELIGHTS2       11702   //AmbulanceLights2.dff
#define OBJ_MAGNOCRANE_03_2        11703   //MagnoCrane_03_2.dff
#define OBJ_BDUPSMASK1             11704   //BDupsMask1.dff
#define OBJ_BLACKTELEPHONE1        11705   //BlackTelephone1.dff
#define OBJ_SMALLWASTEBIN1         11706   //SmallWasteBin1.dff
#define OBJ_TOWELRACK1             11707   //TowelRack1.dff
#define OBJ_BRICKSINGLE1           11708   //BrickSingle1.dff
#define OBJ_ABATTOIRSINK1          11709   //AbattoirSink1.dff
#define OBJ_FIREEXITSIGN1          11710   //FireExitSign1.dff
#define OBJ_EXITSIGN1              11711   //ExitSign1.dff
#define OBJ_CROSS1                 11712   //Cross1.dff
#define OBJ_FIREEXTPANEL1          11713   //FireExtPanel1.dff
#define OBJ_MAINTENANCEDOORS1      11714   //MaintenanceDoors1.dff
#define OBJ_METALFORK1             11715   //MetalFork1.dff
#define OBJ_METALKNIFE1            11716   //MetalKnife1.dff
#define OBJ_WOOZIESCOUCH1          11717   //WooziesCouch1.dff
#define OBJ_SWEETSSAUCEPAN1        11718   //SweetsSaucepan1.dff
#define OBJ_SWEETSSAUCEPAN2        11719   //SweetsSaucepan2.dff
#define OBJ_SWEETSBED1             11720   //SweetsBed1.dff
#define OBJ_RADIATOR1              11721   //Radiator1.dff
#define OBJ_SAUCEBOTTLE1           11722   //SauceBottle1.dff
#define OBJ_SAUCEBOTTLE2           11723   //SauceBottle2.dff
#define OBJ_FIREPLACESURROUND1     11724   //FireplaceSurround1.dff
#define OBJ_FIREPLACE1             11725   //Fireplace1.dff
#define OBJ_HANGINGLIGHT1          11726   //HangingLight1.dff
#define OBJ_PAPERCHASELIGHT1       11727   //PaperChaseLight1.dff
#define OBJ_PAPERCHASEPHONE1       11728   //PaperChasePhone1.dff
#define OBJ_GYMLOCKERCLOSED1       11729   //GymLockerClosed1.dff
#define OBJ_GYMLOCKEROPEN1         11730   //GymLockerOpen1.dff
#define OBJ_WHEARTBED1             11731   //WHeartBed1.dff
#define OBJ_WHEARTBATH1            11732   //WHeartBath1.dff
#define OBJ_WROCKINGHORSE1         11733   //WRockingHorse1.dff
#define OBJ_WROCKINGCHAIR1         11734   //WRockingChair1.dff
#define OBJ_WBOOT1                 11735   //WBoot1.dff
#define OBJ_MEDICALSATCHEL1        11736   //MedicalSatchel1.dff
#define OBJ_ROCKSTARMAT1           11737   //RockstarMat1.dff
#define OBJ_MEDICCASE1             11738   //MedicCase1.dff
#define OBJ_MCAKE1                 11739   //MCake1.dff
#define OBJ_MCAKE2                 11740   //MCake2.dff
#define OBJ_MCAKE3                 11741   //MCake3.dff
#define OBJ_MCAKESLICE1            11742   //MCakeSlice1.dff
#define OBJ_MCOFFEEMACHINE1        11743   //MCoffeeMachine1.dff
#define OBJ_MPLATE1                11744   //MPlate1.dff
#define OBJ_HOLDALLEDITED1         11745   //HoldAllEdited1.dff
#define OBJ_DOORKEY1               11746   //DoorKey1.dff
#define OBJ_BANDAGE1               11747   //Bandage1.dff
#define OBJ_BANDAGEPACK1           11748   //BandagePack1.dff
#define OBJ_CSHANDCUFFS1           11749   //CSHandcuffs1.dff
#define OBJ_CSHANDCUFFS2           11750   //CSHandcuffs2.dff
#define OBJ_AREABOUNDARY50M        11751   //AreaBoundary50m.dff
#define OBJ_AREABOUNDARY10M        11752   //AreaBoundary10m.dff
#define OBJ_AREABOUNDARY1M         11753   //AreaBoundary1m.dff
