/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//countryW.ide
#define OBJ_WT6SUPPSXC             17000   //wt6suppsxc.dff
#define OBJ_CUNTGRSILOS            17001   //cuntgrsilos.dff
#define OBJ_LAWESTBRIDGE_LAW       17002   //lawestbridge_law.dff
#define OBJ_CUNTWCRIDGE            17003   //cuntwcridge.dff
#define OBJ_COS_PCH_BRIG_1         17004   //cos_pch_brig_1.dff
#define OBJ_FARMHOUSE              17005   //farmhouse.dff
#define OBJ_D5002WHI               17006   //D5002whi.dff
#define OBJ_WT6SUPPS01             17007   //wt6supps01.dff
#define OBJ_FARMHOUSE01            17008   //farmhouse01.dff
#define OBJ_TRUTH_BARN02           17009   //truth_barn02.dff
#define OBJ_TRUTH_BARN03           17010   //truth_barn03.dff
#define OBJ_TRUTH_BARN04           17011   //truth_barn04.dff
#define OBJ_CWSTHSEING26           17012   //cwsthseing26.dff
#define OBJ_CUNTPLANT05            17013   //cuntplant05.dff
#define OBJ_CUNTWPLANT01           17014   //cuntwplant01.dff
#define OBJ_CUNTWPLANT07           17015   //cuntwplant07.dff
#define OBJ_CUNTWPLANT09           17016   //cutnwplant09.dff
#define OBJ_CUNTWPLANT10           17017   //cuntwplant10.dff
#define OBJ_CUNTSPLANTFNCE03       17018   //cuntsplantfnce03.dff
#define OBJ_CUNTFRATES1            17019   //cuntfrates1.dff
#define OBJ_CUNTFRATES02           17020   //cuntfrates02.dff
#define OBJ_CUNTPLANT06            17021   //cuntplant06.dff
#define OBJ_CUNTWPLANT11           17022   //cuntwplant11.dff
#define OBJ_CUTNWPLANT10           17023   //cutnwplant10.dff
#define OBJ_CUNTWPLANT12           17024   //cuntwplant12.dff
#define OBJ_CUNT_ROCKGP1           17025   //cunt_rockgp1_.dff
#define OBJ_CUNT_ROCKGP2           17026   //cunt_rockgp2_.dff
#define OBJ_CUNT_ROCKGP1_03        17027   //cunt_rockgp1_03.dff
#define OBJ_CUNT_ROCKGP2_04        17028   //cunt_rockgp2_04.dff
#define OBJ_CUNT_ROCKGP2_09        17029   //cunt_rockgp2_09.dff
#define OBJ_CUNT_ROCKGP2_11        17030   //cunt_rockgp2_11.dff
#define OBJ_CUNT_ROCKGP2_13        17031   //cunt_rockgp2_13.dff
#define OBJ_CUNT_ROCKGP2_14        17032   //cunt_rockgp2_14.dff
#define OBJ_CUNT_ROCKGP2_15        17033   //cunt_rockgp2_15.dff
#define OBJ_CUNT_ROCKGP2_16        17034   //cunt_rockgp2_16.dff
#define OBJ_CUNT_ROCKGP2_17        17035   //cunt_rockgp2_17.dff
#define OBJ_CUNTW_CARPORT1         17036   //cuntw_carport1_.dff
#define OBJ_CUNTW_CARPORT2         17037   //cuntw_carport2_.dff
#define OBJ_CUNTW_WEEFACTORY1      17038   //cuntw_weefactory1_.dff
#define OBJ_CUNTW_WEEBARN1         17039   //cuntw_weebarn1_.dff
#define OBJ_CUNTW_WEEFACT1         17040   //cuntw_weefact1_.dff
#define OBJ_CUNTW_STWN             17041   //cuntw_stwn.dff
#define OBJ_CUNTW_STWNMOTSIGN2     17042   //cuntw_stwnmotsign2.dff
#define OBJ_CONRETEARCH1           17043   //concretearch1.dff
#define OBJ_CUNTW_STWNYELS         17044   //cuntw_stwnyels.dff
#define OBJ_CUNTW_STWNYEL          17045   //cuntw_stwnyel.dff
#define OBJ_TELEWIRESCUNTW         17046   //telewirescuntw.dff
#define OBJ_CUNTWIRES              17047   //cuntwwires.dff
#define OBJ_CUNTWIRES2             17048   //cuntwwires2.dff
#define OBJ_CW_SILO01              17049   //cw_Silo01.dff
#define OBJ_CW_SILO02              17050   //cw_Silo02.dff
#define OBJ_CW_SILO03              17051   //cw_Silo03.dff
#define OBJ_CW_BIGBARN02           17052   //cw_bigbarn02.dff
