/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAw2.ide
#define OBJ_BEACH01_LAW2           6280    //Beach01_LAw2.dff
#define OBJ_BEACH02_LAW2           6281    //Beach02_LAw2.dff
#define OBJ_VENICE03_LAW2          6282    //venice03_laW2.dff
#define OBJ_PIER04B_LAW2           6283    //pier04b_LAw2.dff
#define OBJ_SANTAHOUSE02_LAW2      6284    //santahouse02_law2.dff
#define OBJ_SANTAHOUSE04_LAW2      6285    //santahouse04_law2.dff
#define OBJ_SANTAHOUSE05_LAW2      6286    //santahouse05_law2.dff
#define OBJ_PIER02C_LAW2           6287    //Pier02c_LAw2.dff
#define OBJ_PIER02B_LAW2           6288    //Pier02b_LAw2.dff
#define OBJ_PIER03B_LAW2           6289    //pier03b_LAw2.dff
#define OBJ_RAILTUNN02_LAW2        6290    //RailTunn02_LAw2.dff
#define OBJ_ROADS30_LAW2           6291    //Roads30_LAw2.dff
#define OBJ_RAILTUNN01_LAW2        6292    //RailTunn01_LAw2.dff
#define OBJ_LAWBORDER2B_LAW2       6293    //lawborder2b_LAW2.dff
#define OBJ_SANTAHOUSEGRP_LAW2     6294    //santahousegrp_law2.dff
#define OBJ_SANPEDLITHUS_LAW2      6295    //sanpedlithus_LAw2.dff
#define OBJ_VEROPOLICE_LAW2        6296    //veropolice_LAW2.dff
#define OBJ_BEACHHUT01_LAW2        6297    //Beachut01_LAw2.dff
#define OBJ_FERRIS01_LAW2          6298    //ferris01_LAw2.dff
#define OBJ_PIER03C_LAW2           6299    //pier03c_LAw2.dff
#define OBJ_PIER04_LAW2            6300    //Pier04_LAw2.dff
