/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//VegasN.ide
#define OBJ_VGSNBUILD07            6863    //vgsNbuild07.dff
#define OBJ_VROCKCAFE              6864    //vrockcafe.dff
#define OBJ_STEERSKULL             6865    //steerskull.dff
#define OBJ_CIRCUSCONSTRUCT03      6866    //circusconstruct03.dff
#define OBJ_VEGASPLANT06           6867    //vegasplant06.dff
#define OBJ_SMLBUILDVGAS05         6868    //smlbuildvgas05.dff
#define OBJ_VEGASTEMP1             6869    //vegastemp1.dff
#define OBJ_COURTHSE_VGN           6871    //courthse_vgn.dff
#define OBJ_VGN_CORPBUILD1         6872    //vgn_corpbuild1.dff
#define OBJ_VGN_CORPBUILD3         6873    //vgn_corpbuild3.dff
#define OBJ_VGN_CORPBUILD2         6874    //vgn_corpbuild2.dff
#define OBJ_VGN_CORPBUILD4         6875    //vgn_corpbuild4.dff
#define OBJ_VEGASNEDGE12           6876    //VegasNedge12.dff
#define OBJ_VEGASNEDGE02           6877    //VegasNedge02.dff
#define OBJ_VEGASNROAD055          6878    //VegasNroad055.dff
#define OBJ_VEGASNROAD070          6879    //VegasNroad070.dff
#define OBJ_VEGASNROAD071          6880    //VegasNroad071.dff
#define OBJ_VEGASNROAD072          6881    //VegasNroad072.dff
#define OBJ_VGNORTHLAND04          6882    //vgnorthland04.dff
#define OBJ_VGNORTHLAND06          6883    //vgnorthland06.dff
#define OBJ_VGNORTHLAND07          6884    //vgnorthland07.dff
#define OBJ_VEGASNEDGE03           6885    //VegasNedge03.dff
#define OBJ_VEGASNEDGE04           6886    //VegasNedge04.dff
#define OBJ_VEGASNEDGE05           6887    //VegasNedge05.dff
#define OBJ_VEGASNEDGE06           6888    //VegasNedge06.dff
#define OBJ_VEGASNROAD622          6897    //VegasNroad622.dff
#define OBJ_VEGASNROAD623          6898    //VegasNroad623.dff
#define OBJ_VEGASNROAD624          6899    //VegasNroad624.dff
#define OBJ_VEGASNROAD625          6900    //VegasNroad625.dff
#define OBJ_VGNDWNTWNSHOP1         6907    //vgndwntwnshop1.dff
#define OBJ_VGNDWNTWNSHOP2         6908    //vgndwntwnshop2.dff
#define OBJ_VGNPRTLSTATION         6909    //vgnprtlstation.dff
#define OBJ_VGNPRTLSTATION_01      6910    //vgnprtlstation_01.dff
#define OBJ_VGSNRAILROAD02         6912    //vgsNrailroad02.dff
#define OBJ_VGSNRAILROAD03         6913    //vgsNrailroad03.dff
#define OBJ_VGSNRAILROAD05         6914    //vgsNrailroad05.dff
#define OBJ_VGSNRAILROAD12         6915    //vgsNrailroad12.dff
#define OBJ_VEGASNEDGE07           6916    //VegasNedge07.dff
#define OBJ_VGSNRAILROAD25         6917    //vgsNrailroad25.dff
#define OBJ_VGNLOWBUILD01          6919    //vgnlowbuild01.dff
#define OBJ_VGNLOWBUILD11          6920    //vgnlowbuild11.dff
#define OBJ_VGNLOWBUILD12          6921    //vgnlowbuild12.dff
#define OBJ_VGNLOWBUILD13          6922    //vgnlowbuild13.dff
#define OBJ_VGNLOWBUILD14          6923    //vgnlowbuild14.dff
#define OBJ_VGNLOWBUILD21          6924    //vgnlowbuild21.dff
#define OBJ_VGNLOWBUILD235         6925    //vgnlowbuild235.dff
#define OBJ_VGNHSEING68            6926    //vgnhseing68.dff
#define OBJ_VEGASPLANT03           6928    //vegasplant03.dff
#define OBJ_VEGASPLANT04           6929    //vegasplant04.dff
#define OBJ_VEGASPLANT05           6930    //vegasplant05.dff
#define OBJ_VEGASPLANT01           6931    //vegasplant01.dff
#define OBJ_VEGASPLANT07           6932    //vegasplant07.dff
#define OBJ_VEGASPLANT08           6933    //vegasplant08.dff
#define OBJ_VEGASPLANT09           6934    //vegasplant09.dff
#define OBJ_VGNSHOPNMALL02         6944    //vgnshopnmall02.dff
#define OBJ_VEGASNROAD0711         6945    //VegasNroad0711.dff
#define OBJ_VGNWALGREN1            6946    //vgnwalgren1.dff
#define OBJ_VGNMALL258             6947    //vgnmall258.dff
#define OBJ_VEGASNEDGE08           6948    //VegasNedge08.dff
#define OBJ_VEGASNEDGE09           6949    //VegasNedge09.dff
#define OBJ_VEGASNROAD096          6950    //vegasNroad096.dff
#define OBJ_VEGASNROAD032          6951    //VegasNroad032.dff
#define OBJ_VEGASNROAD027          6952    //VegasNroad027.dff
#define OBJ_VEGASNROAD026          6953    //VegasNroad026.dff
#define OBJ_VROCKGLASS             6954    //vrockglass.dff
#define OBJ_VGNLOWWALL03           6955    //vgnlowwall03.dff
#define OBJ_VEGASNROAD712          6956    //VegasNroad712.dff
