/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//levelmap.ide
#define OBJ_LIB_STREET09           3890    //lib_street09.dff
#define OBJ_LIB_STREET08           3891    //lib_street08.dff
#define OBJ_LIB_STREET10           3892    //lib_street10.dff
#define OBJ_LIB_STREET05           3893    //lib_street05.dff
#define OBJ_LIB_STREET11           3894    //lib_street11.dff
#define OBJ_LIB_STREET14           3895    //lib_street14.dff
#define OBJ_LIB_STREET03           3897    //lib_street03.dff
#define OBJ_LIB_STREET15           3898    //lib_street15.dff
#define OBJ_LIB_STREET04           3899    //lib_street04.dff
#define OBJ_LIB_STREET12           3900    //lib_street12.dff
#define OBJ_LIB_STREET16           3902    //lib_street16.dff
#define OBJ_LIB_STREET07           3903    //lib_street07.dff
#define OBJ_LIB_STREET02           3905    //lib_street02.dff
#define OBJ_LIB_STREET01           3906    //lib_street01.dff
#define OBJ_LIB_STREET06           3907    //lib_street06.dff
#define OBJ_TRACKSHAD05            3910    //trackshad05.dff
#define OBJ_LIB_STREET13           3911    //lib_street13.dff
#define OBJ_SNOWOVER02             3914    //snowover02.dff
#define OBJ_SNOWOVER03             3915    //snowover03.dff
#define OBJ_SNOWOVER04             3916    //snowover04.dff
#define OBJ_LIB_STREET17           3917    //lib_street17.dff
#define OBJ_SNOWOVER01             3918    //snowover01.dff
#define OBJ_LIB_MAIN_BISTROTOP     3919    //lib_main_bistrotop.dff
#define OBJ_LIB_VEG3               3920    //lib_veg3.dff
#define OBJ_LIB_COUNCHS            3921    //lib_counchs.dff
#define OBJ_REST_CHAIR2            3922    //rest_chair2.dff
#define OBJ_LIBSTREETFAR           3923    //libstreetfar.dff
#define OBJ_PLAYROOM               3924    //playroom.dff
#define OBJ_BRIDGE_1               3925    //bridge_1.dff
#define OBJ_D_SIGN                 3926    //d_sign.dff
#define OBJ_D_SIGN01               3927    //d_sign01.dff
#define OBJ_HELIPAD                3928    //helipad.dff
#define OBJ_D_ROCK                 3929    //d_rock.dff
#define OBJ_D_ROCK01               3930    //d_rock01.dff
#define OBJ_D_ROCK02               3931    //d_rock02.dff
#define OBJ_HANGER                 3932    //hanger.dff
#define OBJ_FAKE_SKY               3933    //fake_sky.dff
#define OBJ_HELIPAD01              3934    //helipad01.dff
#define OBJ_STATUE                 3935    //statue.dff
#define OBJ_BWIRE_FENCE            3936    //bwire_fence.dff
#define OBJ_BWIRE_FENCE01          3937    //bwire_fence01.dff
#define OBJ_RCZERO4_BASE01         3938    //rczero4_base01.dff
#define OBJ_HANGER01               3939    //hanger01.dff
#define OBJ_COMMS01                3940    //comms01.dff
#define OBJ_COMMS02                3941    //comms02.dff
#define OBJ_BISTROBAR              3942    //bistrobar.dff
#define OBJ_MID_STAIRCASE          3943    //mid_staircase.dff
#define OBJ_BISTRO_BLOK            3944    //bistro_blok.dff
#define OBJ_ALPHA_FENCE            3945    //alpha_fence.dff
#define OBJ_PLANTS01               3946    //plants01.dff
#define OBJ_RC_TRACK_A             3947    //rc_track_a.dff
#define OBJ_BISTROGARDEN           3948    //bistrogarden.dff
#define OBJ_RC_TRACK_B             3949    //rc_track_b.dff
#define OBJ_RC_ZERO_C              3950    //rc_zero_c.dff
#define OBJ_RC_WATER               3951    //rc_water.dff
#define OBJ_RC_TRACK_D             3952    //rc_track_d.dff
#define OBJ_RC_TRACK_E             3953    //rc_track_e.dff
#define OBJ_RC_TRACK_F             3954    //rc_track_f.dff
#define OBJ_RC_TRACK_G             3955    //rc_track_g.dff
#define OBJ_RC_TRACK_H             3956    //rc_track_h.dff
#define OBJ_RC_TRACK_I             3957    //rc_track_i.dff
#define OBJ_WAREHOOSEBOXES         3958    //warehooseboxes.dff
#define OBJ_RCZERO_ALPHA           3959    //rczero_alpha.dff
#define OBJ_RCZERO4_BASE02         3960    //rczero4_base02.dff
#define OBJ_BOXKITCH               3961    //Boxkitch.dff
#define OBJ_LEE_PLANE07            3962    //lee_Plane07.dff
#define OBJ_LEE_PLANE08            3963    //lee_Plane08.dff
#define OBJ_LEE_PLANE09            3964    //lee_Plane09.dff
#define OBJ_LEE_OBJECT11           3965    //lee_Object11.dff
#define OBJ_LEE_OBJECT01           3966    //lee_object01.dff
#define OBJ_AIRPORT_INT2           3967    //AIRPORT_int2.dff
#define OBJ_AIRPORT_FRONT          3968    //AIRPORT_FRONT.dff
#define OBJ_BAG_BELT2              3969    //BAG_BELT2.dff
#define OBJ_CJ_CUSTOM_BAR          3970    //CJ_CUSTOM_BAR.dff
#define OBJ_CJ_BAG_RECLAIM         3971    //CJ_BAG_RECLAIM.dff
#define OBJ_MON1                   3972    //mon1.dff
#define OBJ_CJ_BAG_DET             3973    //CJ_BAG_DET.dff
