/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFs.ide
#define OBJ_OC_FLATS_GND01_SFS     10350   //OC_FLATS_GND01_SFS.dff
#define OBJ_GROUNDBIT_10_SFS       10351   //groundbit_10_SFS.dff
#define OBJ_GROUNDBIT_11_SFS       10352   //groundbit_11_SFS.dff
#define OBJ_GROUNDBIT_12_SFS       10353   //groundbit_12_SFS.dff
#define OBJ_GROUNDBIT_13_SFS       10354   //groundbit_13_SFS.dff
#define OBJ_GROUNDBIT_48_SFS       10355   //groundbit_48_SFS.dff
#define OBJ_HASHBURY_01_SFS        10356   //hashbury_01_SFS.dff
#define OBJ_TRANSMITTER_SFS        10357   //transmitter_sfs.dff
#define OBJ_OC_FLATS_GND02_SFS     10358   //OC_FLATS_GND02_SFS.dff
#define OBJ_SFSHILL02              10359   //sfshill02.dff
#define OBJ_SFSHILL03              10360   //sfshill03.dff
#define OBJ_SFSHILL04              10361   //sfshill04.dff
#define OBJ_SFSHILL05              10362   //sfshill05.dff
#define OBJ_SFSHILL06              10363   //sfshill06.dff
#define OBJ_SFSHILL07              10364   //sfshill07.dff
#define OBJ_ROADBIT21_SFS          10365   //roadbit21_SFS.dff
#define OBJ_GOLFTUNNEL1_SFS        10366   //golftunnel1_SFS.dff
#define OBJ_ROADBIT38_SFS          10367   //roadbit38_SFS.dff
#define OBJ_CATHEDRAL_SFS          10368   //cathedral_SFS.dff
#define OBJ_SMALLSHOP_10_SFS08     10369   //smallshop_10_SFS08.dff
#define OBJ_ALLEY1_SFS             10370   //alley1_SFS.dff
#define OBJ_ALLEY1_SFS01           10371   //alley1_SFS01.dff
#define OBJ_ALLEY2_SFS01           10372   //alley2_SFS01.dff
#define OBJ_ALLEY2_SFS02           10373   //alley2_SFS02.dff
#define OBJ_ALLEY2_SFS04           10374   //alley2_SFS04.dff
#define OBJ_SUBSHOP_SFS            10375   //subshop_SFS.dff
#define OBJ_SUBSHOP2_SFS           10376   //subshop2_SFS.dff
#define OBJ_CITYHALL_SFS           10377   //cityhall_SFS.dff
#define OBJ_CTIYHALLSQUARE_SFS     10378   //ctiyhallsquare_SFS.dff
#define OBJ_CITYHALL2_SFS          10379   //cityhall2_SFS.dff
#define OBJ_CITYHALL2_SFS01        10380   //cityhall2_SFS01.dff
#define OBJ_ARTGALLERY_SFS         10381   //artgallery_SFS.dff
#define OBJ_ALLEYFUCKINGWAY_SFS    10382   //alleyfuckingway_SFS.dff
#define OBJ_SUBSHOPS3_SFS          10383   //subshops3_SFS.dff
#define OBJ_CITYHALLSQ_SFS         10384   //cityhallsq_SFS.dff
#define OBJ_BBGROUNDBIT_SFS        10385   //bbgroundbit_SFS.dff
#define OBJ_SFSHILL09              10386   //sfshill09.dff
#define OBJ_CUNTWLAND22_SFS        10387   //cuntwland22_SFS.dff
#define OBJ_TEMPOBJ_SFS02          10388   //tempobj_SFS02.dff
#define OBJ_MISSION_07_SFS         10389   //mission_07_SFS.dff
#define OBJ_MISSION_12_SFS         10390   //mission_12_SFS.dff
#define OBJ_MISSION_14_SFS         10391   //mission_14_SFS.dff
#define OBJ_SMALLSHOP_10_SFS07     10392   //smallshop_10_SFS07.dff
#define OBJ_SCUM_SFS01             10393   //scum_SFS01.dff
#define OBJ_PLOT1_SFS              10394   //plot1_SFS.dff
#define OBJ_MISSION_13_SFS         10395   //mission_13_SFS.dff
#define OBJ_HC_TENFENCE_SFS        10396   //hc_tenfence_SFS.dff
#define OBJ_HC_STADLIGHT1_SFS      10397   //hc_stadlight1_SFS.dff
#define OBJ_HEALTHCLUB_SFS         10398   //healthclub_SFS.dff
#define OBJ_HEALTHCL69_SFS         10399   //healthcl69_SFS.dff
#define OBJ_HC_GROUNDS02_SFS       10400   //hc_grounds02_SFS.dff
#define OBJ_HC_SHED02_SFS          10401   //hc_shed02_SFS.dff
#define OBJ_HC_SECFENCE_SFS        10402   //hc_secfence_SFS.dff
#define OBJ_HC_TRACK02_SFS         10403   //hc_track02_SFS.dff
#define OBJ_HC_LAYBYLAND_SFS       10404   //hc_laybyland_SFS.dff
#define OBJ_HC_GOLFCRSE02_SFS      10405   //hc_golfcrse02_SFS.dff
#define OBJ_HC_GROUNDS04_SFS       10406   //hc_grounds04_SFS.dff
#define OBJ_HC_GOLFCRSE03_SFS      10407   //hc_golfcrse03_SFS.dff
#define OBJ_HC_GOLFCRSE05_SFS      10408   //hc_golfcrse05_SFS.dff
#define OBJ_HC_GOLFCRSE09_SFS      10409   //hc_golfcrse09_SFS.dff
#define OBJ_HC_GOLFCRSE10_SFS      10410   //hc_golfcrse10_SFS.dff
#define OBJ_SHITEYBIT_SFS          10411   //shiteybit_SFS.dff
#define OBJ_POSHOTEL1_SFS          10412   //poshotel1_SFS.dff
#define OBJ_GROUNDBIT_09_SFS       10413   //groundbit_09_SFS.dff
#define OBJ_OC_FLATS_GND03_SFS     10414   //OC_FLATS_GND03_SFS.dff
#define OBJ_OC_FLATS_GND17_SFS     10415   //OC_FLATS_GND17_SFS.dff
#define OBJ_OC_FLATS_GND16_SFS     10416   //OC_FLATS_GND16_SFS.dff
#define OBJ_OC_FLATS_GND06_SFS     10417   //OC_FLATS_GND06_SFS.dff
#define OBJ_SFSHILL13              10418   //sfshill13.dff
#define OBJ_OC_FLATS_GND07_SFS     10419   //OC_FLATS_GND07_SFS.dff
#define OBJ_OC_FLATS_GND08_SFS     10420   //OC_FLATS_GND08_SFS.dff
#define OBJ_OC_FLATS_GND09_SFS     10421   //OC_FLATS_GND09_SFS.dff
#define OBJ_OC_FLATS_GND19_SFS     10422   //OC_FLATS_GND19_SFS.dff
#define OBJ_MISSION_15_SFS         10423   //mission_15_SFS.dff
#define OBJ_ROADSSFS01             10424   //ROADSsfs01.dff
#define OBJ_TEMPHOTEL1_SFS         10425   //temphotel1_sfs.dff
#define OBJ_BACKROAD_SFS           10426   //backroad_SFS.dff
#define OBJ_HAIGHT_52_SFS          10427   //haight_52_SFS.dff
#define OBJ_HASHBLOCK1_02_SFS      10428   //hashblock1_02_SFS.dff
#define OBJ_HASHBLOCK1_10_SFS      10429   //hashblock1_10_SFS.dff
#define OBJ_HASHBLOCK1_08_SFS      10430   //hashblock1_08_SFS.dff
#define OBJ_HASHBURY_03_SFS        10431   //hashbury_03_SFS.dff
#define OBJ_HAIGHT_17_SFS          10432   //haight_17_SFS.dff
#define OBJ_HASHBURY_04_SFS        10433   //hashbury_04_SFS.dff
#define OBJ_HASHBURY_05_SFS        10434   //hashbury_05_SFS.dff
#define OBJ_SHOPPIE6_SFS04         10435   //shoppie6_SFS04.dff
#define OBJ_HASHBLOCK1_09_SFS      10436   //hashblock1_09_SFS.dff
#define OBJ_HASHFENCE_09_SFS       10437   //hashfence_09_SFS.dff
#define OBJ_HASHBURY_07_SFS        10438   //hashbury_07_SFS.dff
#define OBJ_HASHBURY_08_SFS        10439   //hashbury_08_SFS.dff
