/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LaWn.ide
#define OBJ_ROAD_LAWN23            5703    //road_lawn23.dff
#define OBJ_ARCHWINDSHOP_LAW       5704    //archwindshop_laW.dff
#define OBJ_FILMSTUD1              5705    //filmstud1.dff
#define OBJ_STUDIOBLD03_LAW        5706    //studiobld03_laW.dff
#define OBJ_ROAD_LAWN03            5707    //road_lawn03.dff
#define OBJ_HOSPITAL_LAW           5708    //hospital_law.dff
#define OBJ_SHOP03_LAW01           5709    //shop03_laW01.dff
#define OBJ_CEM01_LAW              5710    //cem01_law.dff
#define OBJ_CEM02_LAW              5711    //cem02_law.dff
#define OBJ_CEMINT01_LAW           5712    //cemint01_law.dff
#define OBJ_GRAVE01_LAW            5713    //grave01_law.dff
#define OBJ_GRAVE03_LAW            5714    //grave03_law.dff
#define OBJ_GRAVE08_LAW            5715    //grave08_law.dff
#define OBJ_MANNS01_LAWN           5716    //manns01_LAwN.dff
#define OBJ_SUNSET20_LAWN          5717    //Sunset20_LAwN.dff
#define OBJ_SUNSET16_LAWN          5718    //sunset16_LAwN.dff
#define OBJ_HOLBUILD01_LAW         5719    //holbuild01_law.dff
#define OBJ_HOLBUILD02_LAW         5720    //holbuild02_law.dff
#define OBJ_HOLBUILD04_LAW         5721    //holbuild04_law.dff
#define OBJ_MANNS05_LAWN           5722    //manns05_LAwN.dff
#define OBJ_MANNS04_LAWN           5723    //manns04_LAwN.dff
#define OBJ_HOLSIGN03N_LAW         5724    //holsign03n_law.dff
#define OBJ_HOLPACIFIC2_LAW        5725    //holpacific2_law.dff
#define OBJ_LAWN_HOLBUILD21        5726    //Lawn_holbuild21.dff
#define OBJ_HOLBUILD10_LAW         5727    //holbuild10_law.dff
#define OBJ_DUMMYBUILD46_LAW       5728    //dummybuild46_law.dff
#define OBJ_MELBLOK02_LAWN         5729    //MelBlok02_LAwN.dff
#define OBJ_MELBLOK03_LAWN         5730    //MelBlok03_LAwN.dff
#define OBJ_MELBLOK05_LAWN         5731    //MelBlok05_LAwN.dff
#define OBJ_DONUT01_LAWN           5732    //donut01_LAwN.dff
#define OBJ_MELROSE07_LAW          5733    //melrose07_law.dff
#define OBJ_MELROSE09_LAW          5734    //melrose09_law.dff
#define OBJ_STUDOFF_LAW            5735    //studoff_law.dff
#define OBJ_STUDOFF02_LAW          5736    //studoff02_law.dff
#define OBJ_ARCHSHOP07_LAW02       5737    //archshop07_laW02.dff
#define OBJ_HOTHOL02_LAW01         5738    //hothol02_law01.dff
#define OBJ_TALLBLDGRN             5739    //tallbldgrn.dff
#define OBJ_TALL2                  5740    //tall2.dff
#define OBJ_LAWNSTUFF21            5741    //lawnstuff21.dff
#define OBJ_LAWNSTUFF15            5742    //lawnstuff15.dff
#define OBJ_GRNDLAWN               5743    //grndLAwn.dff
