/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//vegaxref.ide
#define OBJ_VEGASBOOTH01           3430    //vegasbooth01.dff
#define OBJ_VGSCLUBOX01            3431    //vgsclubox01.dff
#define OBJ_HTLCNPY02_LVS          3432    //htlcnpy02_lvs.dff
#define OBJ_HTLCNPY01_LVS          3433    //htlcnpy01_lvs.dff
#define OBJ_SKLLSGN01_LVS          3434    //skllsgn01_lvs.dff
#define OBJ_MOTEL01SGN_LVS         3435    //motel01sgn_lvs.dff
#define OBJ_MOTEL03_LVS            3436    //motel03_lvs.dff
#define OBJ_BALLYPLLR01_LVS        3437    //ballypllr01_lvs.dff
#define OBJ_BALLYRING01_LVS        3438    //ballyring01_lvs.dff
#define OBJ_APRTREE01_LVS          3439    //aprtree01_lvs.dff
#define OBJ_ARPTPILLAR01_LVS       3440    //arptpillar01_lvs.dff
#define OBJ_LUXORPILLAR02_LVS      3441    //luxorpillar02_lvs.dff
#define OBJ_VEGASXREXHSE1          3442    //vegasxrexhse1.dff
#define OBJ_VEGASXREXHSE2          3443    //vegasxrexhse2.dff
#define OBJ_SHABBYHOUSE02_LVS      3444    //shabbyhouse02_lvs.dff
#define OBJ_VEGASXREXHSE08         3445    //vegasxrexhse08.dff
#define OBJ_VEGASXREXHSE10         3446    //vegasxrexhse10.dff
#define OBJ_VGSTLGRAPHPOLE         3447    //vgstlgraphpole.dff
#define OBJ_SHAMCPRKIN             3448    //shamcprkin.dff
#define OBJ_VEGASHSENEW1           3449    //vegashsenew1.dff
#define OBJ_VEGASHSEPLOT1          3450    //vegashseplot1.dff
#define OBJ_VEGASHSENEW2           3451    //vegashsenew2.dff
#define OBJ_BBALLINTVGN1           3452    //bballintvgn1.dff
#define OBJ_BBALLINTVGN2           3453    //bballintvgn2.dff
#define OBJ_VGNHSEING15            3454    //vgnhseing15.dff
#define OBJ_VGNHSEBLK1             3455    //vgnhseblk1.dff
#define OBJ_VGNHSEBLK3             3456    //vgnhseblk3.dff
#define OBJ_VGNHSEBLK2             3457    //vgnhseblk2.dff
#define OBJ_VGNCARSHADE1           3458    //vgncarshade1.dff
#define OBJ_VGNTELEPOLE1           3459    //vgntelepole1.dff
#define OBJ_VEGASLAMPOST           3460    //vegaslampost.dff
#define OBJ_TIKITORCH01_LVS        3461    //tikitorch01_lvs.dff
#define OBJ_CSRANGEL_LVS           3462    //csrangel_lvs.dff
#define OBJ_VEGASLAMPOST2          3463    //vegaslampost2.dff
#define OBJ_SHABBYHOUSE03_LVS      3464    //shabbyhouse03_lvs.dff
#define OBJ_VEGSPETROLPUMP         3465    //vegspetrolpump.dff
#define OBJ_SHABBYHOUSE01_LVS      3466    //shabbyhouse01_lvs.dff
#define OBJ_VEGSTREETSIGN1         3467    //vegstreetsign1.dff
#define OBJ_VEGSTREETSIGN2         3468    //vegstreetsign2.dff
#define OBJ_VEGENMOTEL1            3469    //vegenmotel1.dff
#define OBJ_VEGASAIRCON1           3470    //vegasaircon1.dff
#define OBJ_VGSCHINALION1          3471    //vgschinalion1.dff
#define OBJ_CIRCUSLAMPOST03        3472    //circuslampost03.dff
#define OBJ_VEGENMOTEL12           3473    //vegenmotel12.dff
#define OBJ_FREIGHTCRANE1          3474    //Freightcrane1.dff
#define OBJ_VGSN_FNCELEC_PST       3475    //vgsn_fncelec_pst.dff
#define OBJ_VEGASXREXHSE09         3483    //vegasxrexhse09.dff
#define OBJ_VEGASXREXHSE03         3484    //vegasxrexhse03.dff
#define OBJ_VEGASXREXHSE04         3485    //vegasxrexhse04.dff
#define OBJ_VEGASXREXHSE05         3486    //vegasxrexhse05.dff
#define OBJ_VEGASXREXHSE06         3487    //vegasxrexhse06.dff
#define OBJ_VEGASXREXHSE07         3488    //vegasxrexhse07.dff
#define OBJ_HANGAR1_08_LVS         3489    //HANGAR1_08_LVS.dff
#define OBJ_VEGASS_HANGER2         3491    //vegasS_hanger2.dff
#define OBJ_VGSN_CARPARK01         3493    //vgsn_carpark01.dff
#define OBJ_LUXORPILLAR04_LVS      3494    //luxorpillar04_lvs.dff
#define OBJ_VGSXREFBBALLNET        3496    //vgsxrefbballnet.dff
#define OBJ_VGSXREFBBALLNET2       3497    //vgsxrefbballnet2.dff
#define OBJ_WDPILLAR01_LVS         3498    //wdpillar01_lvs.dff
#define OBJ_WDPILLAR02_LVS         3499    //wdpillar02_lvs.dff
#define OBJ_VGSXREFPARTM1          3501    //vgsxrefpartm1.dff
#define OBJ_VGSN_CON_TUBE          3502    //vgsN_con_tube.dff
#define OBJ_VGSNSCFFPLE            3503    //vgsNscffple.dff
#define OBJ_VGSN_PORTALOO          3504    //vgsN_portaloo.dff
#define OBJ_VGSN_NITREE_Y01        3505    //VgsN_nitree_y01.dff
#define OBJ_VGSN_NITREE_Y02        3506    //VgsN_nitree_y02.dff
#define OBJ_VGSN_NITREE_G01        3507    //VgsN_nitree_g01.dff
#define OBJ_VGSN_NITREE_G02        3508    //VgsN_nitree_g02.dff
#define OBJ_VGSN_NITREE_R01        3509    //VgsN_nitree_r01.dff
#define OBJ_VGSN_NITREE_R02        3510    //VgsN_nitree_r02.dff
#define OBJ_VGSN_NITREE_B01        3511    //VgsN_nitree_b01.dff
#define OBJ_VGSN_NITREE_B02        3512    //VgsN_nitree_b02.dff
#define OBJ_VGS_ROADSIGN1          3513    //vgs_roadsign1.dff
#define OBJ_VGS_ROADSIGN02         3514    //vgs_roadsign02.dff
#define OBJ_VGSFOUNTAIN            3515    //vgsfountain.dff
#define OBJ_VGSSTRIPTLIGHTS1       3516    //vgsstriptlights1.dff
#define OBJ_CEASERTREE02_LVS       3517    //ceasertree02_lvs.dff
#define OBJ_VGSN_ROOFLITY          3518    //vgsN_rooflity.dff
#define OBJ_VGSN_ROOFLITB          3519    //vgsN_rooflitb.dff
#define OBJ_VGSN_FLWRBDSM          3520    //vgsN_flwrbdsm.dff
#define OBJ_VGSN_RBSTIFF           3521    //vgsn_RBStiff.dff
#define OBJ_VGSN_FLWBDCRB          3522    //vgsn_flwbdcrb.dff
#define OBJ_SKULLPILLAR01_LVS      3524    //skullpillar01_lvs.dff
#define OBJ_EXBRTORCH01            3525    //exbrtorch01.dff
#define OBJ_VEGASAIRPORTLIGHT      3526    //vegasairportlight.dff
#define OBJ_VGSEDRAGON             3528    //vgsEdragon.dff
#define OBJ_VGSN_CONSTRBEAM        3529    //vgsN_constrbeam.dff
#define OBJ_VGSN_CONSTRBEAM2       3530    //vgsN_constrbeam2.dff
#define OBJ_TRDFLWRBEDQ            3531    //trdflwrbedq.dff
#define OBJ_TRIADBUSH              3532    //triadbush.dff
#define OBJ_TRDPILLAR01            3533    //trdpillar01.dff
#define OBJ_TRDLAMP01              3534    //trdlamp01.dff
#define OBJ_VGSN_FNCELEC_MSH       3550    //vgsn_fncelec_msh.dff
#define OBJ_VISAGESIGN04           3554    //visagesign04.dff
