/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//counxref.ide
#define OBJ_TRAILER_LARGE1_01      3167    //trailer_large1_01.dff
#define OBJ_TRAILER2_01            3168    //trailer2_01.dff
#define OBJ_TRAILER_LARGE2_01      3169    //trailer_large2_01.dff
