/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//propext.ide
#define OBJ_BUST_CABINET_4         910     //BUST_CABINET_4.dff
#define OBJ_BUST_CABINET_1         911     //BUST_CABINET_1.dff
#define OBJ_BUST_CABINET_2         912     //BUST_CABINET_2.dff
#define OBJ_BUST_CABINET_3         913     //BUST_CABINET_3.dff
#define OBJ_GRILL                  914     //GRILL.dff
#define OBJ_AIRCON_FAN             915     //AIRCON_FAN.dff
#define OBJ_FRUITCRATE2            916     //FRUITCRATE2.dff
#define OBJ_FRUITCRATE1            917     //FRUITCRATE1.dff
#define OBJ_CJ_FLAME_DRUM          918     //CJ_FLAME_Drum.dff
#define OBJ_AIRCON                 919     //AIRCON.dff
#define OBJ_Y_GENERATOR            920     //Y_GENERATOR.dff
#define OBJ_CJ_IND_LIGHT           921     //CJ_IND_LIGHT.dff
#define OBJ_PACKING_CARATES1       922     //Packing_carates1.dff
#define OBJ_PACKING_CARATES2       923     //Packing_carates2.dff
#define OBJ_FRUITCRATE3            924     //FRUITCRATE3.dff
#define OBJ_RACK2                  925     //RACK2.dff
#define OBJ_RUBBISH_BOX2           926     //RUBBISH_BOX2.dff
#define OBJ_PIPING_DETAIL          927     //Piping_Detail.dff
#define OBJ_RUBBISH_BOX1           928     //RUBBISH_BOX1.dff
#define OBJ_GENERATOR              929     //GENERATOR.dff
#define OBJ_O2_BOTTLES             930     //O2_Bottles.dff
#define OBJ_RACK3                  931     //RACK3.dff
#define OBJ_H_WHEELCHAIR           932     //H_WHEELCHAIR.dff
#define OBJ_CJ_CABLEROLL           933     //CJ_CABLEROLL.dff
#define OBJ_GENERATOR_BIG          934     //GENERATOR_BIG.dff
#define OBJ_CJ_DRUM                935     //CJ_Drum.dff
#define OBJ_CJ_DF_WORKTOP_2        936     //CJ_DF_WORKTOP_2.dff
#define OBJ_CJ_DF_WORKTOP          937     //CJ_DF_WORKTOP.dff
#define OBJ_CJ_DF_LIGHT            938     //CJ_DF_LIGHT.dff
#define OBJ_CJ_DF_UNIT             939     //CJ_DF_UNIT.dff
#define OBJ_CJ_DF_LIGHT_2          940     //CJ_DF_LIGHT_2.dff
#define OBJ_CJ_DF_WORKTOP_3        941     //CJ_DF_WORKTOP_3.dff
#define OBJ_CJ_DF_UNIT_2           942     //CJ_DF_UNIT_2.dff
#define OBJ_GENERATOR_LOW          943     //GENERATOR_LOW.dff
#define OBJ_PACKING_CARATES04      944     //Packing_carates04.dff
#define OBJ_WS_CF_LAMPS            945     //WS_CF_LAMPS.dff
#define OBJ_BSKBALL_LAX            946     //bskball_lax.dff
#define OBJ_BSKBALLHUB_LAX01       947     //bskballhub_lax01.dff
#define OBJ_PLANT_POT_10           948     //Plant_Pot_10.dff
#define OBJ_PLANT_POT_4            949     //Plant_Pot_4.dff
#define OBJ_PLANT_POT_12           950     //Plant_Pot_12.dff
#define OBJ_CJ_VIEW_TELE2          951     //CJ_VIEW_TELE2.dff
#define OBJ_GENERATOR_BIG_D        952     //GENERATOR_BIG_d.dff
#define OBJ_CJ_OYSTER              953     //CJ_OYSTER.dff
#define OBJ_CJ_HORSE_SHOE          954     //cj_horse_Shoe.dff
#define OBJ_CJ_EXT_SPRUNK          955     //CJ_EXT_SPRUNK.dff
#define OBJ_CJ_EXT_CANDY           956     //CJ_EXT_CANDY.dff
#define OBJ_CJ_LIGHT_FIX_EXT       957     //CJ_LIGHT_FIT_EXT.dff
#define OBJ_CJ_CHIP_MAKER          958     //CJ_CHIP_MAKER.dff
#define OBJ_CJ_CHIP_MAKER_BITS     959     //CJ_CHIP_MAKER_BITS.dff
#define OBJ_CJ_ARM_CRATE           960     //CJ_ARM_CRATE.dff
#define OBJ_CJ_ARM_CRATE_TOP       961     //CJ_ARM_CRATE_top.dff
#define OBJ_CJ_T_TICKET_PED        962     //CJ_T_TICKET_PED.dff
#define OBJ_CJ_T_TICKET            963     //CJ_T_TICKET.dff
#define OBJ_CJ_METAL_CRATE         964     //CJ_METAL_CRATE.dff