/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//default.ide
#define OBJ_GUN_DILDO1             321     //gun_dildo1.dff
#define OBJ_GUN_DILDO2             322     //gun_dildo2.dff
#define OBJ_GUN_VIBE1              323     //gun_vibe1.dff
#define OBJ_GUN_VIBE2              324     //gun_vibe2.dff
#define OBJ_FLOWERA                325     //flowera.dff
#define OBJ_GUN_CANE               326     //gun_cane.dff
#define OBJ_GUN_BOXWEE             327     //gun_boxwee.dff
#define OBJ_GUN_BOXBIG             328     //gun_boxbig.dff
#define OBJ_CELLPHONE              330     //cellphone.dff
#define OBJ_BRASSKNUCKLE           331     //brassknuckle.dff
#define OBJ_GOLFCLUB               333     //golfclub.dff
#define OBJ_NITESTICK              334     //nitestick.dff
#define OBJ_KNIFECUR               335     //knifecur.dff
#define OBJ_BAT                    336     //bat.dff
#define OBJ_SHOVEL                 337     //shovel.dff
#define OBJ_POOLCUE                338     //poolcue.dff
#define OBJ_KATANA                 339     //katana.dff
#define OBJ_CHNSAW                 341     //chnsaw.dff
#define OBJ_GRENADE                342     //grenade.dff
#define OBJ_TEARGAS                343     //teargas.dff
#define OBJ_MOLOTOV                344     //molotov.dff
#define OBJ_MISSILE                345     //missile.dff
#define OBJ_COLT45                 346     //colt45.dff
#define OBJ_SILENCED               347     //silenced.dff
#define OBJ_DESERT_EAGLE           348     //desert_eagle.dff
#define OBJ_CHROMEGUN              349     //chromegun.dff
#define OBJ_SAWNOFF                350     //sawnoff.dff
#define OBJ_SHOTGSPA               351     //shotgspa.dff
#define OBJ_MICRO_UZI              352     //micro_uzi.dff
#define OBJ_MP5LNG                 353     //mp5lng.dff
#define OBJ_FLARE                  354     //flare.dff
#define OBJ_AK47                   355     //ak47.dff
#define OBJ_M4                     356     //m4.dff
#define OBJ_CUNTGUN                357     //cuntgun.dff
#define OBJ_SNIPER                 358     //sniper.dff
#define OBJ_ROCKETLA               359     //rocketla.dff
#define OBJ_HEATSEEK               360     //heatseek.dff
#define OBJ_FLAME                  361     //flame.dff
#define OBJ_MINIGUN                362     //minigun.dff
#define OBJ_SATCHEL                363     //satchel.dff
#define OBJ_BOMB                   364     //bomb.dff
#define OBJ_SPRAYCAN               365     //spraycan.dff
#define OBJ_FIRE_EX                366     //fire_ex.dff
#define OBJ_CAMERA                 367     //camera.dff
#define OBJ_NVGOGGLES              368     //nvgoggles.dff
#define OBJ_IRGOGGLES              369     //irgoggles.dff
#define OBJ_JETPACK                370     //jetpack.dff
#define OBJ_GUN_PARA               371     //gun_para.dff
#define OBJ_TEC9                   372     //tec9.dff
#define OBJ_ARMOUR                 373     //armour.dff
