/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//levelxre.ide
#define OBJ_XREF_GARAGEDOOR        2885    //xref_garagedoor.dff
#define OBJ_SEC_KEYPAD             2886    //sec_keypad.dff
#define OBJ_A51_SPOTBULB           2887    //a51_spotbulb.dff
#define OBJ_A51_SPOTHOUSING        2888    //a51_spothousing.dff
#define OBJ_A51_SPOTBASE           2889    //a51_spotbase.dff
#define OBJ_KMB_SKIP               2890    //kmb_skip.dff
#define OBJ_KMB_PACKET             2891    //kmb_packet.dff
#define OBJ_TEMP_STINGER           2892    //temp_stinger.dff
#define OBJ_KMB_RAMP               2893    //kmb_ramp.dff
#define OBJ_KMB_RHYMESBOOK         2894    //kmb_rhymesbook.dff
#define OBJ_FUN_FLOWER_LAW         2895    //fun_flower_law.dff
#define OBJ_CASKET_LAW             2896    //casket_law.dff
#define OBJ_FUNTARP_LAW            2897    //funtarp_law.dff
#define OBJ_FUNTURF_LAW            2898    //funturf_law.dff
#define OBJ_TEMP_STINGER2          2899    //temp_stinger2.dff
#define OBJ_TEMP_CARDBOX           2900    //temp_cardbox.dff
#define OBJ_KMB_MARIJUANA          2901    //kmb_marijuana.dff
#define OBJ_KMB_SMOKECAN           2902    //kmb_smokecan.dff
#define OBJ_KMB_PARACHUTE          2903    //kmb_parachute.dff
#define OBJ_WAREHOUSE_DOOR1        2904    //warehouse_door1.dff
#define OBJ_KMB_DEADLEG            2905    //kmb_deadleg.dff
#define OBJ_KMB_DEADARM            2906    //kmb_deadarm.dff
#define OBJ_KMB_DEADTORSO          2907    //kmb_deadtorso.dff
#define OBJ_KMB_DEADHEAD           2908    //kmb_deadhead.dff
#define OBJ_KMB_FRONTGATE          2909    //kmb_frontgate.dff
#define OBJ_TEMP_ROAD              2910    //temp_road.dff
#define OBJ_KMB_PETROLDOOR         2911    //kmb_petroldoor.dff
#define OBJ_TEMP_CRATE1            2912    //temp_crate1.dff
#define OBJ_KMB_BPRESS             2913    //kmb_bpress.dff
#define OBJ_KMB_RCFLAG             2914    //kmb_rcflag.dff
#define OBJ_KMB_DUMBELL2           2915    //kmb_dumbbell2.dff
#define OBJ_KMB_DUMBELL            2916    //kmb_dumbbell.dff
#define OBJ_A51_CRANE              2917    //a51_crane.dff
#define OBJ_KMB_MINE               2918    //kmb_mine.dff
#define OBJ_KMB_HOLDALL            2919    //kmb_holdall.dff
#define OBJ_POLICE_BARRIER         2920    //police_barrier.dff
#define OBJ_KMB_CAM                2921    //kmb_cam.dff
#define OBJ_KMB_KEYPAD             2922    //kmb_keypad.dff
#define OBJ_BOTTLE_BANK            2923    //bottle_bank.dff
#define OBJ_KMB_CRASH3DOOR         2924    //kmb_crash3door.dff
#define OBJ_DYNO_BOX_B             2925    //dyno_box_B.dff
#define OBJ_DYNO_BOX_A             2926    //dyno_box_A.dff
#define OBJ_A51_BLASTDOORR         2927    //a51_blastdoorR.dff
#define OBJ_A51_INTDOOR            2928    //a51_intdoor.dff
#define OBJ_A51_BLASTDOORL         2929    //a51_blastdoorL.dff
#define OBJ_CHINATGATE             2930    //chinaTgate.dff
#define OBJ_KMB_JUMP1              2931    //kmb_jump1.dff
#define OBJ_KMB_CONTAINTER_BLUE    2932    //kmb_container_blue.dff
#define OBJ_POL_COMP_GATE          2933    //pol_comp_gate.dff
#define OBJ_KMB_CONTAINTER_RED     2934    //kmb_container_red.dff
#define OBJ_KMB_CONTAINTER_YEL     2935    //kmb_container_yel.dff
#define OBJ_KMB_ROCK               2936    //kmb_rock.dff
#define OBJ_KMB_PLANK              2937    //kmb_plank.dff
#define OBJ_SHUTTER_VEGAS          2938    //shutter_vegas.dff
#define OBJ_RAMP_BOT               2939    //ramp_bot.dff
#define OBJ_RAMP_TOP               2940    //ramp_top.dff
#define OBJ_TEMP_TILL              2941    //temp_till.dff
#define OBJ_KMB_ATM1               2942    //kmb_atm1.dff
#define OBJ_KMB_ATM2               2943    //kmb_atm2.dff
#define OBJ_FREIGHT_SFW_DOOR       2944    //freight_SFW_door.dff
#define OBJ_KMB_NETTING            2945    //kmb_netting.dff
#define OBJ_CR_DOOR_03             2946    //cr_door_03.dff
