/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2023, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//countryN.ide
#define OBJ_CON_LIGHTH             11420   //con_lighth.dff
#define OBJ_ROADSUPP1_01           11421   //roadsupp1_01.dff
#define OBJ_CON_BR1                11422   //con_br1.dff
#define OBJ_CON_BR2                11423   //con_br2.dff
#define OBJ_CON_TUNLL_SUP03        11424   //con_tunll_sup03.dff
#define OBJ_DES_ADOBEHOOSES1       11425   //des_adobehooses1.dff
#define OBJ_DES_ADOBE03            11426   //des_adobe03.dff
#define OBJ_DES_ADOBECH            11427   //des_adobech.dff
#define OBJ_DES_INDRUIN02          11428   //des_indruin02.dff
#define OBJ_NW_BIT_31              11429   //nw_bit_31.dff
#define OBJ_SW_BIT_13              11430   //sw_bit_13.dff
#define OBJ_DES_TEPEOFF01          11431   //des_tepeoff01.dff
#define OBJ_DES_TEPESIGN01         11432   //des_tepesign01.dff
#define OBJ_ADOBE_HOOSE2           11433   //adobe_hoose2.dff
#define OBJ_DES_INDIANSTORE        11434   //des_indianstore.dff
#define OBJ_DES_INDSIGN1           11435   //des_indsign1.dff
#define OBJ_DES_INDSHOPS1          11436   //des_indshops1.dff
#define OBJ_DES_INDCHFENC          11437   //des_indchfenc.dff
#define OBJ_DES_INDTPFENC          11438   //des_indtpfenc.dff
#define OBJ_DES_WOODBR             11439   //des_woodbr_.dff
#define OBJ_DES_PUEBLO1            11440   //des_pueblo1.dff
#define OBJ_DES_PUEBLO5            11441   //des_pueblo5.dff
#define OBJ_DES_PUEBLO3            11442   //des_pueblo3.dff
#define OBJ_DES_PUEBLO4            11443   //des_pueblo4.dff
#define OBJ_DES_PUEBLO2            11444   //des_pueblo2.dff
#define OBJ_DES_PUEBLO06           11445   //des_pueblo06.dff
#define OBJ_DES_PUEBLO07           11446   //des_pueblo07.dff
#define OBJ_DES_PUEBLO08           11447   //des_pueblo08.dff
#define OBJ_DES_RAILBR_TWR1        11448   //des_railbr_twr1.dff
#define OBJ_DES_NWTSHOP2           11449   //des_nwtshop2.dff
#define OBJ_DES_NWTSHOP07          11450   //des_nwtshop07.dff
#define OBJ_DES_NWSHERRIF          11451   //des_nwsherrif.dff
#define OBJ_DES_NWSHFENC           11452   //des_nwshfenc.dff
#define OBJ_DES_SHERRIFSGN1        11453   //des_sherrifsgn1.dff
#define OBJ_DES_NWMEDCEN           11454   //des_nwmedcen.dff
#define OBJ_DES_MEDCENSGN01        11455   //des_medcensgn01.dff
#define OBJ_DES_NWTSHOP10          11456   //des_nwtshop10.dff
#define OBJ_DES_PUEBLO09           11457   //des_pueblo09.dff
#define OBJ_DES_PUEBLO10           11458   //des_pueblo10.dff
#define OBJ_DES_PUEBLO11           11459   //des_pueblo11.dff
#define OBJ_DES_TELEWIRES03        11460   //des_telewires03.dff
#define OBJ_DES_NWWTOWER           11461   //des_nwwtower.dff
#define OBJ_DES_RAILBRIDGE1        11462   //des_railbridge1.dff
#define OBJ_DES_RAILBR_TWR05       11463   //des_railbr_twr05.dff
#define OBJ_DES_TRAINLINE02        11464   //des_trainline02.dff
#define OBJ_DES_TRAINLINE03        11465   //des_trainline03.dff
#define OBJ_DES_TRAINLINE04        11466   //des_trainline04.dff
#define OBJ_DES_TRAINLINE05        11467   //des_trainline05.dff
#define OBJ_DES_RAILSTRUCT1        11468   //des_railstruct1_.dff
#define OBJ_DES_BULLGRILL          11469   //des_bullgrill_.dff
#define OBJ_DES_BIGBULL            11470   //des_bigbull.dff
#define OBJ_DES_SWTSHOP14          11471   //des_swtshop14.dff
#define OBJ_DES_SWTSTAIRS1         11472   //des_swtstairs1.dff
#define OBJ_DES_SWTFENCE1          11473   //des_swtfence1.dff
#define OBJ_DES_SWTFENCE2          11474   //des_swtfence2.dff
#define OBJ_DES_SWTSHOP02          11475   //des_swtshop02.dff
#define OBJ_SWT_TELINE_02          11476   //swt_teline_02.dff
#define OBJ_SWT_TELINE_03          11477   //swt_teline_03.dff
#define OBJ_SWT_TELINE_01          11478   //swt_teline_01.dff
#define OBJ_DES_NWTFESCAPE         11479   //des_nwtfescape.dff
#define OBJ_DES_NWT_CARPORT        11480   //des_nwt_carport.dff
#define OBJ_DES_RAILFENC1          11481   //des_railfenc1.dff
#define OBJ_DES_RAILFENC2          11482   //des_railfenc2.dff
#define OBJ_DES_RAILJUMP02         11483   //des_railjump02.dff
#define OBJ_DAM_TURBINE_4          11484   //dam_turbine_4.dff
#define OBJ_DAM_TURBINE_3          11485   //dam_turbine_3.dff
#define OBJ_DAM_TURBINE_2          11486   //dam_turbine_2.dff
#define OBJ_DAM_TURBINE_1          11487   //dam_turbine_1.dff
#define OBJ_DAM_STATAREA           11488   //dam_statarea.dff
#define OBJ_DAM_STATUES            11489   //dam_statues.dff
#define OBJ_DES_RANCH              11490   //des_ranch.dff
#define OBJ_DES_RANCHBITS1         11491   //des_ranchbits1.dff
#define OBJ_DES_RSHED1             11492   //des_rshed1_.dff
#define OBJ_DES_RANCHBOT           11493   //des_ranchbot.dff
#define OBJ_DES_RNCHBHOUS          11494   //des_rnchbhous.dff
#define OBJ_DES_RANCHJETTY         11495   //des_ranchjetty.dff
#define OBJ_DES_WJETTY             11496   //des_wjetty.dff
#define OBJ_DES_BAITSHOP           11497   //des_baitshop.dff
#define OBJ_DES_ROCKGP2_27         11498   //des_rockgp2_27.dff
#define OBJ_DES_DINERFENC01        11499   //des_dinerfenc01.dff
#define OBJ_DES_SKELSIGNBUSH       11500   //des_skelsignbush_.dff
