/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//SFn.ide
#define OBJ_ROAD04SFN              9205    //road04sfn.dff
#define OBJ_LAND2_SFN10            9206    //land2_sfN10.dff
#define OBJ_LAND2_SFN01            9207    //land2_sfN01.dff
#define OBJ_LAND2_SFN19            9208    //land2_sfN19.dff
#define OBJ_LAND_SFN06             9209    //land_SFN06.dff
#define OBJ_LAND2_SFN11            9210    //land2_sfN11.dff
#define OBJ_LAND2_SFN09            9211    //land2_sfN09.dff
#define OBJ_LAND2_SFN13            9212    //land2_sfN13.dff
#define OBJ_LAND2_SFN15            9213    //land2_sfN15.dff
#define OBJ_LAND2_SFN12            9214    //land2_sfN12.dff
#define OBJ_LAND2_SFN17            9215    //land2_sfN17.dff
#define OBJ_LAND_SFN13             9216    //land_SFN13.dff
#define OBJ_LAND2_SFN16            9217    //land2_sfN16.dff
#define OBJ_LAND_SFN15             9218    //land_SFN15.dff
#define OBJ_LAND2_SFN14            9219    //land2_sfN14.dff
#define OBJ_VILLA_SFN_CHRIS_01     9220    //Villa_SFN_CHRIS_01.dff
#define OBJ_VILLA_SFN_CHRIS_02     9221    //Villa_SFN_CHRIS_02.dff
#define OBJ_ROAD08SFN              9222    //road08sfn.dff
#define OBJ_LAND_SFN21             9223    //land_sfn21.dff
#define OBJ_COCK_SFN02             9224    //cock_sfn02.dff
#define OBJ_LAND_SFN22             9225    //land_sfn22.dff
#define OBJ_LAND_SFN18             9226    //land_sfn18.dff
#define OBJ_MORESFNSHIT20          9227    //moresfnshit20.dff
#define OBJ_MORESFNSHIT22          9228    //moresfnshit22.dff
#define OBJ_SFN_COAST03            9229    //sfn_coast03.dff
#define OBJ_SFN_COAST01            9230    //sfn_coast01.dff
#define OBJ_ROAD01SFN              9231    //road01sfn.dff
#define OBJ_ROAD06SFN              9232    //road06sfn.dff
#define OBJ_ROAD07SFN              9233    //road07sfn.dff
#define OBJ_LAND_SFN20             9234    //land_sfn20.dff
#define OBJ_LAND2_SFN18            9235    //land2_sfN18.dff
#define OBJ_COCK_SFN07             9236    //cock_sfn07.dff
#define OBJ_LIGHTHOUSE_SFN         9237    //lighhouse_SFN.dff
#define OBJ_MORESFNSHIT28          9238    //moresfnshit28.dff
#define OBJ_TRACK01_SFN            9239    //track01_SFN.dff
#define OBJ_TRACK02_SFN            9240    //track02_SFN.dff
#define OBJ_COPBITS_SFN            9241    //copbits_sfn.dff
#define OBJ_COCK_SFN06             9242    //cock_sfn06.dff
#define OBJ_HRBORBUILD_SFN02       9243    //hrborbuild_SFN02.dff
#define OBJ_HRBORBUILD_SFN01       9244    //hrborbuild_SFN01.dff
#define OBJ_CSTGUARD_SFN01         9245    //cstguard_SFN01.dff
#define OBJ_COCK_SFN09             9246    //cock_sfn09.dff
#define OBJ_HRBRMSTR_SFN01         9247    //hrbrmstr_SFN01.dff
#define OBJ_COCK_SFN08             9248    //cock_sfn08.dff
#define OBJ_BEACH_SFN01            9249    //beach_sfn01.dff
#define OBJ_ROAD02SFN              9250    //road02sfn.dff
#define OBJ_ROAD03SFN              9251    //road03sfn.dff
#define OBJ_ROAD05SFN              9252    //road05sfn.dff
#define OBJ_SFN_COAST04            9253    //sfn_coast04.dff
#define OBJ_CARPARK_SFN01          9254    //carpark_sfn01.dff
#define OBJ_CARPARK_SFN02          9255    //carpark_sfn02.dff
#define OBJ_COCK_SFN14             9256    //cock_sfn14.dff
#define OBJ_SFN_COAST05            9257    //sfn_coast05.dff
#define OBJ_PRESCHOOSML02_SFN      9258    //preshoosml02_SFN.dff
#define OBJ_PRESHOOSBIG02_SFN      9259    //preshoosbig02_SFN.dff
#define OBJ_HRBORBUILD_SFN03       9260    //hrborbuild_SFN03.dff
#define OBJ_LAND_SFN19             9261    //land_sfn19.dff
#define OBJ_HWAY_SFN01             9262    //hway_SFN01.dff
#define OBJ_HWAY_SFN03             9264    //hway_SFN03.dff
#define OBJ_HWAY_SFN04             9265    //hway_SFN04.dff
#define OBJ_HWAY_SFN05             9266    //hway_SFN05.dff
#define OBJ_HWAY_SFN06             9267    //hway_SFN06.dff
#define OBJ_GGBRIDGEEND_SFN        9269    //GGbridgeend_SFN.dff
#define OBJ_PRESHOOSBIG01_SFN01    9270    //preshoosbig01_SFN01.dff
#define OBJ_PRESHOOS03_SFN01       9271    //preshoos03_SFN01.dff
#define OBJ_PRESHOOS03_SFN02       9272    //preshoos03_SFN02.dff
#define OBJ_PRESHOOS01_SFN03       9273    //preshoos01_SFN03.dff
#define OBJ_PRESHOOS03_SFN03       9274    //preshoos03_SFN03.dff
#define OBJ_PRESHOOSML02_SFN01     9275    //preshoosml02_SFN01.dff
#define OBJ_LAND_SFN17             9276    //land_SFN17.dff
#define OBJ_BIGSFNLITE02           9277    //bigsfnlite02.dff
#define OBJ_BIGSFNLITE05           9278    //bigsfnlite05.dff
#define OBJ_BIGSFNLITE08           9279    //bigsfnlite08.dff
#define OBJ_BIGSFNLITE10           9280    //bigsfnlite10.dff
#define OBJ_BIGSFNLITE12           9281    //bigsfnlite12.dff
#define OBJ_BIGSFNLITE14           9282    //bigsfnlite14.dff
#define OBJ_BIGSFNLITE16           9283    //bigsfnlite16.dff
#define OBJ_LAND2_SFN02            9284    //land2_sfN02.dff
