/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAw.ide
#define OBJ_LAWROADS_LAW12         6035    //lawroads_law12.dff
#define OBJ_FILLER01_LAW           6036    //filler01_laW.dff
#define OBJ_FILLER02_LAW           6037    //filler02_laW.dff
#define OBJ_WILSHIRE2_LAW          6038    //wilshire2_law.dff
#define OBJ_WILSHIRE5_LAW          6039    //wilshire5_law.dff
#define OBJ_WILSHIRE7_LAW          6040    //wilshire7_law.dff
#define OBJ_WILSHIRE6_LAW          6041    //wilshire6_law.dff
#define OBJ_VENBLUE01_LAW          6042    //venblue01_law.dff
#define OBJ_WILSHIRE2W_LAW         6044    //wilshire2w_law.dff
#define OBJ_WILSHIRE5W_LAW         6045    //wilshire5w_law.dff
#define OBJ_HEDGE01_LAW            6046    //hedge01_law.dff
#define OBJ_WILSHIRE1_LAW          6047    //wilshire1_law.dff
#define OBJ_MALL_LAW               6048    //mall_laW.dff
#define OBJ_BEACHWALL_LAW          6049    //beachwall_law.dff
#define OBJ_BEACHHUT01_LAW         6050    //beachhut01_law.dff
#define OBJ_MALLGLASS_LAW          6051    //mallglass_laW.dff
#define OBJ_ARTCURVE_LAW           6052    //artcurve_law.dff
#define OBJ_STEPSHOP_LAW           6053    //stepshop_law.dff
#define OBJ_LAWROADS_LAW02         6054    //lawroads_law02.dff
#define OBJ_LAWROADS_LAW03         6055    //lawroads_law03.dff
#define OBJ_JETTYSIGN_LAW          6056    //jettysign_law.dff
#define OBJ_WDPANELHS09_LAW        6057    //wdpanelhs09_law.dff
#define OBJ_WDPANELHS08_LAW        6058    //wdpanelhs08_law.dff
#define OBJ_OFFVEN02_LAW           6059    //offven02_law.dff
#define OBJ_PLAZA2TOP_LAW          6060    //plaza2top_law.dff
#define OBJ_PLAZA2BOT_LAW          6061    //plaza2bot_law.dff
#define OBJ_STAPLAZ_LAW            6063    //staplaz_law.dff
#define OBJ_LABEACH_03BX           6064    //LAbeach_03bx.dff
#define OBJ_LABEACH_04BX           6065    //LAbeach_04bx.dff
#define OBJ_VENGYM_LAW             6066    //vengym_law.dff
#define OBJ_OFFVEN01_LAW           6087    //offven01_law.dff
#define OBJ_OFFVEN05_LAW           6088    //offven05_law.dff
#define OBJ_BEVGRND03B_LAW         6094    //bevgrnd03b_law.dff
#define OBJ_OFFVENSP02_LAW         6095    //offvensp02_law.dff
#define OBJ_OFFVENSP03_LAW         6096    //offvensp03_law.dff
#define OBJ_GZBUILD2_LAW           6098    //gzbuild2_law.dff
#define OBJ_GAZ3_LAW               6099    //gaz3_law.dff
#define OBJ_GAZ1_LAW               6100    //gaz1_law.dff
#define OBJ_GAZ2_LAW               6101    //gaz2_law.dff
#define OBJ_GAZ4_LAW               6102    //gaz4_LAW.dff
