/*
 * Includes for San Andreas Multiplayer+
 * 2018 - 2022, Ivan Kmeťo
 *
 * CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
 * https://creativecommons.org/publicdomain/zero/1.0/
 */


//LAn.ide
#define OBJ_POLICEST01_LAN         3975    //PoliceSt01_LAn.dff
#define OBJ_POLICEST02_LAN         3976    //PoliceSt02_LAn.dff
#define OBJ_LARIVERSEC1_LAN        3977    //LAriverSec1_LAn.dff
#define OBJ_LARIVERSEC3_LAN        3978    //LAriverSec3_LAn.dff
#define OBJ_BONAVENTURA_LAN        3979    //bonaventura_LAn.dff
#define OBJ_LACITYHALL1_LAN        3980    //LAcityhall1_LAn.dff
#define OBJ_LARIVERSEC4A_LAN       3981    //LAriverSec4a_LAn.dff
#define OBJ_LARIVERSEC5A_LAN       3982    //LAriverSec5a_LAn.dff
#define OBJ_PEUBLOMISS2_LAN        3983    //peublomiss2_LAn.dff
#define OBJ_CHURCHPROG1_LAN        3984    //churchprog1_LAn.dff
#define OBJ_PERSHINGSQ1_LAN        3985    //PershingSq1_LAn.dff
#define OBJ_MIS1_LAN               3986    //mis1_LAn.dff
#define OBJ_FIGHTPLAZA2_LAN        3987    //fightplaza2_LAn.dff
#define OBJ_CITYHALLBLOCK2_LAN     3988    //cityhallblock2_LAn.dff
#define OBJ_BONAPLAZAGR_LAN        3989    //bonaplazagr_LAn.dff
#define OBJ_GSFREEWAY6_LAN         3990    //GSFreeway6_LAn.dff
#define OBJ_GSFREEWAY7_LAN         3991    //GSFreeway7_LAn.dff
#define OBJ_ROADS03_LAN            3992    //Roads03_LAn.dff
#define OBJ_ROADS04_LAN            3993    //Roads04_LAn.dff
#define OBJ_ROADS06_LAN            3994    //Roads06_LAn.dff
#define OBJ_ROADS07_LAN            3995    //Roads07_LAn.dff
#define OBJ_ROADS08_LAN            3996    //Roads08_LAn.dff
#define OBJ_CITYHALLBLOK_LAN       3997    //cityhallblok_LAn.dff
#define OBJ_COURT1_LAN             3998    //court1_LAn.dff
#define OBJ_TWINJAIL2_LAN          4000    //twintjail2_LAn.dff
#define OBJ_BAILBONDS1_LAN         4001    //BailBonds1_LAn.dff
#define OBJ_LACITYHALL2_LAN        4002    //LAcityhall2_LAn.dff
#define OBJ_LACITYHALLTRANS_LAN    4003    //LAcityhallTrans_LAn.dff
#define OBJ_LACITYHALL3_LAN        4004    //LAcityhall3_LAn.dff
#define OBJ_DECOBLOK2_LAN          4005    //decoblok2_LAn.dff
#define OBJ_EASTCOLUMB1_LAN        4006    //eastcolumb1_LAn.dff
#define OBJ_WELLSFARGO1_LAN        4007    //wellsfargo1_LAn.dff
#define OBJ_DECOBLOK1_LAN          4008    //decoblok1_LAn.dff
#define OBJ_FIGFREE1_LAN           4010    //figfree1_LAn.dff
#define OBJ_FIGFREE2_LAN           4011    //figfree2_LAn.dff
#define OBJ_TERMANEXGRD1_LAN       4012    //TermAnexGrd1_LAn.dff
#define OBJ_BONAVENBASE_LAN        4013    //bonavenBase_LAn.dff
#define OBJ_BONAPLAZA_LAN          4014    //bonaplaza_LAn.dff
#define OBJ_BONAVENTURAGL_LAN      4015    //bonaventuraGL_LAn.dff
#define OBJ_FIGHOTBASE_LAN         4016    //fighotbase_LAn.dff
#define OBJ_OFFBLOKA_LAN           4017    //offblokA_LAn.dff
#define OBJ_NEWBUILDSM02           4018    //newbuildsm02.dff
#define OBJ_NEWBUILDSM01           4019    //newbuildsm01.dff
#define OBJ_FIGHOTBLOK1_LAN        4020    //fighotblok1_LAn.dff
#define OBJ_OFFECESML1_LAN         4021    //Officessml1_lan.dff
#define OBJ_FOODMART1_LAN          4022    //Foodmart1_lan.dff
#define OBJ_NEWDBBUILD_LAN04       4023    //newdbbuild_lan04.dff
#define OBJ_LANGRASSPATCH          4027    //langrasspatch.dff
#define OBJ_LANSTAP                4028    //lanstap.dff
#define OBJ_LARIVERSEC5B_LAN       4029    //LAriverSec5b_LAn.dff
#define OBJ_LARIVERSEC4B_LAN       4030    //LAriverSec4b_LAn.dff
#define OBJ_CARIMP_LAN             4032    //carimp_LAn.dff
#define OBJ_FIGHTPLAZA1_LAN        4033    //fightplaza1_LAn.dff
#define OBJ_FIGHTPLAZA1TRA_LAN     4034    //fightplaza1tra_LAn.dff
#define OBJ_LACITYHALL4_LAN        4048    //LAcityhall4_LAn.dff
#define OBJ_FIGHOTBLOK2_LAN        4058    //fighotblok2_LAn.dff
#define OBJ_FIGHOTBLOK3_LAN        4059    //fighotblok3_LAn.dff
#define OBJ_FIGHOTBLOK4_LAN        4060    //fighotblok4_LAn.dff
#define OBJ_TWINTJAIL1_LAN         4079    //twintjail1_LAn.dff
#define OBJ_JUD_LAN                4084    //JUD_LAN.dff
#define OBJ_SUPPORTS01_LAN         4085    //supports01_LAn.dff
#define OBJ_SUPPORTS02_LAN         4086    //supports02_LAn.dff
#define OBJ_SUPPORTS03_LAN         4087    //supports03_LAn.dff
#define OBJ_SUPPORTS04_LAN         4088    //supports04_LAn.dff
#define OBJ_SUPPORTS05_LAN         4089    //supports05_LAn.dff
#define OBJ_SUPPORTS06_LAN         4090    //supports06_LAn.dff
#define OBJ_SUPPORTS07_LAN         4091    //supports07_LAn.dff
#define OBJ_TWINTJAILFENCE_LAN     4099    //twintjailfence_LAn.dff
#define OBJ_MESHFENCE1_LAN         4100    //meshfence1_LAn.dff
